export type {
  GamePhase,
  GameplayPillar,
  GameSession,
  GameLoopAction,
  GameSessionSummary,
} from "./types";

export { VALID_TRANSITIONS, PILLAR_INSTRUCTION_MAP, CHOICE_PILLAR_MAP } from "./types";

export { transition, isValidTransition, InvalidTransitionError } from "./state-machine";

export {
  applyWorldStateChanges,
  applySanityImpact,
  addDiscoveredItems,
  partitionDiscoveredItems,
  discoveredItemLeadFact,
  actingMethodDiscoveryFact,
  applyDigestion,
  applyResolution,
  narrationOnly,
  gateLocationChange,
  isInvoluntaryMoveCause,
  INVOLUNTARY_MOVE_CAUSES,
  grantSealedArtifact,
  grantChurchArtifact,
  isChurchAffiliated,
  type ApplyWorldStateOptions,
  type GateLocationChangeInput,
  type GateLocationChangeResult,
  type InvoluntaryMoveCause,
  type ChurchArtifactGrantOutcome,
  type ChurchArtifactGrantResult,
} from "./world-state";

export { cityForLocation, isReachable, type ReachableResult } from "./place-graph";

export { createCanonCharacterSession, stripSelfFromNpcs } from "./canon-takeover";

export {
  resolveLocation,
  mapAtlasFor,
  locationLabel,
  registerCustomLocation,
  resolveCityId,
  matchDistrictSlug,
  stripCityPrefix,
  customLocationSlug,
  customToDistrict,
  isValidCustomLocationsShape,
  type ResolvedLocation,
  type MapAtlas,
} from "./location";

export {
  companionsPresentOnMove,
  emptyTrackedNpcState,
  followers,
  isValidTrackedNpcShape,
  isValidTrackedNpcStateShape,
  joinRoster,
  leaveRoster,
  markPursuer,
  reassertFollowersAt,
  resolveTrackedNpcState,
  shakeOff,
  type TrackedDisposition,
  type TrackedNpc,
  type TrackedNpcState,
} from "./tracked-npcs";

export {
  advanceActiveHunts,
  advanceHunt,
  clearHunt,
  findHunt,
  huntQuestLabel,
  huntTrackingTurns,
  isHuntReady,
  isValidHuntStateShape,
  isValidHuntsShape,
  startHunt,
  HUNT_BASE_TRACKING_TURNS,
  type HuntStartOutcome,
  type HuntStartResult,
  type HuntState,
} from "./hunt";

// Acquired powers — copied/stolen/borrowed Beyonder abilities (Error Prometheus,
// White Tower Imitation, the Ring of Mimicry / Blood Vessel Thief artifacts).
export {
  acquirePower,
  acquiredPowerAbilityLabels,
  canAcquirePower,
  capabilityForMethod,
  findAcquiredPower,
  isValidAcquiredPowerShape,
  isValidAcquiredPowersShape,
  permanentPowers,
  powerAcquisitionCapabilities,
  releasePower,
  temporaryPowers,
  tickAcquiredPowers,
  updateAcquiredPower,
  ARTIFACT_ACQUISITIONS,
  BLOOD_VESSEL_THIEF_DURATION_TURNS,
  GRAZED_SOUL_DURATION_TURNS,
  IMITATION_DURATION_TURNS,
  MAX_ACQUIRED_POWERS,
  PATHWAY_ACQUISITIONS,
  PROMETHEUS_THEFT_DURATION_TURNS,
  RING_OF_MIMICRY_DURATION_TURNS,
  SINGLE_USE_DURATION_TURNS,
  type AcquiredPower,
  type AcquirePowerInput,
  type AcquirePowerOutcome,
  type AcquirePowerResult,
  type AcquisitionCapability,
  type PowerAcquisitionMethod,
  type PowerPermanence,
  type UpdateAcquiredPowerInput,
  type UpdateAcquiredPowerOutcome,
  type UpdateAcquiredPowerResult,
} from "./acquired-powers";

// Artifice — crafting Sealed Artifacts + the player-created artifact registry.
export {
  type CustomArtifact,
  type CustomArtifactState,
  MAX_CUSTOM_ARTIFACTS,
  emptyCustomArtifactState,
  resolveCustomArtifactState,
  mintCustomArtifactItem,
  findCustomArtifact,
  customArtifactForItem,
  registerCustomArtifact,
  forgetCustomArtifact,
  craftedArtifactFact,
  isValidCustomArtifactShape,
  isValidCustomArtifactStateShape,
} from "./custom-artifacts";
export {
  PARAGON_PATHWAY_ID,
  ARTISAN_SEQUENCE,
  COMMISSION_FEE_BY_GRADE,
  SELF_CRAFT_MATERIALS_COST_BY_GRADE,
  craftCapability,
  canCraftArtifact,
  gradeForCharacteristicSequence,
  parseCharacteristicItem,
  craftFee,
  craftArtifact,
  type CraftMode,
  type CraftCapability,
  type CraftArtifactInput,
  type CraftOutcome,
  type CraftResult,
} from "./artifice";
export {
  deriveArtifactEffects,
  deriveArtifactDrawback,
  effectHookForAbility,
  carriedArtifactEffects,
  carriedEffectsByHook,
  artifactIdentityCapabilities,
  artifactSanityActions,
  artifactCombatEffects,
  artifactPowerAcquisitions,
  artifactNarratorContext,
  MAX_DERIVED_EFFECTS,
  type CarriedArtifactEffects,
  type ArtifactIdentityGrant,
  type ArtifactSanityAction,
  type ArtifactCombatEffect,
  type ArtifactPowerGrant,
} from "./artifact-effects";

// Advancement rituals — begun once, matured naturally over play (issue #209).
export {
  advanceRitual,
  beginRitual,
  clearRitual,
  isValidRitualStateShape,
  ritualCircumstanceFidelity,
  ritualFidelity,
  ritualInProgress,
  ritualNarratorContext,
  ritualQuestLabel,
  ritualStepsFor,
  RITUAL_FIDELITY_CAP,
  type RitualState,
} from "./ritual";

// The rite of ascension — the apex endgame as a paced, multi-turn rite.
export {
  advanceAscensionRite,
  ascensionRiteFidelity,
  ascensionRiteInProgress,
  ascensionRiteNarratorContext,
  ascensionRiteQuestLabel,
  ascensionRiteReady,
  ascensionTierFor,
  beginAscensionRite,
  clearAscensionRite,
  isValidAscensionRiteShape,
  ASCENSION_FIDELITY_CAP,
  ASCENSION_PROGRESS_RATE,
  type AscensionRiteState,
  type AscensionTier,
} from "./ascension-rite";

// Formula pursuit — seeking the next potion's recipe through the story (#171).
export {
  advanceFormulaPursuit,
  beginFormulaPursuit,
  clearFormulaPursuit,
  formulaPursuitQuestLabel,
  formulaPursuitTurns,
  isFormulaPursuitReady,
  isValidFormulaPursuitShape,
  secureFormulaThroughStory,
  FORMULA_PURSUIT_BASE_TURNS,
  type FormulaPursuitOutcome,
  type FormulaPursuitResult,
  type FormulaPursuitState,
  type FormulaSecureOutcome,
  type FormulaSecureResult,
} from "./formula-pursuit";

export {
  DIGESTION_MIN,
  DIGESTION_MAX,
  NEUTRAL_ALIGNMENT,
  CONTRADICTION_THRESHOLD,
  MAX_PROGRESS_PER_EVAL,
  MAX_REVERSE_PER_EVAL,
  MIN_PROGRESS_PER_SESSION,
  createDigestionState,
  computeProgressDelta,
  applyDigestionProgress,
  isDigestionComplete,
  digestionFeedback,
} from "./digestion";

export {
  canConvene,
  canFoundSociety,
  foundSociety,
  holdGathering,
  isValidSocietyShape,
  memberArc,
  memberPathwayHint,
  migrateSocietyState,
  recruitMember,
  resolveMemberArc,
  societyKindForPathway,
  GATHERING_COOLDOWN_TURNS,
  SOCIETY_FOUNDING_SEQUENCE,
  SOCIETY_KIND_LABELS,
  type GatheringOutcome,
  type SocietyKind,
  type SocietyMember,
  type SocietyState,
} from "./society";
export {
  composeDeduction,
  composeDialogueAction,
  composeRitualAction,
  detectInputMode,
  gatherClues,
  INPUT_MODE_LABELS,
  RITUAL_STEPS,
  type InputMode,
} from "./input-modes";
export {
  divergenceScore,
  evaluateAchievements,
  getAchievement,
  legacyCount,
  showcaseStats,
  ACHIEVEMENTS,
  type Achievement,
  type ShowcaseStats,
} from "./achievements";
export {
  fetchLeaderboard,
  publishShowcase,
  toShowcaseRow,
  type LeaderboardEntry,
  type LeaderboardMetric,
  type ShowcaseClient,
} from "./showcase-sync";
export {
  addItemToInventory,
  adjustFunds,
  canAfford,
  filterListings,
  getFunds,
  removeItemForListing,
  validateListing,
  vendorSaleValue,
  sellItemToVendor,
  LISTING_DAYS,
  PRICE_GUIDANCE,
  VENDOR_SALE_CATEGORIES,
  STARTING_FUNDS,
  ARTIFACT_PRICE_BY_GRADE,
  artifactPriceGuidance,
  isMarketTradeable,
  canFenceItem,
  type ListingFilter,
  type ListingStatus,
  type MarketListing,
  type VendorSaleResult,
} from "./marketplace";
export {
  createListing,
  delist,
  fetchActiveListings,
  fetchOwnHistory,
  purchase,
  type MarketplaceClient,
} from "./marketplace-sync";
export {
  composeMessage,
  getMessageTemplate,
  selectMessagesForScene,
  MAX_MESSAGES_PER_SCENE,
  MESSAGE_TEMPLATES,
  type MessageCategory,
  type MessageTemplate,
  type WorldMessage,
} from "./world-messages";
export {
  fetchLocationMessages,
  placeMessage,
  rateMessage,
  type WorldMessagesClient,
} from "./world-messages-sync";
export {
  activeIdentity,
  adjustReputation,
  applyExposure,
  checkExposure,
  createIdentity,
  createIdentityState,
  detectAssumeIdentityIntent,
  discardIdentity,
  hasPreparedIdentity,
  identityCapability,
  identityPromptContext,
  isFateProof,
  isValidIdentityStateShape,
  recordIdentityUse,
  switchIdentity,
  ASSUME_VIA_PANEL_NARRATIVE,
  EXPOSURE_EVENT_THRESHOLD,
  FATE_PROOF_THRESHOLDS,
  FLAWLESS_IDENTITY_THRESHOLDS,
  FULL_IDENTITY_THRESHOLDS,
  MAX_BASIC_IDENTITIES,
  UNPREPARED_IDENTITY_NARRATIVE,
  type ExposureEvent,
  type Identity,
  type IdentityCapability,
  type IdentityState,
  type NewIdentityFields,
  type SocialClass,
} from "./identity";
export {
  addProfileNote,
  applyProfileChange,
  applyProfileEdits,
  createProfileState,
  editProfileNote,
  isDrasticChange,
  isValidProfileStateShape,
  openRecognitionGap,
  pierceRecognition,
  profilePromptContext,
  proposalToChange,
  recognitionPromptContext,
  recordRecognition,
  removeProfileNote,
  renameTrueSelf,
  resolveProfileState,
  validateSelfChangeProposal,
  RECOGNITION_PIERCE_CHANCE,
  SELF_CHANGE_FIELDS,
  type ApplyProfileChangeOptions,
  type DemeanorTrait,
  type DrasticChangeContext,
  type PierceResult,
  type ProfileChange,
  type ProfileEdits,
  type ProfileNote,
  type ProfileState,
  type RecognitionGap,
  type SelfChangeField,
  type SelfChangeProposal,
  type TrueSelfProfile,
} from "./profile";
export {
  transformationRiteFor,
  TRANSFORMATION_RITES,
  type TransformationRite,
} from "./transformation-rites";
export {
  anchorHighRisk,
  anchorPressure,
  anchorsRelevant,
  canConsecrateCongregation,
  consecrateAnchor,
  damageAnchor,
  effectiveSupport,
  emptyAnchorState,
  isLost,
  isUnderAnchored,
  isValidAnchorStateShape,
  loseAnchor,
  repairAnchor,
  requiredSupport,
  requiresAnchors,
  supportShortfall,
  ANCHOR_INTEGRITY_MAX,
  ANCHOR_INTEGRITY_MIN,
  ANCHOR_KIND_WEIGHT,
  ANGEL_SUPPORT_PER_STEP,
  DEMIGOD_TRAITS,
  MAX_ANCHOR_PRESSURE,
  PRESSURE_SHORTFALL_SCALE,
  SAINT_REQUIRED_SUPPORT,
  type Anchor,
  type AnchorKind,
  type AnchorState,
  type DemigodTraits,
  type NewAnchorFields,
} from "./anchors";
export {
  applyCodexUpdate,
  applyCodexUpdates,
  codexCounts,
  codexRebuildDigest,
  filterCodexEntities,
  emptyCodexState,
  isValidCodexStateShape,
  mergeCodexEntities,
  pinnedEntitiesForPrompt,
  recordCodexTurn,
  removeCodexEntity,
  resolveCodexState,
  seedCodexFromSession,
  selectPinnedEntities,
  setCodexImportance,
  touchCodexEntities,
  updateCodexEntity,
  CODEX_KINDS,
  MAX_CODEX_ENTITIES,
  MAX_PINNED_ENTITIES,
  type CodexEdit,
  type CodexEntity,
  type CodexFilter,
  type CodexImportance,
  type CodexKind,
  type CodexState,
} from "./codex";
export {
  FREE_TEXT_CHOICE_ID,
  FREE_TEXT_MAX_LENGTH,
  freeTextRejection,
  freeTextToChoice,
  validateFreeText,
  type FreeTextRejection,
  type FreeTextValidation,
} from "./free-text";
export {
  TUTORIAL_REQUIRED_TOPICS,
  TUTORIAL_SCENES,
  type TutorialScene,
} from "./tutorial";
export {
  applySetback,
  buildLegacy,
  deserializeLegacies,
  endSession,
  evaluateFailure,
  fallbackDescentScene,
  legaciesToFacts,
  serializeLegacies,
  SETBACK_SANITY_RATIO,
  type CharacterLegacy,
  type FailureCause,
  type FailureContext,
  type FailureOutcome,
  type FailureVerdict,
  type LegacyFate,
  type LegacyRole,
  type SetbackResult,
} from "./death";
export {
  apotheosisRequirements,
  apotheosisSuccessChance,
  attemptApotheosis,
  canAttemptApotheosis,
  drawPetition,
  sequenceAbilities,
  apexAbilityView,
  type ApexAbilityView,
  sequenceClassificationFor,
  sequenceLabel,
  type SequenceTier,
  trueGodName,
  uniquenessItemFor,
  ABOVE_SEQUENCE_TEASE,
  APOTHEOSIS_SANITY_RATIO,
  APOTHEOSIS_STAGES,
  PETITION_CHANCE,
  TRUE_GOD_ABILITIES,
  TRUE_GOD_NAMES,
  type ApotheosisAscended,
  type ApotheosisRequirement,
  type ApotheosisResult,
  type ApotheosisUnmade,
} from "./apotheosis";

// The Pillars — the mechanical apex above Sequence 0 (issue #99 Part B).
export {
  attemptPillarAscension,
  canAttemptPillarAscension,
  pillarAscensionSuccessChance,
  pillarName,
  pillarRequirements,
  ABOVE_THE_SEQUENCE_TEASE,
  PILLAR_ABILITIES,
  PILLAR_REQUIRED_SUPPORT,
  PILLAR_SANITY_RATIO,
  PILLAR_SEQUENCE,
  PILLAR_STAGES,
  type PillarAscensionResult,
  type PillarEnthroned,
  type PillarRequirement,
  type PillarUnmade,
} from "./pillars";

export {
  advancementHighRisk,
  advancementRequirements,
  advancementSuccessChance,
  attemptAdvancement,
  canAdvance,
  isAdvanceableSequence,
  meetsRequirements,
  ritualRequiredFor,
  targetSequence,
  ADVANCEMENT_SANITY_RATIO,
  MAX_ADVANCEABLE_SEQUENCE,
  MIN_ADVANCEABLE_SEQUENCE,
  RITUAL_REQUIRED_AT_OR_BELOW,
  type AdvancementAdvanced,
  type AdvancementLostControl,
  type AdvancementRequirement,
  type AdvancementResult,
} from "./advancement";
export {
  acquisitionCost,
  acquisitionDepthFactor,
  acquisitionMethodsFor,
  deliverHuntedItem,
  huntLootReward,
  nextPotionItems,
  potionPreparationPlan,
  purchasePotionItem,
  ACQUISITION_DEPTH_STEP,
  HUNT_LOOT_BASE,
  MAIN_INGREDIENT_HUNT_ONLY_AT_OR_BELOW,
  type AcquisitionMethod,
  type HuntOutcome,
  type HuntResult,
  crossPathwayAcquisitionCost,
  crossPathwayPotionPlan,
  hasCrossPathwayPotion,
  purchaseCrossPathwayPotionItem,
  CROSS_PATHWAY_COST_PREMIUM,
  type PotionItemStatus,
  type PotionPreparationPlan,
  type CrossPathwayPotionPlan,
  type PurchaseOutcome,
  type PurchaseResult,
} from "./potion-preparation";
export {
  hasSwitchedPathways,
  retainedAbilitiesFor,
  makePathwaySwitch,
  recordPathwaySwitch,
  fusedRetainedAbilities,
  isValidPathwayLineageShape,
  type RetainedAbility,
  type PathwaySwitch,
  type PathwayLineageState,
} from "./pathway-lineage";
export {
  emptyLedger,
  resolveCharacteristicLedger,
  isValidCharacteristicLedgerShape,
  ledgerCharacteristicItemName,
  precipitatedItemsFor,
  recordPrecipitation,
  convergenceFor,
  convergenceNarratorContext,
  precipitationFact,
} from "./characteristic-ledger";
export {
  switchUnlockSequence,
  switchTargetSequence,
  switchRelation,
  switchRequirements,
  meetsSwitchRequirements,
  canAttemptSwitch,
  pathwaySwitchSuccessChance,
  switchHighRisk,
  attemptPathwaySwitch,
  neighboringSwitchTargets,
  type SwitchRelation,
  type SwitchRequirement,
  type PathwaySwitched,
  type PathwaySwitchLostControl,
  type PathwaySwitchResult,
} from "./pathway-switch";
export {
  hasItem,
  hasItemMatching,
  isReagentCategory,
  isConsumable,
  removeItemsByName,
  REAGENT_CATEGORIES,
} from "./inventory";
export {
  artifactToItem,
  deserializeArtifacts,
  discoverableArtifacts,
  echoFacts,
  mintArtifact,
  pickStartingEcho,
  serializeArtifacts,
  type TimelineArtifact,
} from "./echoes";
export {
  addAnnotation,
  addJournalEntries,
  annotationsFor,
  buildJournalEntry,
  createJournal,
  deleteAnnotation,
  deriveJournalEntries,
  deserializeJournal,
  editAnnotation,
  filterJournal,
  journalEventLabel,
  journalToMarkdown,
  JOURNAL_EVENT_TYPES,
  serializeJournal,
  validateJournalFlag,
  type Journal,
  type JournalAnnotation,
  type JournalEntry,
  type JournalEventType,
  type JournalFilter,
} from "./journal";
export {
  deleteAnnotationRemote,
  deleteSessionEntriesRemote,
  syncAnnotation,
  syncEntries,
  syncJournal,
  toAnnotationRow,
  toEntryRow,
  type JournalSyncClient,
} from "./journal-sync";
export {
  deleteSessionRemote,
  fetchSessions,
  pushSessions,
  reconcile,
  setActiveRemote,
  toSessionRow,
  type FetchedSessions,
  type SessionReconciliation,
  type SessionSyncClient,
} from "./session-sync";
export {
  fetchWorldMemory,
  legacyKey,
  pushWorldMemory,
  reconcileWorldMemory,
  type WorldMemory,
  type WorldMemorySynced,
  type WorldMemorySyncClient,
} from "./world-memory-sync";
export {
  fetchPreferences,
  pushPreferences,
  reconcilePreferences,
  type PreferencesSyncClient,
  type SyncedPreferences,
} from "./preferences-sync";
export {
  advanceCanonPosition,
  createSession,
  createDefaultGameState,
  seedArchetype,
  DEFAULT_CANON_POSITION,
  type CreateSessionOptions,
  sessionToSummary,
  serializeSession,
  deserializeSession,
  isValidSessionShape,
  isValidDigestionShape,
  isValidInjuriesShape,
} from "./session";

export {
  CITIES,
  CONTINENT_CROSSING_DAYS,
  CROSSING_CITY,
  canTravelTo,
  cityIdFromLocation,
  continentOf,
  crossesContinent,
  getCity,
  grantAccessFlag,
  hasAccessFlag,
  isValidAccessFlagsShape,
  meetsAccessGate,
  reachedDreamWorldGate,
  travelDays,
  travelTo,
  type City,
  type TravelResult,
} from "./travel";

export {
  buildRetrievalQuery,
  toRetrievedLoreChunks,
  RETRIEVAL_QUERY_CHAR_CAP,
} from "./lore-retrieval";

export {
  AMBUSH_PREP_CAP,
  VICTORY_THRESHOLD,
  DEFEAT_THRESHOLD,
  DECISION_POINT_COUNT,
  INJURY_RECOVERY_TURNS,
  INJURY_PENALTY_CAP,
  emptyPreparation,
  scorePreparation,
  computeSequenceGap,
  computePathwayMatchup,
  computeInjuryPenalty,
  computeBaseAdvantage,
  generateDecisionPoints,
  deriveEncounterEnemy,
  deriveEncounter,
  deriveHuntQuarry,
  selectOpponents,
  bestiaryFoeToEnemy,
  isReconcilableFraming,
  coerceAllyFraming,
  makeEncounterContext,
  framingLabel,
  describeFraming,
  enemyIntel,
  createEncounter,
  applyPreparation,
  chooseOption,
  isExchangeComplete,
  resolveOutcome,
  isWinningOutcome,
  computeConsequences,
  resolveEncounter,
  applyCombatResult,
  tickInjuries,
  combatNarrationContext,
  isValidEncounterShape,
  controlTierFor,
  controlTierLabel,
  describeControlTier,
  seedControlStrain,
  stanceForPoint,
  stanceLabel,
  describeStance,
  threatAssessment,
  afterActionReport,
  MAX_DYNAMIC_ARTIFACT_OPTIONS_PER_POINT,
  type CreateEncounterOptions,
  type EnemyIntel,
  type OpponentOption,
  type SelectOpponentsOptions,
  type OutcomeInput,
  type ResolutionLineTally,
  type DangerTier,
  type OddsBand,
  type ThreatAssessment,
  type AfterActionReport,
} from "./combat";

export {
  combatKitFor,
  combatAbilityFrom,
  classifyAbility,
  abilityKindTag,
  type KitSourceAbility,
} from "./combat-abilities";

export {
  fusedAbilityNames,
  fusedCombatKit,
  currentJoinSequence,
  heldCumulativeAbilities,
  heldAbilityGroups,
  retainedAbilityGroups,
  type RetainedAbilityGroup,
} from "./pathway-fusion";

export type {
  IntelligenceLevel,
  TerrainAdvantage,
  Enemy,
  EncounterFraming,
  EncounterContext,
  AbilityKind,
  CombatAbility,
  CombatPreparationInput,
  PreparationTier,
  PreparationQuality,
  MatchupRelation,
  PathwayMatchup,
  DecisionKind,
  ResolutionLine,
  ControlTier,
  EnemyStance,
  DecisionOption,
  DecisionPoint,
  CombatOutcome,
  InjurySeverity,
  Injury,
  CombatResult,
  CombatControlVerdict,
  CombatPhase,
  CombatEncounter,
} from "@/lib/types/combat";

export {
  SESSION_KEY_PREFIX,
  SESSION_INDEX_KEY,
  ACTIVE_SESSION_KEY,
  PROVIDER_CONFIG_KEY,
  IMAGE_PROVIDER_CONFIG_KEY,
  PROLOGUE_DRAFT_KEY,
  MODELS_CACHE_KEY,
  PREFERENCES_KEY,
  JOURNAL_KEY_PREFIX,
  LEGACIES_KEY,
  ECHOES_KEY,
  HINT_KEY_PREFIX,
  CLOUD_SYNCED_KEY,
  COMBAT_KEY_PREFIX,
  USAGE_KEY_PREFIX,
} from "./constants";

export { characterDeletionPlan, type CharacterDeletionPlan } from "./character-admin";

export {
  TEST_CHARACTER_ID,
  createTestCharacter,
  devToolsEnabled,
  isUndeletableCharacter,
} from "./dev-tools";

export {
  ADMIN_CHARACTER_ID_PREFIX,
  buildAdminCharacter,
  makeAdvancementReadyState,
  makeAdvancementReady,
  setSessionSanity,
  setSessionFunds,
  grantArtifactsToSession,
  forceLossOfControl,
  lossOfControlPreview,
  type AdminCharacterOptions,
  type AdminAcquiredPowerSpec,
  type AdminAnchorSpec,
  type AdminEndgame,
} from "./admin-tools";

export {
  SANITY_MIN,
  SANITY_TIER_THRESHOLDS,
  SANITY_EFFECTS,
  ABILITY_USE_BASE_DRAIN,
  ABILITY_USE_PER_SEQUENCE,
  HORROR_BASE_DRAIN,
  HORROR_PER_GAP,
  MAX_HORROR_DRAIN,
  ADVANCEMENT_DRAIN,
  OUTER_DEITY_DRAIN,
  ACTING_SUCCESS_RECOVERY,
  REST_RECOVERY,
  HUMAN_CONNECTION_RECOVERY,
  ROUTINE_RECOVERY,
  ACTING_NEGLECT_DECAY,
  HORROR_TAG_GAP,
  SANITY_EVENT_TAGS,
  SANITY_RESIDUAL_CAP,
  sanityPercent,
  classifySanityTier,
  sanityEffects,
  SANITY_DESCRIPTORS,
  sanityDescriptor,
  sanityDelta,
  sanityDeltaForTags,
  inRoleDrainMultiplier,
  SANITY_DRAIN_INROLE_RELIEF,
  inRoleRecovery,
  IN_ROLE_RECOVERY_MAX,
  knownSanityTags,
  previewSanityImpact,
  isLossOfControl,
  evaluateLossOfControl,
} from "./sanity";

export type {
  SanityTier,
  SanityEffectProfile,
  SanityEvent,
  SanityEventTag,
  SanityBreakdown,
  LossOfControlSeverity,
  LossOfControlContext,
} from "./sanity";

export {
  DEFAULT_PREFERENCES,
  isValidPreferencesShape,
  mergePreferences,
  serializePreferences,
  deserializePreferences,
} from "./preferences";

export type { GamePreferences } from "./preferences";

export {
  createActingMethodState,
  evaluateActingDiscovery,
  isValidActingMethodStateShape,
  resolveActingMethodState,
  ACTING_ALIGNED_THRESHOLD,
  ACTING_DISCOVERY_STREAK,
  type ActingDiscoveryResult,
  type ActingDiscoveryTrigger,
  type ActingMethodState,
} from "./acting-method";

export { isValidDraftShape, isActivePrologueDraft, clearDraft } from "./prologue-draft";

export type { PrologueDraft } from "./prologue-draft";

export {
  POTION_HEADINGS,
  FIRST_POTION_NARRATIVE,
  PATHWAY_DESCRIPTIONS,
  dominantAffinity,
  tallyAffinities,
  rankPathways,
  selectTopCandidates,
  createPrologueMemory,
  createAIPrologueMemory,
  buildPrologueRecap,
  RECAP_FINALE_CHAR_CAP,
} from "./prologue";

export type { PathwayScore, PrologueRecapInput } from "./prologue";

export {
  validateBackstorySequence,
  type BackstoryViolation,
  type BackstoryValidationResult,
} from "./backstory-validation";
