"use client";

import { useCallback, useRef, useState, useSyncExternalStore } from "react";
import type { ImageProviderId, ImageProviderConfig } from "@/lib/ai";
import {
  IMAGE_PROVIDER_MODELS,
  defaultImageBaseUrl,
  imageProviderNeedsBaseUrl,
  imageProviderNeedsModel,
  imageProviderRequiresKey,
} from "@/lib/ai";
import { IMAGE_PROVIDER_CONFIG_KEY } from "@/lib/game";
import { noopSubscribe } from "@/lib/react";

// Independent image-provider configuration (image model selection). Scene art
// is generated by a provider/model chosen SEPARATELY from the text narrator —
// so a player running Ollama for text can still drop in an OpenAI key only for
// images, or point at a local Stable Diffusion / Ollama image model, or leave
// it unset. BYOK, browser-direct, key stored only in this browser.

// Ollama Cloud is intentionally absent: ollama.com hosts no image-generation
// endpoint (its image models run locally only), so it can never produce art.
const PROVIDERS: { id: ImageProviderId; label: string }[] = [
  { id: "openai", label: "OpenAI" },
  { id: "ollama", label: "Ollama (local)" },
  { id: "local-sd", label: "Stable Diffusion (local)" },
];

// Sentinel option that reveals the free-text model field for the diffusion
// backends whose catalogs vary per install.
const CUSTOM_MODEL = "__custom__";

type SaveStatus = "saved" | "unsaved" | "saving";

interface FormState {
  providerId: ImageProviderId;
  apiKey: string;
  baseUrl: string;
  model: string;
  /** True when the model is entered as free text rather than picked from the list. */
  customModel: boolean;
}

function catalogFor(providerId: ImageProviderId) {
  return IMAGE_PROVIDER_MODELS[providerId];
}

function defaultModel(providerId: ImageProviderId): string {
  return catalogFor(providerId)[0]?.id ?? "";
}

function freshState(providerId: ImageProviderId): FormState {
  return {
    providerId,
    apiKey: "",
    baseUrl: imageProviderNeedsBaseUrl(providerId) ? defaultImageBaseUrl(providerId) : "",
    model: defaultModel(providerId),
    customModel: false,
  };
}

const defaultFormState: FormState = freshState("openai");

function loadInitialState(): FormState {
  if (typeof window === "undefined") return defaultFormState;
  try {
    const raw = localStorage.getItem(IMAGE_PROVIDER_CONFIG_KEY);
    if (!raw) return defaultFormState;
    const config = JSON.parse(raw) as ImageProviderConfig;
    if (!PROVIDERS.some((p) => p.id === config.providerId)) return defaultFormState;
    const inCatalog = catalogFor(config.providerId).some((m) => m.id === config.model);
    return {
      providerId: config.providerId,
      apiKey: config.apiKey ?? "",
      baseUrl: config.baseUrl ?? "",
      model: config.model ?? "",
      // A saved model absent from the catalog was entered by hand — keep editing it as text.
      customModel: !!config.model && !inCatalog,
    };
  } catch {
    return defaultFormState;
  }
}

export function ImageProviderConfig() {
  const cacheRef = useRef<FormState | null>(null);
  const initialState = useSyncExternalStore(
    noopSubscribe,
    () => {
      if (cacheRef.current === null) cacheRef.current = loadInitialState();
      return cacheRef.current;
    },
    () => defaultFormState,
  );

  // Derive from the reactive snapshot until an edit overrides it (the SSR-safe
  // pattern the other settings panels use — `useState(initialState)` would
  // freeze on the server fallback after a full page load).
  const [formOverride, setFormOverride] = useState<FormState | null>(null);
  const form = formOverride ?? initialState;
  const [showKey, setShowKey] = useState(false);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>("saved");

  const requiresKey = imageProviderRequiresKey(form.providerId);
  const needsBaseUrl = imageProviderNeedsBaseUrl(form.providerId);
  const needsModel = imageProviderNeedsModel(form.providerId);
  const catalog = catalogFor(form.providerId);

  const updateField = useCallback(
    <K extends keyof FormState>(field: K, value: FormState[K]) => {
      setFormOverride((prev) => ({ ...(prev ?? initialState), [field]: value }));
      setSaveStatus("unsaved");
    },
    [initialState],
  );

  const handleProviderChange = useCallback((id: ImageProviderId) => {
    setFormOverride(freshState(id));
    setSaveStatus("unsaved");
  }, []);

  const handleModelSelect = useCallback(
    (value: string) => {
      if (value === CUSTOM_MODEL) {
        setFormOverride((prev) => ({ ...(prev ?? initialState), customModel: true }));
      } else {
        setFormOverride((prev) => ({
          ...(prev ?? initialState),
          model: value,
          customModel: false,
        }));
      }
      setSaveStatus("unsaved");
    },
    [initialState],
  );

  const handleSave = useCallback(() => {
    setSaveStatus("saving");
    const config: ImageProviderConfig = {
      providerId: form.providerId,
      apiKey: form.apiKey,
      baseUrl: needsBaseUrl ? form.baseUrl : undefined,
      model: form.model,
    };
    try {
      localStorage.setItem(IMAGE_PROVIDER_CONFIG_KEY, JSON.stringify(config));
      setSaveStatus("saved");
    } catch {
      setSaveStatus("unsaved");
    }
  }, [form, needsBaseUrl]);

  const handleRemoveKey = useCallback(() => {
    setFormOverride((prev) => ({ ...(prev ?? initialState), apiKey: "" }));
    try {
      const raw = localStorage.getItem(IMAGE_PROVIDER_CONFIG_KEY);
      if (raw) {
        const stored = JSON.parse(raw) as Record<string, unknown>;
        localStorage.setItem(
          IMAGE_PROVIDER_CONFIG_KEY,
          JSON.stringify({ ...stored, apiKey: "" }),
        );
      }
    } catch {
      // Storage unavailable — the in-memory form is still cleared.
    }
    setSaveStatus("unsaved");
  }, [initialState]);

  const showCustomModelField = needsModel && (form.customModel || catalog.length === 0);
  const selectValue = form.customModel ? CUSTOM_MODEL : form.model;

  return (
    <div className="space-y-8 animate-fade-in-up">
      {/* Provider Selector */}
      <fieldset>
        <legend className="mb-3 font-serif text-sm font-semibold tracking-wide text-foreground/80 uppercase">
          Image provider
        </legend>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {PROVIDERS.map((p) => (
            <button
              key={p.id}
              type="button"
              onClick={() => handleProviderChange(p.id)}
              aria-pressed={form.providerId === p.id}
              className={`group relative rounded-md border px-3 py-2.5 text-sm transition-all duration-200 ${
                form.providerId === p.id
                  ? "border-amber/60 bg-amber/[0.08] text-amber shadow-[inset_0_1px_0_rgba(217,119,6,0.1),0_0_12px_rgba(217,119,6,0.06)]"
                  : "border-border bg-surface text-muted hover:border-amber/20 hover:text-foreground/80"
              }`}
            >
              <span
                className={`absolute top-1.5 right-1.5 h-1.5 w-1.5 rounded-full transition-all duration-200 ${
                  form.providerId === p.id
                    ? "bg-amber shadow-[0_0_6px_var(--color-amber)]"
                    : "bg-transparent"
                }`}
                aria-hidden="true"
              />
              {p.label}
            </button>
          ))}
        </div>
      </fieldset>

      {/* API Key */}
      <fieldset>
        <legend className="mb-3 font-serif text-sm font-semibold tracking-wide text-foreground/80 uppercase">
          {requiresKey ? "API Key" : "Connection"}
        </legend>
        {requiresKey ? (
          <div className="relative">
            <input
              id="image-api-key"
              aria-label="Image provider API key"
              type={showKey ? "text" : "password"}
              value={form.apiKey}
              onChange={(e) => updateField("apiKey", e.target.value)}
              placeholder="sk-..."
              autoComplete="off"
              className="w-full rounded-md border border-border bg-background px-4 py-3 pr-20 font-mono text-sm text-foreground placeholder-muted transition-colors duration-200 focus:border-amber/50 focus:outline-none focus:ring-1 focus:ring-amber/20"
            />
            <button
              type="button"
              onClick={() => setShowKey(!showKey)}
              aria-pressed={showKey}
              aria-controls="image-api-key"
              aria-label={showKey ? "Hide API key" : "Show API key"}
              className="absolute top-1/2 right-3 flex min-h-[24px] -translate-y-1/2 items-center rounded px-2 py-1 text-xs text-muted transition-colors hover:text-amber"
            >
              {showKey ? "Hide" : "Show"}
            </button>
          </div>
        ) : null}
        <p className="mt-2 text-xs leading-relaxed text-muted">
          {form.providerId === "openai"
            ? "Your OpenAI key, used only for images — independent of your narrator provider. Stored only in this browser, sent only to OpenAI. Roughly $0.04 per image."
            : form.providerId === "ollama"
              ? "Local Ollama (experimental image generation) — no key required. Ensure Ollama is running with an image model pulled (e.g. z-image-turbo). Image generation is on-device only — an ollama.com cloud key has no image endpoint to call."
              : "A local Stable Diffusion WebUI (Automatic1111/Forge) with its API enabled — no key required. Set the base URL below."}
        </p>
      </fieldset>

      {/* Base URL (conditional) */}
      {needsBaseUrl && (
        <fieldset>
          <legend className="mb-3 font-serif text-sm font-semibold tracking-wide text-foreground/80 uppercase">
            Base URL
          </legend>
          <input
            type="url"
            aria-label="Image provider base URL"
            value={form.baseUrl}
            onChange={(e) => updateField("baseUrl", e.target.value)}
            placeholder={defaultImageBaseUrl(form.providerId)}
            className="w-full rounded-md border border-border bg-background px-4 py-3 font-mono text-sm text-foreground placeholder-muted transition-colors duration-200 focus:border-amber/50 focus:outline-none focus:ring-1 focus:ring-amber/20"
          />
        </fieldset>
      )}

      {/* Model */}
      <fieldset>
        <legend className="mb-3 font-serif text-sm font-semibold tracking-wide text-foreground/80 uppercase">
          Image model
        </legend>
        {needsModel ? (
          <div className="space-y-3">
            {catalog.length > 0 && (
              <select
                id="image-model"
                aria-label="Image model"
                value={selectValue}
                onChange={(e) => handleModelSelect(e.target.value)}
                className="w-full rounded-md border border-border bg-background px-4 py-2.5 text-sm text-foreground transition-colors duration-200 focus:border-amber/50 focus:outline-none focus:ring-1 focus:ring-amber/20"
              >
                {catalog.map((m) => (
                  <option key={m.id} value={m.id}>
                    {m.name}
                  </option>
                ))}
                <option value={CUSTOM_MODEL}>Custom model…</option>
              </select>
            )}
            {showCustomModelField && (
              <input
                id="image-model-custom"
                type="text"
                aria-label="Custom image model id"
                value={form.model}
                onChange={(e) => updateField("model", e.target.value)}
                placeholder="e.g. z-image-turbo or x/flux2-klein:9b"
                className="w-full rounded-md border border-border bg-background px-4 py-2.5 font-mono text-sm text-foreground placeholder-muted transition-colors duration-200 focus:border-amber/50 focus:outline-none focus:ring-1 focus:ring-amber/20"
              />
            )}
          </div>
        ) : (
          <input
            id="image-model"
            type="text"
            aria-label="Image model or checkpoint"
            value={form.model}
            onChange={(e) => updateField("model", e.target.value)}
            placeholder="Checkpoint name (optional — uses the WebUI's loaded model)"
            className="w-full rounded-md border border-border bg-background px-4 py-2.5 font-mono text-sm text-foreground placeholder-muted transition-colors duration-200 focus:border-amber/50 focus:outline-none focus:ring-1 focus:ring-amber/20"
          />
        )}
      </fieldset>

      {/* Actions */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={handleSave}
            disabled={saveStatus === "saving" || saveStatus === "saved"}
            className="rounded-md bg-amber/90 px-4 py-2 text-sm font-medium text-background transition-all duration-200 hover:bg-amber disabled:cursor-not-allowed disabled:opacity-40"
          >
            {saveStatus === "saving"
              ? "Saving..."
              : saveStatus === "saved"
                ? "Saved"
                : "Save image settings"}
          </button>
          {requiresKey && form.apiKey && (
            <button
              type="button"
              onClick={handleRemoveKey}
              className="rounded-md border border-crimson/30 px-4 py-2 text-sm font-medium text-sanity-low transition-all duration-200 hover:border-crimson/50 hover:bg-crimson/[0.06]"
            >
              Remove key
            </button>
          )}
        </div>
        <div role="status" className="flex items-center gap-4 text-xs">
          {saveStatus === "unsaved" && (
            <span className="text-muted italic">Unsaved changes</span>
          )}
          {saveStatus === "saved" && (
            <span className="text-muted">Image settings saved</span>
          )}
        </div>
      </div>
    </div>
  );
}
