import type { LoreEntry } from "./types";

export const BACKLUND_LORE: LoreEntry[] = [
  {
    slug: "backlund-city-overview",
    title: "Backlund — Overview",
    category: "location",
    content: `Backlund is the capital of the Loen Kingdom and the largest city of the Northern Continent, a metropolis of over five million people that styles itself the "Land of Hope" and the "City of Cities." It is also bitterly nicknamed the "Capital of Dust" for the atmospheric pollution that hangs over it. Sitting in the middle of the kingdom, only dozens of kilometres from the Sonia Sea, the city is split into two halves by the Tussock River, which flows to the southeast; the two banks are joined by the Backlund Bridge and by ferries. In the Fourth Epoch it was the capital of the Tudor-Trunsoest United Empire, and beneath its streets lie countless ancient ruins. Industry, opera, fashion, and finance all flourish here — anything can be had for the right price — but so does desperate poverty, and the Churches quietly press the nobility to reform the slums lest misery breed the descent of an evil god. All three orthodox Beyonder organizations active in the midlands maintain a far heavier presence here than in a provincial town like Tingen, and the capital teems with both Church-affiliated and unaffiliated Beyonders.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "loen-kingdom", "capital", "fifth-epoch"],
    tokenCount: 240,
  },
  {
    slug: "backlund-empress-borough",
    title: "Backlund — Empress Borough",
    category: "location",
    content: `Empress Borough is one of Backlund's class-defined boroughs, the heart of wealth, fashion, and high society on the more refined bank of the Tussock River. Where the city's cardinal boroughs — North, South, East, and West — are named for direction, the four class boroughs (Empress, Cherwood, Hillston, and St. George) are named for status, and Empress sits at the top. Here stand the townhouses of the nobility, the most exclusive clubs and salons, the grand opera houses, and shops selling goods from across both continents. Each borough is nearly the size of all of Tingen City, so even this single district is a small city in its own right. Wide, well-lit avenues are swept daily and patrolled openly; carriages of lacquered black roll between glittering windows. The borough is the social stage on which the kingdom's great families perform their rivalries — through marriages, investments, and parliamentary intrigue — and where collectors of rare and dangerous curios quietly trade behind respectable doors.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["district", "upper-class", "high-society", "setting"],
    tokenCount: 215,
  },
  {
    slug: "backlund-hillston-borough",
    title: "Backlund — Hillston Borough",
    category: "location",
    content: `Hillston Borough is the borough of the comfortable and the aspiring — the bourgeoisie, prosperous merchants, senior civil servants, and professionals who have climbed clear of the working districts but cannot yet pretend to the heights of Empress Borough. Detached and semi-detached houses with small gardens line orderly streets; respectability here is a daily performance, maintained with domestic staff, calling cards, and careful attention to which clubs one belongs to. Like every borough of Backlund it is nearly the size of Tingen City entire. Hillston is the natural habitat of the rising middle class produced by the kingdom's reforms — the Civil Servant Unified Examination and expanded education have swelled their ranks — and of the new money made in industry and finance. For the Beyonder world it is significant ground: organizations that recruit the educated and the ambitious, such as the psychiatry-fronted alchemists, find fertile soil among Hillston's discreetly anxious strivers, and more than one unremarkable townhouse conceals a private collection of sealed curios.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["district", "middle-class", "setting", "social-stratification"],
    tokenCount: 205,
  },
  {
    slug: "backlund-east-borough",
    title: "Backlund — East Borough",
    category: "location",
    content: `East Borough is the vast working heart of Backlund — at least twice the size of any other borough, a sprawl of tenements, factories, foundries, and the smoke-spewing industrial district that gives the capital its choking air. Here live the labourers, dockhands, costermongers, and the desperately poor, packed into back-to-backs and rookeries where a single yellow-lit room may house a whole family. It was over East Borough, the dock area, and the factory quarter that the deadly smog of the winter of 1349 settled, killing tens of thousands. The squalor and resentment of the lower districts is exactly what the Churches fear: a breeding ground where misery might be harnessed to call down an evil god, and indeed cults have schemed to use precisely this. Beneath East Borough run sewers grander than those of any other city, and below them older tunnels still — the strata of a capital that has been inhabited since before the Fifth Epoch began.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["district", "working-class", "industrial", "poverty", "setting"],
    tokenCount: 215,
  },
  {
    slug: "backlund-bridge-tussock",
    title: "Backlund — The Backlund Bridge & the Tussock River",
    category: "location",
    content: `The Tussock River cuts Backlund in two as it flows southeast toward the distant Sonia Sea, and the Backlund Bridge — together with a traffic of ferries — is the great seam that stitches the city's two halves together. The same river that gives Tingen its docks far upstream becomes, here in the capital, a crowded artery of barges, lighters, and seagoing vessels feeding the dockland "shipyards" that line the waterfront. The bridge itself is a landmark and a thoroughfare: a river of carriages, omnibuses, and pedestrians crossing above a river of water, where the two distinct halves of Backlund society meet and mingle in transit. Fog rolls thick off the water at dusk, and the embankments below are a world apart from the boroughs above — mudlarks, watermen, and those with reasons to avoid the bridge's gaslight. Because maritime and waterborne supernatural incidents fall to the Church of the Lord of Storms, its Beyonders keep a particular watch over the river, the bridge, and the dockland districts.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["landmark", "waterway", "bridge", "docks", "setting"],
    tokenCount: 220,
  },
  {
    slug: "backlund-boroughs-structure",
    title: "Backlund — The Boroughs of the Capital",
    category: "location",
    content: `Backlund is administered as a patchwork of boroughs, and to know the capital is to know which borough a thing happens in. Four CARDINAL boroughs — North, South, East, and West — divide the city by geography, while four CLASS boroughs divide it by station: Empress Borough, where the nobility and the rich keep their townhouses behind the city's best security; Hillston Borough, the financial and business heart, home to the banks and the Stock Exchange; Cherwood Borough, the comfortable middle along the river; and St. George Borough, the industrial working district of factories and the labouring poor. Each borough is nearly the size of all of Tingen City, so a Backlunder may live an entire life within one and rarely set foot in another. The Tussock River is the great divide between the refined bank and the working bank, and a person's address announces their rank before they speak a word. For a Beyonder this geography is practical knowledge: the orthodox Churches and the capital's hidden factions concentrate their attention very differently from borough to borough, and a face that belongs in Empress Borough draws suspicion in the rookeries of the East — and the reverse just as surely.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["geography", "districts", "social-stratification", "setting"],
    tokenCount: 230,
    narratorOnly: false,
  },
  {
    slug: "backlund-harbor-docklands",
    title: "Backlund — Backlund Harbor & the Docklands",
    category: "location",
    content: `Where the Tussock River widens toward the distant Sonia Sea, Backlund becomes a working harbour: a forest of masts and smokestacks, wet-docks and dry-docks, warehouses and customs houses, and the long shipyards that build and mend the vessels of the largest port-capital on the Northern Continent. Goods from across both continents come ashore here, and so do things that pay to slip past the customs men — sealed curios, smuggled Beyonder materials, and stranger cargo still. The docklands are loud, dangerous, and a law unto themselves after dark, worked by sailors, stevedores, and the desperate, where a knife in the fog settles more disputes than any constable. Because maritime and weather-borne supernatural incidents fall to the Church of the Lord of Storms, its Mandated Punishers keep their closest watch over the harbour, the river-mouth, and the sailors' quarter — for a returning ship may carry home far more than spice and tea.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["landmark", "harbour", "docks", "mandated-punishers", "setting"],
    tokenCount: 215,
    narratorOnly: false,
  },
  {
    slug: "backlund-underground-ruins",
    title: "Backlund — The Underground & the Ancient Ruins",
    category: "location",
    content: `Beneath Backlund lies another, older city. The capital's sewers are the grandest in the kingdom, a brick labyrinth large enough to lose an army in, and below even them run the buried strata of everything Backlund has ever been: the city was the seat of the Tudor-Trunsoest United Empire in the Fourth Epoch, and the foundations, vaults, and tunnels of that vanished age still honeycomb the ground. Mudlarks and tunnel-folk work the upper drains; smugglers move goods through the lower ones; and now and then a digging crew or a collapsed cellar breaks through onto something far older and far worse — a sealed chamber, a ruin that should have stayed buried, a relic of the Empire that fell. The Churches treat the underground as permanently suspect, for it is exactly the kind of place where a cult can work unseen and an ancient horror can be woken by the careless or the curious.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["landmark", "underground", "ruins", "fourth-epoch", "setting"],
    tokenCount: 220,
    narratorOnly: false,
  },
  {
    slug: "backlund-financial-district",
    title: "Backlund — Hillston Borough & the Stock Exchange",
    category: "location",
    content: `Hillston Borough is the financial and business heart of the Loen Kingdom, where the institutions that move the kingdom's money cluster on the refined bank of the Tussock: the great banks, the counting-houses, the insurance halls, and above all the Backlund Stock Exchange, where fortunes are made and unmade between the opening and closing bells. The capital styles itself the place where anything can be had for the right price — and here is where that price is set. The district runs on credit, rumour, and nerve; a whisper can crash a share or float a swindle, and the line between respectable finance and outright fraud is thin and often crossed. For the Beyonder world this matters more than it seems: vast sums move quietly here, collectors and secret societies fund themselves through shell ventures and front companies, and more than one financial panic in the capital's history has had a supernatural hand behind it. Money is its own kind of power in Backlund, and the people who command it are always worth watching.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["district", "hillston", "finance", "stock-exchange", "setting"],
    tokenCount: 225,
    narratorOnly: false,
  },
  {
    slug: "backlund-great-smog",
    title: "Backlund — The Great Smog",
    category: "event",
    content: `The Great Smog of Backlund is remembered by the public as the deadliest disaster in the capital's modern history: a monstrous, unnatural fog settled over the city in the depths of winter and would not lift, choking tens of thousands to death within days, with plague and ruin claiming tens of thousands more in the aftermath. The official account blamed coal-smoke, foul weather, and a disgraced member of the royal family. The truth, known only to a few, is far worse: the smog was deliberately raised as the engine of a forbidden apotheosis ritual — the work of a Sequence-0 Demoness remembered as Lady Despair, in concert with conspirators reaching into the royal house itself and the fanatics of the Aurora Order, who meant to ride the mass death to godhood. The plot was stopped and buried, the true perpetrators struck from the record, and Backlund went on mourning a tragedy it never understood. To a Beyonder, the Great Smog stands as a warning of what the capital's hidden powers will spend to ascend.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [5],
    tags: ["backlund", "great-smog", "event", "aurora-order", "demoness", "history"],
    tokenCount: 220,
    narratorOnly: true,
  },
  {
    slug: "backlund-orthodox-churches",
    title: "Backlund — The Orthodox Churches in the Capital",
    category: "organization",
    content: `Because Backlund is the capital and the most populous city of the Loen Kingdom, the orthodox Churches maintain their grandest cathedrals and their heaviest Beyonder presence here, far exceeding anything in a provincial town. The Church of the Evernight Goddess, the Church of the Lord of Storms, and the Church of the God of Steam and Machinery all hold formal authority in the kingdom, and their Beyonder arms — the Nighthawks, the Mandated Punishers, and the Machinery Hivemind — operate across the city under their respective jurisdictions. Since many devout workers cannot rest on Sundays and labour through the day, the cathedrals here keep their doors open until the early hours, letting believers come to pray and repent through the night. Beyond the orthodox Churches, the capital's size shelters a dense undergrowth of the unaffiliated and the heretical: independent Beyonders, collectors, smuggling rings dealing in sealed curios, and on occasion full cults whose schemes have more than once threatened the city itself. Backlund is where the Beyonder world's stakes are highest and its secrecy most fiercely guarded.`,
    epoch: 5,
    city: "backlund",
    npcs: [],
    sequences: [],
    tags: ["organization", "churches", "nighthawks", "mandated-punishers", "setting"],
    tokenCount: 230,
    narratorOnly: true,
  },
];
