import type { LoreEntry } from "./types";

export const BAYAM_LORE: LoreEntry[] = [
  {
    slug: "bayam-city-overview",
    title: "Bayam — Overview",
    category: "location",
    content: `Bayam is the capital of the Rorsted Archipelago, a port city built on Blue Mountain Island in the central Sonia Sea and nicknamed the "City of Generosity." The island it occupies is largely forested and richly endowed — gold, silver, copper, coal, and iron in its hills, and an abundance of fruit from its fertile land — so its first colonists named it for the plenty they found, a promised land said to flow with milk and honey. Bayam was for less than fifty years a pivotal colony of the Loen Kingdom in its Sonia Sea holdings, and the city still bears that history: many of its streets are named after cities of the Loen homeland. The air is salt and spice; the harbour is crowded with merchantmen, adventurers, informants, and pirates; and the whole archipelago trades on its exotic spices and its notorious pleasure-houses. By night a strict curfew falls over the city, and the cemeteries do not open until dawn. Beneath the colonial trade and the cosmopolitan bustle runs a deep current of island superstition that the foreign rulers have never fully suppressed.`,
    epoch: 5,
    city: "bayam",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "rorsted-archipelago", "colony", "fifth-epoch"],
    tokenCount: 235,
  },
  {
    slug: "bayam-harbour-district",
    title: "Bayam — The Harbour & Adventurers' Quarter",
    category: "location",
    content: `Bayam's life turns on its harbour and the warren of streets behind it where adventurers, sailors, informants, and pirates gather. The Swordfish Bar is the accepted meeting-place for adventurers, its blackboards of posted requests propped on wooden shelves along the wall; the Amyris Leaf Bar is famous as a Beyonder gathering spot where pirates and intelligence-brokers trade in rumour; and the rougher Seaweed Bar is where gangs and infamous pirates do their darker business through secret channels. Inns line the trade streets — the luxurious Wind of Azure Inn on Acid Lemon Street, the Teana Inn, and others — catering to travellers from across the seas. The local press, the Sonia Morning Post and the News Report, carry the announcements that send the whole quarter buzzing. Foreign powers keep embassies here — Intis, Feysac, and Feynapotter all maintain missions — so the harbour district is at once a marketplace, a rumour-mill, and a quiet battleground of competing interests, where a careful listener can buy almost any secret for the right price.`,
    epoch: 5,
    city: "bayam",
    npcs: [],
    sequences: [],
    tags: ["district", "harbour", "adventurers", "setting"],
    tokenCount: 225,
  },
  {
    slug: "bayam-cathedral-of-waves",
    title: "Bayam — The Cathedral of Waves",
    category: "location",
    content: `The Cathedral of Waves is the chief church of the Church of the Lord of Storms in the Rorsted Archipelago, and for years it was the largest cathedral in Bayam — the visible seat of orthodox authority over the sea-faring colony. The Church of the Lord of Storms is the true ruling power of the Beyonder world in the archipelago, charged with maritime and storm-related supernatural affairs across the Sonia Sea, and the Cathedral of Waves is the centre from which its high-ranking deacon — a member of the Council of Cardinals permanently stationed here — administers this key diocese. The cathedral stands above a city of foreigners and natives uneasily mingled, presiding over a colony where the Church has long waged a quiet war against the outlawed worship of the native sea-deity. Its services, its clergy, and its authority give Bayam an orthodox face; but the cathedral's dominance has been challenged, and the religious landscape of the City of Generosity has proven far less settled than the Church's grand stonework would suggest.`,
    epoch: 5,
    city: "bayam",
    npcs: [],
    sequences: [],
    tags: ["cathedral", "lord-of-storms", "religion", "setting"],
    tokenCount: 215,
    narratorOnly: true,
  },
  {
    slug: "bayam-streets-cemeteries",
    title: "Bayam — Streets, Markets & Cemeteries",
    category: "location",
    content: `Bayam wears its colonial history in its very geography. Its streets carry the names of Loen cities, a constant reminder of the kingdom that ruled here; Enmat Street, named for Enmat Harbour, holds Mabel's Sundry Store among its shopfronts, and Blackhorn Street its rented apartments. The city is sharply divided in death as in life: the natives are buried on the mountainside on the city's outskirts, in ground specially set aside by the Church of Storms and the governor-general's office, while foreigners who have settled here — merchants, adventurers, and migrants from Loen, Intis, Feysac, and Feynapotter — lie on a flat plain across the way, backed by forest. The Red Theatre, the most famous pleasure-house in the surrounding seas, anchors the city's other great trade alongside the spices. Under a nightly curfew the streets empty after dark and the graveyards stay shut until dawn — a discipline that speaks to how much the colonial rulers fear what moves in Bayam by night.`,
    epoch: 5,
    city: "bayam",
    npcs: [],
    sequences: [],
    tags: ["district", "streets", "cemeteries", "colony", "setting"],
    tokenCount: 220,
  },
  {
    slug: "bayam-sea-god-kalvetua",
    title: "Bayam — The Sea God Kalvetua & Native Belief",
    category: "metaphysics",
    content: `Before the Loen Kingdom completed its colonisation of the Rorsted Archipelago, the natives of Bayam, Blue Mountain Island, and the surrounding seas worshipped the Sea God Kalvetua — an unimaginably huge blue sea serpent, its scales covered in symbols, believed to guard the islands from earthquakes and tsunamis. Kalvetua is no mere legend: it is a genuine Beyonder of the Tyrant Pathway that took elements of an ancient power and styled itself a god, able to answer its believers' prayers across the archipelago and to enchant their charms and tokens — though such blessings fade to nothing within a few months. The Church of the Lord of Storms has outlawed this worship and hunts its heretics, capturing devotees every month or two; rumour holds that powerful cardinals defeated and drove the serpent into hiding more than a century ago. Yet belief endures stubbornly in Bayam and across the islands, bound up with native resentment of colonial rule. The faith of the Sea God is the deepest of the island superstitions — a drowned, hunted, but living religion beneath the colony's orthodox surface.`,
    epoch: 5,
    city: "bayam",
    npcs: [],
    sequences: [],
    tags: ["sea-god", "kalvetua", "native-belief", "tyrant-pathway", "setting"],
    tokenCount: 240,
    narratorOnly: true,
  },
];
