import type { LoreEntry } from "./types";

export const FIFTH_EPOCH_LORE: LoreEntry[] = [
  {
    slug: "fifth-epoch-overview",
    title: "Fifth Epoch — The Iron Age",
    category: "metaphysics",
    content: `The Fifth Epoch, known as the Iron Age, is the current historical era. It began after the conclusion of the Fourth Epoch's devastating divine wars and is defined by three characteristics: the Industrial Revolution, the concealment of mysticism from the general public, and the dominance of the Seven Orthodox Churches. Steam power drives factories and transportation, gas lamps illuminate city streets, and mechanical innovation reshapes society. The general populace is unaware of the Beyonder world — supernatural incidents are suppressed by the orthodox churches and their Beyonder organizations. This concealment is deliberate policy: the churches learned from the Fourth Epoch that open divine intervention causes catastrophic collateral damage. The major nations of the Northern Continent — the Loen Kingdom, the Intis Republic, the Feysac Empire, and the Feynapotter Kingdom — maintain an uneasy balance of power, with each nation aligned with specific orthodox churches. The Southern Continent remains largely colonized by Northern powers.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["epoch", "history", "industrial-revolution", "concealment", "world-setting"],
    tokenCount: 210,
  },
  {
    slug: "fifth-epoch-political-landscape",
    title: "Fifth Epoch — Political Landscape",
    category: "metaphysics",
    content: `The Northern Continent's four major nations each maintain distinct political systems and church alignments. The Loen Kingdom, modeled on Victorian Britain, is a constitutional monarchy with a strong parliament and aristocratic class. Its primary churches are the Church of the Evernight Goddess and the Church of the Lord of Storms, with the Church of the God of Steam and Machinery also holding significant influence due to industrialization. The Intis Republic, inspired by industrial France, is dominated by the Church of the Eternal Blazing Sun and maintains republican governance. The Feysac Empire, resembling Imperial Russia, is an autocracy closely tied to the Church of the God of Combat. The Feynapotter Kingdom serves as a fourth balancing power. Colonial competition over the Southern Continent drives international tension. Beneath the surface, the royal families of each nation harbor Beyonder secrets — the Loen royal family in particular pursues the Black Emperor pathway toward apotheosis, a plot that becomes central to the mid-narrative.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["politics", "nations", "loen-kingdom", "intis-republic", "feysac-empire"],
    tokenCount: 210,
  },
  {
    slug: "fifth-epoch-technology",
    title: "Fifth Epoch — Technology and Industry",
    category: "metaphysics",
    content: `Fifth Epoch technology mirrors the Victorian-to-Edwardian transition, driven by steam power and early electrical experimentation. Key technologies include steam engines powering factories and locomotives, gas lighting in urban areas, telegraph communication networks, mechanical printing presses enabling mass media, and early experiments with internal combustion and electricity. The Church of the God of Steam and Machinery actively promotes technological innovation, viewing it as an expression of their deity's domain. Firearms are widespread: revolvers and rifles are standard for law enforcement and military, and even Beyonders at lower sequences are vulnerable to gunfire. This creates a distinctive power dynamic where mundane technology remains dangerous to supernatural beings until they reach mid-sequence. Transportation relies on horse-drawn carriages in cities, steam trains between cities, and steam-powered ships for maritime travel. Medicine is advancing but still limited — diseases like tuberculosis and cholera remain threats, though Beyonder healing can cure what conventional medicine cannot.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["technology", "steam-power", "firearms", "industry", "world-setting"],
    tokenCount: 210,
  },
  {
    slug: "fifth-epoch-social-norms",
    title: "Fifth Epoch — Social Norms and Daily Life",
    category: "metaphysics",
    content: `Fifth Epoch society follows Victorian social conventions with rigid class stratification. The aristocracy and wealthy merchants occupy the upper echelons, followed by a growing middle class of professionals, clerks, and skilled tradesmen, with factory workers and laborers forming the working class. Social etiquette demands formal dress, proper modes of address, and strict gender role expectations — though women have begun entering the workforce in limited capacities. Religion plays a central social role: church attendance is expected, the seven orthodox faiths provide community structure, and blasphemy carries social and sometimes legal consequences. Newspapers are the primary information medium, and literacy rates are rising due to public education initiatives. Entertainment includes theater, music halls, horse racing, social clubs, and the emergence of organized sports. Poverty and industrial exploitation exist alongside displays of wealth, creating social tension that mirrors real Victorian inequalities. The supernatural world operates entirely within these social structures — Beyonders maintain cover identities appropriate to their class.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["society", "class-system", "victorian", "daily-life", "world-setting"],
    tokenCount: 210,
  },
  {
    slug: "fifth-epoch-hidden-mysticism",
    title: "Fifth Epoch — The Hidden World of Beyonders",
    category: "metaphysics",
    content: `Beneath the mundane surface of Fifth Epoch society, an entire world of supernatural power operates in secrecy. The Seven Orthodox Churches maintain divisions of Official Beyonders who investigate supernatural incidents, contain dangerous artifacts, and eliminate threats. These divisions — the Nighthawks, Mandated Punishers, Machinery Hivemind, Inquisition, and others — function as secret supernatural police forces. Beyond the churches, secret organizations like the Psychology Alchemists, the Aurora Order, and the Rose School of Thought pursue their own agendas. The black market for Beyonder materials thrives in the shadows: potion formulas, mystical ingredients, and Beyonder characteristics are traded in underground exchanges. Ordinary citizens occasionally encounter the supernatural — unexplained deaths, haunted locations, mysterious disappearances — but the churches suppress evidence and maintain the narrative that such things are superstition. This concealment serves a practical purpose: widespread knowledge of the Beyonder world would cause mass panic and make it easier for malevolent entities to recruit followers. The tension between the hidden and mundane worlds defines the setting's atmosphere.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["beyonder-world", "secrecy", "churches", "black-market", "world-setting"],
    tokenCount: 225,
  },
];
