import type { LoreEntry } from "./types";

export const NPC_LORE: LoreEntry[] = [
  {
    slug: "npc-dunn-smith",
    title: "Dunn Smith — Tingen Nighthawks Captain",
    category: "npc",
    content: `Captain Dunn Smith is the leader of the Tingen Nighthawks team. A Sequence 7 Nightmare on the Darkness (Sleepless) pathway, Dunn is a tall, handsome man in his late thirties with a perpetually drowsy demeanor — he is often found dozing at his desk, a trait both endearing and deceptive, as his apparent laziness conceals sharp instincts and significant combat ability. Dunn's leadership style is understated: he gives his team members considerable autonomy, trusts their judgment, and intervenes only when situations escalate beyond their capability. He is deeply protective of his team and takes losses personally. As a Nightmare, Dunn possesses abilities related to dreams and sleep manipulation — he can enter others' dreams, induce sleep, and create nightmarish illusions. His combat effectiveness is considerable for Tingen-level threats. Dunn maintains a calm, fatherly relationship with his subordinates, particularly Klein, whom he mentors in the early days. His character arc in the narrative is tragic: he becomes entangled in the Ince Zangwill conspiracy and ultimately cannot protect his team from the dangers that converge on Tingen.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Dunn Smith"],
    sequences: [7],
    tags: ["nighthawks", "captain", "mentor", "darkness-pathway"],
    tokenCount: 245,
  },
  {
    slug: "npc-leonard-mitchell",
    title: "Leonard Mitchell — Nighthawk and Poet",
    category: "npc",
    content: `Leonard Mitchell is a young Nighthawk serving on the Tingen team and one of Klein Moretti's earliest companions. A Sequence 9 Sleepless on the Darkness pathway (advancing to Sequence 8 during the Tingen arc), Leonard is notable for his poetic sensibility, good looks, and a habit of composing verses in his head during tense situations. He is observant, empathetic, and genuinely committed to protecting civilians from supernatural threats. Leonard harbors a significant secret: he is the host of Pallez Zoroast, a powerful Beyonder of the Error pathway, who resides within Leonard's body as a symbiotic entity. Pallez provides Leonard with occasional guidance and enhanced abilities but also represents a constant danger — the Angel's own agenda may not always align with Leonard's. In the Tarot Club, Leonard later becomes "The Star." His friendship with Klein is one of the narrative's most enduring relationships, and he plays a critical role in later volumes. In Tingen, Leonard serves as Klein's partner on investigations and provides the reader's window into the Nighthawks' daily operations.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Leonard Mitchell", "Pallez Zoroast"],
    sequences: [9, 8],
    tags: ["nighthawks", "tarot-club", "the-star", "darkness-pathway"],
    tokenCount: 250,
  },
  {
    slug: "npc-old-neil",
    title: "Old Neil — Nighthawk Artificer",
    category: "npc",
    content: `Old Neil is the Tingen Nighthawks' resident artificer and historian, an elderly man who serves as the team's expert on mystical artifacts, ritual materials, and Beyonder history. He maintains the team's equipment, identifies recovered artifacts, and provides technical support for operations. Old Neil is warm, grandfatherly, and generous with his knowledge — he teaches Klein about ritual practices, artifact handling, and the practical aspects of the Beyonder world that formal training doesn't cover. He follows the Hermit pathway at a low sequence level (a Sequence 9 Mystery Pryer), giving him analytical and knowledge-gathering abilities. Old Neil's fate becomes one of the Tingen arc's most poignant tragedies: he is manipulated into attempting an advancement ritual that goes wrong, leading to his loss of control. His transformation into an uncontrolled aberration forces the Nighthawks team to confront and put down one of their own — an event that deeply affects Klein and demonstrates the ever-present danger of Beyonder advancement. Old Neil's death serves as a formative trauma that shapes Klein's cautious approach to advancement throughout the narrative.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Old Neil"],
    sequences: [9, 8],
    tags: ["nighthawks", "artificer", "mentor", "tragedy", "loss-of-control"],
    tokenCount: 240,
  },
  {
    slug: "npc-daly-simone",
    title: "Daly Simone — Spirit Medium",
    category: "npc",
    content: `Daly Simone is a Sequence 7 Spirit Medium on the Death pathway, serving with the Tingen Nighthawks on secondment. She is one of the team's most capable combatants, specializing in communicating with the dead, banishing restless spirits, and navigating the boundary between the living and the dead. Daly is a composed, professional woman who approaches her work with clinical detachment — necessary given the disturbing nature of her abilities, which include channeling dead spirits through her own body and entering the death realm. She serves as a senior field operative and is often paired with less experienced members for dangerous assignments. Daly's expertise in death-related phenomena makes her invaluable when the team encounters undead threats, haunted locations, or cases requiring forensic communication with murder victims. Her presence on the Tingen team illustrates how the orthodox churches share personnel across pathway specializations when local expertise is needed. Daly maintains professional relationships with her colleagues but keeps emotional distance — a defense mechanism common among Spirit Mediums who regularly expose themselves to the grief and trauma of the dead.`,
    epoch: 5,
    city: "tingen",
    pathway: "death",
    npcs: ["Daly Simone"],
    sequences: [7],
    tags: ["nighthawks", "death-pathway", "spirit-medium", "senior-operative"],
    tokenCount: 240,
  },
  {
    slug: "npc-azik-eggers",
    title: "Azik Eggers — The Undying Teacher",
    category: "npc",
    content: `Azik Eggers is a mysterious figure who serves as a history lecturer in Tingen, known to Klein Moretti from his university days. Behind his academic facade, Azik is an extraordinarily powerful Beyonder of the Death pathway — a being who has lived for centuries, possibly since the Second or Third Epoch. He possesses the title and power of a "Death Consul" at the Angel level (approximately Sequence 2). Azik's memory is fragmented due to the immense age of his existence and the accumulation of Death pathway characteristics; he periodically forgets his past and assumes new identities. In Tingen, he lives as a mild-mannered professor who has forgotten much of his true nature. Klein's interaction with Azik predates his transmigration — the original Klein knew Azik as a kind teacher. After Klein's transmigration, Azik becomes an unwitting ally, occasionally providing crucial assistance in life-threatening situations when fragments of his true power surface. Azik's copper whistle, which Klein inherits, becomes one of Klein's most important protective artifacts, capable of summoning death-related powers far beyond Klein's own sequence level.`,
    epoch: 5,
    city: "tingen",
    pathway: "death",
    npcs: ["Azik Eggers"],
    sequences: [2],
    tags: ["death-pathway", "angel", "ancient-being", "university", "mentor"],
    tokenCount: 255,
  },
  {
    slug: "npc-klein-moretti",
    title: "Klein Moretti — The Transmigrated Protagonist",
    category: "npc",
    content: `Klein Moretti is the protagonist of Lord of the Mysteries. Originally Zhou Mingrui, a young Chinese man from modern Earth, he awakens in the body of Klein Moretti, a Tingen history graduate who recently committed suicide. Klein must navigate his new identity while hiding the fact that he is not the original Klein. He quickly discovers the Beyonder world when he accidentally activates a ritual that connects him to Sefirah Castle — a mysterious extradimensional space that becomes his greatest asset. Klein joins the Nighthawks to investigate the circumstances of the original Klein's death and to gain access to Beyonder resources. He begins the Fool pathway as a Sequence 9 Seer, using divination and spiritual perception as his primary tools. Klein is defined by his intelligence, caution, and emotional depth — he genuinely cares about the people around him and struggles with the moral compromises the Beyonder world demands. His modern knowledge gives him analytical advantages, and his discovery of the Acting Method allows him to advance more safely than most Beyonders. In the Tarot Club, he assumes the persona of "The Fool," masquerading as an ancient deity.`,
    epoch: 5,
    city: "tingen",
    pathway: "fool",
    npcs: ["Klein Moretti"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "protagonist",
      "transmigrator",
      "tarot-club",
      "the-fool",
      "seer",
      "fool-pathway",
    ],
    tokenCount: 260,
  },
  {
    slug: "npc-melissa-moretti",
    title: "Melissa Moretti — Klein's Sister",
    category: "npc",
    content: `Melissa Moretti is Klein's younger sister in his adopted identity. She is a hardworking young woman employed at a textile factory, contributing to the household finances after their parents' death and Klein's recent graduation. Melissa is practical, caring, and slightly stern — she manages the household budget, prepares meals, and worries constantly about Klein's erratic behavior after his "illness" (the transmigration). She represents Klein's primary emotional anchor to his new life and identity: protecting Melissa and ensuring her wellbeing becomes one of his core motivations. Melissa is unaware of the Beyonder world and Klein's supernatural activities. Their modest apartment on Iron Cross Street is the domestic center of Klein's Tingen life. Melissa's character embodies the ordinary people whom the Beyonder organizations strive to protect — she lives in a world where supernatural horrors lurk just beyond perception, shielded only by the efforts of people like her brother. Klein's determination to keep her safe and ignorant of the dangers he faces drives many of his decisions. Benson Moretti, their older brother, works in another city and sends money home occasionally.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Melissa Moretti", "Benson Moretti"],
    sequences: [],
    tags: ["family", "civilian", "anchor", "iron-cross-street"],
    tokenCount: 235,
  },
  {
    slug: "npc-ince-zangwill",
    title: "Ince Zangwill — The Fallen Nighthawk",
    category: "npc",
    content: `Ince Zangwill is a former high-ranking Nighthawk who serves as the primary antagonist of the Tingen arc. A Beyonder who began on the Death pathway as a Sequence 5 Gatekeeper and later crossed into the Darkness pathway (a Sequence 4 Nightwatcher), Zangwill possesses the "0-08" card — one of the most dangerous sealed artifacts in the Church of the Evernight Goddess's possession. This living, malevolent playing card can manipulate fate and probability, making Zangwill extraordinarily dangerous. Zangwill betrayed the Nighthawks by stealing the card and fleeing, becoming a fugitive pursued by the church. His return to Tingen drives the climactic events of Volume 1: he orchestrates a series of incidents that culminate in a deadly confrontation where Klein Moretti is killed. Zangwill's motivations are complex — the 0-08 card's corrupting influence has warped his mind, and his actions serve both his own ambitions and the card's mysterious agenda. He represents the danger of powerful artifacts corrupting their wielders and the threat that rogue Beyonders pose to both the mundane and supernatural worlds. Klein's eventual revenge against Zangwill becomes a driving motivation that spans multiple volumes.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Ince Zangwill"],
    sequences: [5],
    tags: ["antagonist", "nighthawks", "0-08-card", "darkness-pathway", "betrayal"],
    tokenCount: 245,
  },
  // ── Forsaken Land of the Gods — City of Silver characters (issue #132) ──
  // City-keyed so they ride the same location-gating as the continent's lore;
  // each carries family/friends/affiliation relationship data for grounding.
  {
    slug: "npc-derrick-berg",
    title: "Derrick Berg — The Sun of the Tarot Club",
    category: "npc",
    content: `Derrick Berg is a young man born and raised in the City of Silver, one of the surviving cities of the Forsaken Land of the Gods, and one of the rare souls to leave it by the Dream-World passage. A devout, earnest, and physically powerful Beyonder of the Sun pathway, he was a defender of the City before the wider world opened to him. He becomes a member of the Tarot Club under the code name "The Sun," where his sincerity and raw strength make him both a reliable ally and, at times, an unwitting source of comedy among subtler members. His defining ties are to his home: his family and the brotherhood of the City of Silver's defenders, the faith of the abandoned that he carries with unshaken conviction, and — through the Tarot Club — a growing bond with The Fool (Klein Moretti) and the other members "above the gray fog." Derrick's arc is one of a sheltered believer discovering how vast and dangerous the real world is, without ever losing the openhearted decency the City raised in him.`,
    epoch: 5,
    city: "silver",
    // Deliberately NOT pathway-keyed (issue #132 leak control): selectCuratedLore
    // indexes pathway lore location-independently, so a `pathway` field here would
    // inject this City-of-Silver entry into any mainland Sun character's prompt.
    // The prose still names his Sun pathway; the entry stays city-gated to "silver".
    npcs: ["Derrick Berg"],
    sequences: [],
    tags: ["forsaken-land", "city-of-silver", "tarot-club", "the-sun", "sun-pathway"],
    tokenCount: 220,
    narratorOnly: false,
  },
  {
    slug: "npc-giant-king-aurmir",
    title: "Giant King Aurmir — The Lord of the Ruined Court",
    category: "npc",
    content: `Giant King Aurmir is the legendary figure for whom Giant King's Court — the titan-scaled ruin east of the City of Silver — is named, remembered in the City's lore as a lord of the elder Giants from the ages before the continent fell. To the abandoned faithful he is half history and half myth: a being of the old inhuman powers whose seat outlived him, its broken thrones and colossal halls now the holiest and most feared site on the Forsaken Land. The City keeps his name and his rites because his Court is no mere ruin — its shadow in the Dream World is the single doorway in and out of the sealed continent — so the keepers who guard that secret guard his memory with it. Whether anything of Aurmir himself yet lingers about the Court is a question the City's deepest order does not answer for outsiders.`,
    epoch: 5,
    city: "giant",
    npcs: ["Giant King Aurmir"],
    sequences: [4],
    tags: ["forsaken-land", "giant-kings-court", "giant", "legend"],
    tokenCount: 195,
    narratorOnly: true,
  },
  // ── Backlund deep-dive (world build-out 4, issue #133) ──
  // City-keyed to "backlund" so the narrator carries them for a character in the
  // capital. Deliberately NOT pathway-keyed (the issue #132 leak rule): a
  // `pathway` field would inject a Backlund NPC into any same-pathway character's
  // prompt regardless of where they are. Pathways are named only in prose.
  // All canon (names, families, pathways, identities) verified against corpus/wiki
  // (see CLAUDE.md "Canon & Source Material") — NOT memory.
  {
    slug: "npc-audrey-hall",
    title: "Audrey Hall — Lady of Empress Borough, the Tarot Club's Justice",
    category: "npc",
    content: `Audrey Hall is the youngest child and only daughter of the aristocratic Hall family of Backlund's Empress Borough — her father an Earl who sits in the Cabinet and ranks among Loen's foremost bankers, her mother Caitlyn, and her two elder brothers Hibbert and Alfred. A poised and famously charming young noblewoman, called "Backlund's most dazzling gem," she moves easily through the salons and balls of the capital's high society. Behind that public face she is a Beyonder of the Visionary (Spectator) pathway, gifted in reading and gently swaying the minds and hearts of others, and — known to no one in her ordinary world — a member of the secret Tarot Club, where she takes the name "Justice." Idealistic, quick-witted, and braver than her sheltered upbringing would suggest, she is determined to use her gifts for genuine good. Her devoted golden retriever Susie — who drank one of her early potions and is no ordinary dog — is rarely far from her side. She is a living bridge between Backlund's gilded surface and its hidden Beyonder depths.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Audrey Hall", "Hibbert Hall", "Alfred Hall", "Caitlyn Hall"],
    sequences: [],
    tags: ["backlund", "hall-family", "tarot-club", "the-justice", "visionary-pathway"],
    tokenCount: 250,
  },
  {
    slug: "npc-hall-family",
    title: "The Hall Family — A Noble House of Empress Borough",
    category: "npc",
    content: `The Hall family is one of the most prominent aristocratic houses of Backlund, seated in the Earl Hall Villa in Empress Borough on the refined bank of the Tussock. The Earl himself is a power in the capital — a member of the Cabinet and one of the foremost bankers of the Loen Kingdom — and with his wife Caitlyn he has raised three children: the eldest son and heir Hibbert, the second son Alfred, and the youngest, his only daughter Audrey, the family's brightest light in society. Like the great families around them the Halls live by the rituals of their class: the season's balls, advantageous marriages, parliamentary connection, and the careful management of reputation and fortune. On the surface they are exactly what they appear to be — old money and high office in a city built on both. What the Earl does not know is that his daughter walks a hidden world far stranger and more dangerous than any drawing-room intrigue.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Caitlyn Hall", "Hibbert Hall", "Alfred Hall", "Audrey Hall"],
    sequences: [],
    tags: ["backlund", "hall-family", "nobility", "empress-borough"],
    tokenCount: 220,
  },
  {
    slug: "npc-klein-backlund-identities",
    title: "Sherlock Moriarty & Dwayne Dantès — Backlund Cover Identities",
    category: "npc",
    content: `In Backlund, one extraordinarily capable Beyonder operates behind two carefully built faces. SHERLOCK MORIARTY is a private detective working out of an office on Minsk Street in Cherwood Borough — sharp, theatrical, and uncannily good at the cases the police cannot close; he moves through the capital's underworld and its tragedies, the smog-choked economic crisis among them, gathering what no badge ever could. DWAYNE DANTÈS is the other face: a mysterious, fabulously wealthy tycoon and philanthropist who buys his way into Empress Borough high society, founds a charitable bursary, donates to the Church of the Evernight Goddess, and trades quietly in influence and arms. The two never appear to be the same man, and neither appears to be what he truly is — a powerful Beyonder, the Tarot Club's masked "Fool," using Backlund as his stage. To the city they are a clever detective and a generous magnate; to those who could see clearly, they are two masks worn by a single mind.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Sherlock Moriarty", "Dwayne Dantès", "Klein Moretti"],
    sequences: [],
    tags: [
      "backlund",
      "klein-identities",
      "sherlock-moriarty",
      "dwayne-dantes",
      "tarot-club",
    ],
    tokenCount: 230,
    narratorOnly: true,
  },
  {
    slug: "npc-bravehearts-temperance",
    title: "Sharron & Maric — the Bravehearts Bar Exiles",
    category: "npc",
    content: `Sharron and Maric are two Beyonders of the Chained pathway who fled the Rose School of Thought when its Temperance faction was shattered, and who found refuge in Backlund under the protection of the Tarot Club's "The Fool." They keep to the Bravehearts Bar near the Backlund Bridge and to lodgings in Hillston Borough — Sharron a formidable, watchful bodyguard (hired more than once by their mysterious patron) who carries the Tarot name "Temperance," and Maric her steadfast companion, the "Knight of Swords." Survivors of an order that turned to devouring desire, they hold instead to the discipline of restraint the Rose School abandoned. To ordinary Backlunders they are simply foreign regulars at a riverside bar; in truth they are exiles of a heresy, sheltering with the very network that opposes the Mother Tree of Desire, and fiercely loyal to the patron who took them in when their own kind hunted them.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Sharron", "Maric", "Reinette Tinekerr"],
    sequences: [],
    tags: [
      "backlund",
      "rose-school-of-thought",
      "temperance",
      "tarot-club",
      "chained-pathway",
    ],
    tokenCount: 215,
    narratorOnly: true,
  },
  // ── Moon City — the eastern fog-watch (issue #133). City-keyed "moon" (a City-
  // of-Silver native never receives this; the cities were mutually unaware). NOT
  // pathway-keyed (the #132 leak rule); pathway named only in prose. ──
  {
    slug: "npc-nim",
    title: "Nim — High Priest of Moon City",
    category: "npc",
    content: `Nim is one of the three High Priests who hold Moon City together against the dead land — an old man wrapped in dark beast-hide, his grey hair unkempt, his face seamed with cracks that are not only age. A demigod-tier Beyonder of the Darkness path (a Sequence 4 Nightwatcher), he is the closest thing the isolated city has to a guardian and a king: he keeps the old rites, rations the city's strength, and carries the weight of its ancient duty to watch the gray fog. Hard, patient, and unsentimental in the way only a man who has buried generations can be, Nim is nonetheless not cruel — every harsh choice he makes is bent toward one end, that Moon City last another year. His ties are to his fellow High Priests, to the watchful people in his charge, and to a duty laid on the city by a god who no longer answers.`,
    epoch: 5,
    city: "moon",
    npcs: ["Nim"],
    sequences: [4],
    tags: ["forsaken-land", "moon-city", "high-priest", "darkness-pathway"],
    tokenCount: 205,
    narratorOnly: true,
  },
];
