import type { LoreEntry } from "./types";

export const NPC_LORE: LoreEntry[] = [
  {
    slug: "npc-dunn-smith",
    title: "Dunn Smith — Tingen Nighthawks Captain",
    category: "npc",
    content: `Captain Dunn Smith is the leader of the Tingen Nighthawks team. A Sequence 7 Nightmare on the Darkness (Sleepless) pathway, Dunn is a tall, handsome man in his late thirties with a perpetually drowsy demeanor — he is often found dozing at his desk, a trait both endearing and deceptive, as his apparent laziness conceals sharp instincts and significant combat ability. Dunn's leadership style is understated: he gives his team members considerable autonomy, trusts their judgment, and intervenes only when situations escalate beyond their capability. He is deeply protective of his team and takes losses personally. As a Nightmare, Dunn possesses abilities related to dreams and sleep manipulation — he can enter others' dreams, induce sleep, and create nightmarish illusions. His combat effectiveness is considerable for Tingen-level threats. Dunn maintains a calm, fatherly relationship with his subordinates, particularly Klein, whom he mentors in the early days. His character arc in the narrative is tragic: he becomes entangled in the Ince Zangwill conspiracy and ultimately cannot protect his team from the dangers that converge on Tingen.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Dunn Smith"],
    sequences: [7],
    tags: ["nighthawks", "captain", "mentor", "darkness-pathway"],
    tokenCount: 245,
  },
  {
    slug: "npc-leonard-mitchell",
    title: "Leonard Mitchell — Nighthawk and Poet",
    category: "npc",
    content: `Leonard Mitchell is a young Nighthawk serving on the Tingen team and one of Klein Moretti's earliest companions. A Sequence 9 Sleepless on the Darkness pathway (advancing to Sequence 8 during the Tingen arc), Leonard is notable for his poetic sensibility, good looks, and a habit of composing verses in his head during tense situations. He is observant, empathetic, and genuinely committed to protecting civilians from supernatural threats. Leonard harbors a significant secret: he is the host of Pallez Zoroast, a powerful Beyonder of the Error pathway, who resides within Leonard's body as a symbiotic entity. Pallez provides Leonard with occasional guidance and enhanced abilities but also represents a constant danger — the Angel's own agenda may not always align with Leonard's. In the Tarot Club, Leonard later becomes "The Star." His friendship with Klein is one of the narrative's most enduring relationships, and he plays a critical role in later volumes. In Tingen, Leonard serves as Klein's partner on investigations and provides the reader's window into the Nighthawks' daily operations.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Leonard Mitchell", "Pallez Zoroast"],
    sequences: [9, 8],
    tags: ["nighthawks", "tarot-club", "the-star", "darkness-pathway"],
    tokenCount: 250,
  },
  {
    slug: "npc-old-neil",
    title: "Old Neil — Nighthawk Artificer",
    category: "npc",
    content: `Old Neil is the Tingen Nighthawks' resident artificer and historian, an elderly man who serves as the team's expert on mystical artifacts, ritual materials, and Beyonder history. He maintains the team's equipment, identifies recovered artifacts, and provides technical support for operations. Old Neil is warm, grandfatherly, and generous with his knowledge — he teaches Klein about ritual practices, artifact handling, and the practical aspects of the Beyonder world that formal training doesn't cover. He follows the Hermit pathway at a low sequence level (a Sequence 9 Mystery Pryer), giving him analytical and knowledge-gathering abilities. Old Neil's fate becomes one of the Tingen arc's most poignant tragedies: he is manipulated into attempting an advancement ritual that goes wrong, leading to his loss of control. His transformation into an uncontrolled aberration forces the Nighthawks team to confront and put down one of their own — an event that deeply affects Klein and demonstrates the ever-present danger of Beyonder advancement. Old Neil's death serves as a formative trauma that shapes Klein's cautious approach to advancement throughout the narrative.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Old Neil"],
    sequences: [9, 8],
    tags: ["nighthawks", "artificer", "mentor", "tragedy", "loss-of-control"],
    tokenCount: 240,
  },
  {
    slug: "npc-daly-simone",
    title: "Daly Simone — Spirit Medium",
    category: "npc",
    content: `Daly Simone is a Sequence 7 Spirit Medium on the Death pathway, serving with the Tingen Nighthawks on secondment. She is one of the team's most capable combatants, specializing in communicating with the dead, banishing restless spirits, and navigating the boundary between the living and the dead. Daly is a composed, professional woman who approaches her work with clinical detachment — necessary given the disturbing nature of her abilities, which include channeling dead spirits through her own body and entering the death realm. She serves as a senior field operative and is often paired with less experienced members for dangerous assignments. Daly's expertise in death-related phenomena makes her invaluable when the team encounters undead threats, haunted locations, or cases requiring forensic communication with murder victims. Her presence on the Tingen team illustrates how the orthodox churches share personnel across pathway specializations when local expertise is needed. Daly maintains professional relationships with her colleagues but keeps emotional distance — a defense mechanism common among Spirit Mediums who regularly expose themselves to the grief and trauma of the dead.`,
    epoch: 5,
    city: "tingen",
    pathway: "death",
    npcs: ["Daly Simone"],
    sequences: [7],
    tags: ["nighthawks", "death-pathway", "spirit-medium", "senior-operative"],
    tokenCount: 240,
  },
  {
    slug: "npc-azik-eggers",
    title: "Azik Eggers — The Undying Teacher",
    category: "npc",
    content: `Azik Eggers is a mysterious figure who serves as a history lecturer in Tingen, known to Klein Moretti from his university days. Behind his academic facade, Azik is an extraordinarily powerful Beyonder of the Death pathway — a being who has lived for centuries, possibly since the Second or Third Epoch. He possesses the title and power of a "Death Consul" at the Angel level (approximately Sequence 2). Azik's memory is fragmented due to the immense age of his existence and the accumulation of Death pathway characteristics; he periodically forgets his past and assumes new identities. In Tingen, he lives as a mild-mannered professor who has forgotten much of his true nature. Klein's interaction with Azik predates his transmigration — the original Klein knew Azik as a kind teacher. After Klein's transmigration, Azik becomes an unwitting ally, occasionally providing crucial assistance in life-threatening situations when fragments of his true power surface. Azik's copper whistle, which Klein inherits, becomes one of Klein's most important protective artifacts, capable of summoning death-related powers far beyond Klein's own sequence level.`,
    epoch: 5,
    city: "tingen",
    pathway: "death",
    npcs: ["Azik Eggers"],
    sequences: [2],
    tags: ["death-pathway", "angel", "ancient-being", "university", "mentor"],
    tokenCount: 255,
  },
  {
    slug: "npc-klein-moretti",
    title: "Klein Moretti — The Transmigrated Protagonist",
    category: "npc",
    content: `Klein Moretti is the protagonist of Lord of the Mysteries. Originally Zhou Mingrui, a young Chinese man from modern Earth, he awakens in the body of Klein Moretti, a Tingen history graduate who recently committed suicide. Klein must navigate his new identity while hiding the fact that he is not the original Klein. He quickly discovers the Beyonder world when he accidentally activates a ritual that connects him to Sefirah Castle — a mysterious extradimensional space that becomes his greatest asset. Klein joins the Nighthawks to investigate the circumstances of the original Klein's death and to gain access to Beyonder resources. He begins the Fool pathway as a Sequence 9 Seer, using divination and spiritual perception as his primary tools. Klein is defined by his intelligence, caution, and emotional depth — he genuinely cares about the people around him and struggles with the moral compromises the Beyonder world demands. His modern knowledge gives him analytical advantages, and his discovery of the Acting Method allows him to advance more safely than most Beyonders. In the Tarot Club, he assumes the persona of "The Fool," masquerading as an ancient deity.`,
    epoch: 5,
    city: "tingen",
    pathway: "fool",
    npcs: ["Klein Moretti"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "protagonist",
      "transmigrator",
      "tarot-club",
      "the-fool",
      "seer",
      "fool-pathway",
    ],
    tokenCount: 260,
  },
  {
    slug: "npc-melissa-moretti",
    title: "Melissa Moretti — Klein's Sister",
    category: "npc",
    content: `Melissa Moretti is Klein's younger sister in his adopted identity. She is a hardworking young woman employed at a textile factory, contributing to the household finances after their parents' death and Klein's recent graduation. Melissa is practical, caring, and slightly stern — she manages the household budget, prepares meals, and worries constantly about Klein's erratic behavior after his "illness" (the transmigration). She represents Klein's primary emotional anchor to his new life and identity: protecting Melissa and ensuring her wellbeing becomes one of his core motivations. Melissa is unaware of the Beyonder world and Klein's supernatural activities. Their modest apartment on Iron Cross Street is the domestic center of Klein's Tingen life. Melissa's character embodies the ordinary people whom the Beyonder organizations strive to protect — she lives in a world where supernatural horrors lurk just beyond perception, shielded only by the efforts of people like her brother. Klein's determination to keep her safe and ignorant of the dangers he faces drives many of his decisions. Benson Moretti, their older brother, works in another city and sends money home occasionally.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Melissa Moretti", "Benson Moretti"],
    sequences: [],
    tags: ["family", "civilian", "anchor", "iron-cross-street"],
    tokenCount: 235,
  },
  {
    slug: "npc-ince-zangwill",
    title: "Ince Zangwill — The Fallen Nighthawk",
    category: "npc",
    content: `Ince Zangwill is a former high-ranking Nighthawk who serves as the primary antagonist of the Tingen arc. A Beyonder who began on the Death pathway as a Sequence 5 Gatekeeper and later crossed into the Darkness pathway (a Sequence 4 Nightwatcher), Zangwill possesses the "0-08" card — one of the most dangerous sealed artifacts in the Church of the Evernight Goddess's possession. This living, malevolent playing card can manipulate fate and probability, making Zangwill extraordinarily dangerous. Zangwill betrayed the Nighthawks by stealing the card and fleeing, becoming a fugitive pursued by the church. His return to Tingen drives the climactic events of Volume 1: he orchestrates a series of incidents that culminate in a deadly confrontation where Klein Moretti is killed. Zangwill's motivations are complex — the 0-08 card's corrupting influence has warped his mind, and his actions serve both his own ambitions and the card's mysterious agenda. He represents the danger of powerful artifacts corrupting their wielders and the threat that rogue Beyonders pose to both the mundane and supernatural worlds. Klein's eventual revenge against Zangwill becomes a driving motivation that spans multiple volumes.`,
    epoch: 5,
    city: "tingen",
    pathway: "darkness",
    npcs: ["Ince Zangwill"],
    sequences: [5],
    tags: ["antagonist", "nighthawks", "0-08-card", "darkness-pathway", "betrayal"],
    tokenCount: 245,
  },
  // ── Forsaken Land of the Gods — City of Silver characters (issue #132) ──
  // City-keyed so they ride the same location-gating as the continent's lore;
  // each carries family/friends/affiliation relationship data for grounding.
  {
    slug: "npc-derrick-berg",
    title: "Derrick Berg — The Sun of the Tarot Club",
    category: "npc",
    content: `Derrick Berg is a young man born and raised in the City of Silver, one of the surviving cities of the Forsaken Land of the Gods, and one of the rare souls to leave it by the Dream-World passage. A devout, earnest, and physically powerful Beyonder of the Sun pathway, he was a defender of the City before the wider world opened to him. He becomes a member of the Tarot Club under the code name "The Sun," where his sincerity and raw strength make him both a reliable ally and, at times, an unwitting source of comedy among subtler members. His defining ties are to his home: his family and the brotherhood of the City of Silver's defenders, the faith of the abandoned that he carries with unshaken conviction, and — through the Tarot Club — a growing bond with The Fool (Klein Moretti) and the other members "above the gray fog." Derrick's arc is one of a sheltered believer discovering how vast and dangerous the real world is, without ever losing the openhearted decency the City raised in him.`,
    epoch: 5,
    city: "silver",
    // Deliberately NOT pathway-keyed (issue #132 leak control): selectCuratedLore
    // indexes pathway lore location-independently, so a `pathway` field here would
    // inject this City-of-Silver entry into any mainland Sun character's prompt.
    // The prose still names his Sun pathway; the entry stays city-gated to "silver".
    npcs: ["Derrick Berg"],
    sequences: [],
    tags: ["forsaken-land", "city-of-silver", "tarot-club", "the-sun", "sun-pathway"],
    tokenCount: 220,
    narratorOnly: false,
  },
  {
    slug: "npc-giant-king-aurmir",
    title: "Giant King Aurmir — The Lord of the Ruined Court",
    category: "npc",
    content: `Giant King Aurmir is the legendary figure for whom Giant King's Court — the titan-scaled ruin east of the City of Silver — is named, remembered in the City's lore as a lord of the elder Giants from the ages before the continent fell. To the abandoned faithful he is half history and half myth: a being of the old inhuman powers whose seat outlived him, its broken thrones and colossal halls now the holiest and most feared site on the Forsaken Land. The City keeps his name and his rites because his Court is no mere ruin — its shadow in the Dream World is the single doorway in and out of the sealed continent — so the keepers who guard that secret guard his memory with it. Whether anything of Aurmir himself yet lingers about the Court is a question the City's deepest order does not answer for outsiders.`,
    epoch: 5,
    city: "giant",
    npcs: ["Giant King Aurmir"],
    sequences: [4],
    tags: ["forsaken-land", "giant-kings-court", "giant", "legend"],
    tokenCount: 195,
    narratorOnly: true,
  },
  // ── Backlund deep-dive (world build-out 4, issue #133) ──
  // City-keyed to "backlund" so the narrator carries them for a character in the
  // capital. Deliberately NOT pathway-keyed (the issue #132 leak rule): a
  // `pathway` field would inject a Backlund NPC into any same-pathway character's
  // prompt regardless of where they are. Pathways are named only in prose.
  // All canon (names, families, pathways, identities) verified against corpus/wiki
  // (see CLAUDE.md "Canon & Source Material") — NOT memory.
  {
    slug: "npc-audrey-hall",
    title: "Audrey Hall — Lady of Empress Borough, the Tarot Club's Justice",
    category: "npc",
    content: `Audrey Hall is the youngest child and only daughter of the aristocratic Hall family of Backlund's Empress Borough — her father an Earl who sits in the Cabinet and ranks among Loen's foremost bankers, her mother Caitlyn, and her two elder brothers Hibbert and Alfred. A poised and famously charming young noblewoman, called "Backlund's most dazzling gem," she moves easily through the salons and balls of the capital's high society. Behind that public face she is a Beyonder of the Visionary (Spectator) pathway, gifted in reading and gently swaying the minds and hearts of others, and — known to no one in her ordinary world — a member of the secret Tarot Club, where she takes the name "Justice." Idealistic, quick-witted, and braver than her sheltered upbringing would suggest, she is determined to use her gifts for genuine good. Her devoted golden retriever Susie — who drank one of her early potions and is no ordinary dog — is rarely far from her side. She is a living bridge between Backlund's gilded surface and its hidden Beyonder depths.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Audrey Hall", "Hibbert Hall", "Alfred Hall", "Caitlyn Hall"],
    sequences: [],
    tags: ["backlund", "hall-family", "tarot-club", "the-justice", "visionary-pathway"],
    tokenCount: 250,
  },
  {
    slug: "npc-hall-family",
    title: "The Hall Family — A Noble House of Empress Borough",
    category: "npc",
    content: `The Hall family is one of the most prominent aristocratic houses of Backlund, seated in the Earl Hall Villa in Empress Borough on the refined bank of the Tussock. The Earl himself is a power in the capital — a member of the Cabinet and one of the foremost bankers of the Loen Kingdom — and with his wife Caitlyn he has raised three children: the eldest son and heir Hibbert, the second son Alfred, and the youngest, his only daughter Audrey, the family's brightest light in society. Like the great families around them the Halls live by the rituals of their class: the season's balls, advantageous marriages, parliamentary connection, and the careful management of reputation and fortune. On the surface they are exactly what they appear to be — old money and high office in a city built on both. What the Earl does not know is that his daughter walks a hidden world far stranger and more dangerous than any drawing-room intrigue.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Caitlyn Hall", "Hibbert Hall", "Alfred Hall", "Audrey Hall"],
    sequences: [],
    tags: ["backlund", "hall-family", "nobility", "empress-borough"],
    tokenCount: 220,
  },
  {
    slug: "npc-klein-backlund-identities",
    title: "Sherlock Moriarty & Dwayne Dantès — Backlund Cover Identities",
    category: "npc",
    content: `In Backlund, one extraordinarily capable Beyonder operates behind two carefully built faces. SHERLOCK MORIARTY is a private detective working out of an office on Minsk Street in Cherwood Borough — sharp, theatrical, and uncannily good at the cases the police cannot close; he moves through the capital's underworld and its tragedies, the smog-choked economic crisis among them, gathering what no badge ever could. DWAYNE DANTÈS is the other face: a mysterious, fabulously wealthy tycoon and philanthropist who buys his way into Empress Borough high society, founds a charitable bursary, donates to the Church of the Evernight Goddess, and trades quietly in influence and arms. The two never appear to be the same man, and neither appears to be what he truly is — a powerful Beyonder, the Tarot Club's masked "Fool," using Backlund as his stage. To the city they are a clever detective and a generous magnate; to those who could see clearly, they are two masks worn by a single mind.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Sherlock Moriarty", "Dwayne Dantès", "Klein Moretti"],
    sequences: [],
    tags: [
      "backlund",
      "klein-identities",
      "sherlock-moriarty",
      "dwayne-dantes",
      "tarot-club",
    ],
    tokenCount: 230,
    narratorOnly: true,
  },
  {
    slug: "npc-bravehearts-temperance",
    title: "Sharron & Maric — the Bravehearts Bar Exiles",
    category: "npc",
    content: `Sharron and Maric are two Beyonders of the Chained pathway who fled the Rose School of Thought when its Temperance faction was shattered, and who found refuge in Backlund under the protection of the Tarot Club's "The Fool." They keep to the Bravehearts Bar near the Backlund Bridge and to lodgings in Hillston Borough — Sharron a formidable, watchful bodyguard (hired more than once by their mysterious patron) who carries the Tarot name "Temperance," and Maric her steadfast companion, the "Knight of Swords." Survivors of an order that turned to devouring desire, they hold instead to the discipline of restraint the Rose School abandoned. To ordinary Backlunders they are simply foreign regulars at a riverside bar; in truth they are exiles of a heresy, sheltering with the very network that opposes the Mother Tree of Desire, and fiercely loyal to the patron who took them in when their own kind hunted them.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Sharron", "Maric", "Reinette Tinekerr"],
    sequences: [],
    tags: [
      "backlund",
      "rose-school-of-thought",
      "temperance",
      "tarot-club",
      "chained-pathway",
    ],
    tokenCount: 215,
    narratorOnly: true,
  },
  // ── Moon City — the eastern fog-watch (issue #133). City-keyed "moon" (a City-
  // of-Silver native never receives this; the cities were mutually unaware). NOT
  // pathway-keyed (the #132 leak rule); pathway named only in prose. ──
  {
    slug: "npc-nim",
    title: "Nim — High Priest of Moon City",
    category: "npc",
    content: `Nim is one of the three High Priests who hold Moon City together against the dead land — an old man wrapped in dark beast-hide, his grey hair unkempt, his face seamed with cracks that are not only age. A demigod-tier Beyonder of the Darkness path (a Sequence 4 Nightwatcher), he is the closest thing the isolated city has to a guardian and a king: he keeps the old rites, rations the city's strength, and carries the weight of its ancient duty to watch the gray fog. Hard, patient, and unsentimental in the way only a man who has buried generations can be, Nim is nonetheless not cruel — every harsh choice he makes is bent toward one end, that Moon City last another year. His ties are to his fellow High Priests, to the watchful people in his charge, and to a duty laid on the city by a god who no longer answers.`,
    epoch: 5,
    city: "moon",
    npcs: ["Nim"],
    sequences: [4],
    tags: ["forsaken-land", "moon-city", "high-priest", "darkness-pathway"],
    tokenCount: 205,
    narratorOnly: true,
  },
  // ── Wider Loen Kingdom (world build-out 5, issue #134) ──
  // City-keyed where the figure belongs to one of our curated cities (Gawain →
  // Tingen/Awwa County; Welch McGovern → Constant). The Foundation figures
  // (Pacheco Dwayne, Barton) sit in Stoen City, East Chester County, which is
  // NOT a curated travel city, so they carry NO `city` key — corpus/RAG +
  // integrity + archetype-tie only, never curated-injected. NONE is pathway-
  // keyed (the issue #132 leak rule): a `pathway` field would inject a regional
  // NPC into any same-pathway character's prompt; pathways are named in prose.
  // All canon verified against corpus/wiki (see CLAUDE.md) — NOT memory.
  {
    slug: "npc-gawain",
    title: "Gawain — The Last Awwa Knight",
    category: "npc",
    content: `Gawain is one of the last living representatives of the Awwa Knights' Order of Chivalry, the knighthood that once guarded Tingen's county and faded into history when the high-pressure steam gun and the six-barrel machine gun made armoured swordsmen obsolete. Far from mourning the change, Gawain has embraced it: a hard, weathered old combatant, he holds that there is no sense studying the sword in this age and that a fighting man should learn instead to draw his gun and shoot, mastering the most advanced weaponry the foundries can make. He earns his living now as a combat instructor in Tingen, drilling those who need to survive violence in strength, endurance, footwork, and marksmanship — among his pupils, for a season, the young Nighthawk-to-be Klein Moretti, whom he ran ragged through afternoons of basic conditioning and pistol work. Gruff, practical, and entirely without romance about his vanished order, Gawain is a useful man to know for anyone in Awwa County who expects to have to fight and would rather not die learning how.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Gawain", "Klein Moretti"],
    sequences: [],
    tags: ["tingen", "awwa-county", "awwa-knights", "combat-instructor", "mentor"],
    tokenCount: 215,
    narratorOnly: false,
  },
  {
    slug: "npc-welch-mcgovern",
    title: "Welch McGovern — The Banker's Son of Constant",
    category: "npc",
    content: `Welch McGovern is a young man of the Wind City of Constant, the son of a wealthy banking family with a stake in the Constant Coal and Steel Consortium, who came south to read history at Khoy University in Tingen. There he studied under Senior Associate Professor Cohen alongside Naya and the original Klein Moretti, and — easy-going, well-funded, and not much troubled by ambition — fell into the habit of leaning on his cleverer group-mates to carry the work he could not be bothered to do himself. Generous with his father's money and careless with most else, he is the very picture of the comfortable provincial money that Constant's furnaces have made: a Khoy man with a soft accent of the industrial north, a name that opens doors among the coal-and-steel set, and family connections that reach from the counting-houses of Constant to the lecture halls of Tingen. To anyone tied to the McGovern household he is a friend worth having and a responsibility worth watching — for trouble has a way of finding the heedless rich.`,
    epoch: 5,
    city: "constant",
    npcs: ["Welch McGovern", "Klein Moretti"],
    sequences: [],
    tags: ["constant", "khoy-university", "banking-family", "civilian"],
    tokenCount: 215,
    narratorOnly: false,
  },
  {
    slug: "npc-pacheco-dwayne",
    title: "Pacheco Dwayne — Deputy Director of Compliance",
    category: "npc",
    content: `Pacheco Dwayne is a deputy director of the Compliance Department of the Loen Relic Search and Preservation Foundation — and, unknown to the Foundation's ordinary staff, a Beyonder of the Black Emperor pathway. Common-featured, black-haired, and unremarkable to look at, he was once a private lawyer in Backlund, partner to the late Framis Cage and afterward legal adviser to the Backlund Bike Company. When Cage died, Pacheco secured Cage's family a considerable share by means his rivals called inappropriate, and the enmity that earned him made Backlund too warm to stay; at Audrey Hall's invitation he left the capital for East Chester County and the Foundation's discreet Beyonder division. He is a man defined by a single conviction — that the world needs order and rules — and he applies it with a lawyer's cold precision to the abnormal things the Foundation's diggers unearth. Loyal to Audrey, allied with the men he trusts, and ruthless with those who break the order he believes in, Pacheco is the kind of subordinate a hidden power most wants: competent, principled in his fashion, and entirely discreet.`,
    epoch: 5,
    npcs: ["Pacheco Dwayne", "Framis Cage", "Audrey Hall"],
    sequences: [5],
    tags: [
      "loen-relic-foundation",
      "compliance-department",
      "black-emperor-pathway",
      "audrey-hall",
    ],
    tokenCount: 230,
    narratorOnly: true,
  },
  {
    slug: "npc-barton",
    title: "Barton — An Ordinary Man of the Foundation",
    category: "npc",
    content: `Barton is an upper-middle-class clerk in the employ of the Loen Relic Search and Preservation Foundation, living a settled life in Stoen City of East Chester County with his wife and children, a devotee of the Church of the Lord of Storms and a reader of cheap murder-and-romance novels in his spare hours. He is, by every measure, an ordinary man — save for one thing. Ten years ago, on an archaeological excavation that went badly, Barton came away with a faint thread of spiritual perception no ordinary person carries: he senses, now and then, movements and presences that others cannot, a prickle at the back of the neck when something is wrong. It is not power, only awareness — but in a foundation whose diggers turn up the relics of older epochs, an ordinary man who can feel when a thing is wrong is more useful than he knows. His old friend the archaeologist Vernal Fnarr brings him trouble; his colleague the deputy director Pacheco Dwayne brings him answers; and Barton, who wants only a quiet life, keeps being drawn to the edge of a hidden world he was never meant to see.`,
    epoch: 5,
    npcs: ["Barton", "Vernal Fnarr", "Pacheco Dwayne"],
    sequences: [],
    tags: [
      "loen-relic-foundation",
      "east-chester-county",
      "civilian",
      "spiritual-perception",
    ],
    tokenCount: 230,
    narratorOnly: false,
  },
  // ── Intis Republic — Trier (world build-out 6, issue #135) ──
  // City-keyed "trier" so the narrator carries them for a character in the
  // Intis capital. Deliberately NOT pathway-keyed (the #132 leak rule): a
  // `pathway` field would inject a Trier NPC into any same-pathway character's
  // prompt; the Sun pathway is named only in prose. narratorOnly for the
  // Angel/Saint/Beyonder truths beneath their public church roles. All canon
  // verified against corpus/wiki (see CLAUDE.md) — NOT memory.
  {
    slug: "npc-saint-vieve",
    title: "Saint Viève — Guardian Angel of Trier",
    category: "npc",
    content: `Saint Viève is the only female angel named in the Bible of the Church of the Eternal Blazing Sun, venerated as one of the three guardian angels of Trier and the namesake of the great cathedral that crowns the Island District. To the faithful of the sunlit capital she is the radiant protector of their city; in truth she is an Angel-tier Beyonder of the Sun pathway, a figure draped in white robes shot with gold who seems crafted from pure light — emerald-eyed, blond, translucent, and divine. Her ties are to the Church she serves and to the city she guards: she answers the cathedral's gravest needs, descends against the servants of the Outer Deities when they threaten Trier, and stands among the powers that have held the capital safe across the ages. Most Trierans will never see her with their own eyes; that they believe in her at all is the measure of how deeply the Blazing Sun is woven into the life of the City of Fashion.`,
    epoch: 5,
    city: "trier",
    npcs: ["Viève"],
    sequences: [4],
    tags: ["trier", "eternal-blazing-sun", "angel", "sun-pathway", "guardian"],
    tokenCount: 215,
    narratorOnly: true,
  },
  {
    slug: "npc-plessy-descartes",
    title: "Cardinal Plessy Descartes — Head of the Trier Diocese",
    category: "npc",
    content: `Cardinal Plessy Descartes oversees the Trier diocese of the Church of the Eternal Blazing Sun from Saint Viève Cathedral in the Island District. An elderly man with high cheekbones and grizzled blond hair, his manner is mild rather than stern, yet a faint radiance clings to him that makes direct eye contact difficult and seems to leave a room without shadows — the mark of a Saint-tier Beyonder of the Sun pathway. He is the Church's senior authority in the capital: he commands its clergy, blesses its rites, and directs its sterner work, summoning Purifiers of the Inquisition to Saint Viève Cathedral and raising the deserving among them to the rank of deacon. Patient, watchful, and utterly devoted to the radiant order of the sun-faith, the Cardinal is the human face of the Church's power in Trier — the man through whom its will reaches both the pulpit and the shadows the Inquisition is set to burn.`,
    epoch: 5,
    city: "trier",
    npcs: ["Plessy Descartes"],
    sequences: [4],
    tags: ["trier", "eternal-blazing-sun", "cardinal", "sun-pathway", "inquisition"],
    tokenCount: 215,
    narratorOnly: true,
  },
  {
    slug: "npc-angouleme-de-francois",
    title: "Angoulême de François — Deacon-Purifier of the Inquisition",
    category: "npc",
    content: `Angoulême de François is a deacon of the Church of the Eternal Blazing Sun's Inquisition in Trier and, in the same breath, a Deputy Assistant Commissioner of the city's police — a man who holds both the sacred and the civic authority over Quartier 13. A blond Sun-pathway Beyonder of the Saint tier (a Sequence 4 "Unshadowed"), he hunts heresy, corruption, and the servants of the Outer Deities with the same cold competence he brings to ordinary crime, teaching his subordinates that even beneath the sun there are shadows one must learn to use, to eliminate, or to coexist with. He answers to Cardinal Plessy Descartes and leads a small team of his own — among them Imre, Valentine de Lacourt, and Antoine. Bridging cathedral and constabulary, the Inquisition and the law, Angoulême is exactly the sort of figure the Republic's capital runs on: a believer with a badge, equally at home blessing a congregation and interrogating a suspect, and a dangerous man to deceive on either count.`,
    epoch: 5,
    city: "trier",
    npcs: [
      "Angoulême de François",
      "Plessy Descartes",
      "Imre",
      "Valentine de Lacourt",
      "Antoine",
    ],
    sequences: [4],
    tags: ["trier", "eternal-blazing-sun", "inquisition", "sun-pathway", "police"],
    tokenCount: 225,
    narratorOnly: true,
  },
  // ── Orthodox Churches sweep (world build-out 10, issue #139) ──
  // Notable, corpus-verified members of the eight Churches, with relationship
  // data (family/friends/colleagues/affiliations). City-keyed to their home
  // travel-city where canon places them there (else uncityed, cross-cutting),
  // and — like the issue #132/#135 regional NPCs — NEVER `pathway`-keyed: a
  // member's pathway is named only in prose, so a same-pathway character never
  // has a far-off cleric injected by the pathway selector. narratorOnly:true for
  // the Angel/Saint/Beyonder truths beneath their public church roles.
  {
    slug: "npc-arianna",
    title: "Arianna — Head of the Evernight Goddess's Thirteen Archbishops",
    category: "npc",
    content: `Arianna is the matron of the Evernight Cloister and Head of the Thirteen Archbishops of the Church of the Evernight Goddess — by most reckonings, the next Pope. An ascetic who asks to be called "Ma'am" rather than "Your Eminence," she goes barefoot in a patched linen robe, her manner all calm and quiet certainty, and she keeps a conscience strong enough to balk at sacrificing innocents for the Church's ends. She is a Servant of Concealment, a Sequence 2 demigod of the Darkness Pathway, and a Mythical Creature in truth, though she wears an ordinary woman's face. Her most important tie is to Klein Moretti: she often relays and assists the Evernight Goddess's oracles to him, becoming one of the Church's surest hands in the strange events that gather around the Fool. Within the Council of twenty-two equals she stands first among the archbishops, answering only to the Goddess and the Pope.`,
    epoch: 5,
    npcs: ["Arianna", "Klein Moretti"],
    sequences: [2],
    tags: ["evernight-goddess", "archbishop", "darkness-pathway", "cloister"],
    tokenCount: 215,
    narratorOnly: true,
  },
  {
    slug: "npc-gaard-ii",
    title: "Gaard II — Pontiff of the Lord of Storms",
    category: "npc",
    content: `Gaard II is the Pontiff of the Church of the Lord of Storms and the spokesman of the storm-god himself, seated at the Chasm of Storms Cathedral on Pasu Island. Though he wears the face of a man in his forties, he has led the Council of Cardinals for nearly a century; crowned with a triple diadem of sapphire and emerald and robed in storm-dark blue shot with gold and silver, he carries himself like a gathering tempest. As Head of the Council of Cardinals he commands both the Church's clergy and its Beyonder arm, the Mandated Punishers, who take their orders directly from the Council. He is a Calamity, a Sequence 2 demigod of the Tyrant Pathway and a Mythical Creature beneath the man's shape. To the faithful of the seas he is the nearest thing to the Lord of Storms made flesh — the voice through which the King of the Skies and Emperor of the Seas speaks to his Church.`,
    epoch: 5,
    npcs: ["Gaard II"],
    sequences: [2],
    tags: ["lord-of-storms", "pontiff", "tyrant-pathway", "mandated-punishers"],
    tokenCount: 210,
    narratorOnly: true,
  },
  {
    slug: "npc-jahn-kottman",
    title: "Jahn Kottman — The Sea King of Bayam",
    category: "npc",
    content: `Jahn Kottman is a Cardinal of the Church of the Lord of Storms and a high-ranking deacon of the Mandated Punishers, and was long the true ruler of the Beyonder world in the Rorsted Archipelago from the Cathedral of Waves in Bayam. Brawny and deep-eyed, his blue hair thick as a knot of tentacles, he is aggressive and impulsive in the way of his pathway — a Sea King, a Sequence 3 of the Tyrant Pathway who boasts that even a War Bishop must bow his head in his waters. He once contained the rampage of the dying Sea God Kalvetua and tried to claim his characteristics, only to be beaten to the corpse by the Fool. When the bounty hunter Gehrman Sparrow drew his eye in Bayam, Kottman reported him and saw a bounty placed on his head; he later crushed a sea-borne invasion of Bayam during the World War. His rivalries run from the Rose School of Thought to the man behind Gehrman Sparrow's many masks.`,
    epoch: 5,
    city: "bayam",
    npcs: ["Jahn Kottman", "Klein Moretti", "Kalvetua"],
    sequences: [3],
    tags: [
      "lord-of-storms",
      "cardinal",
      "sea-king",
      "tyrant-pathway",
      "bayam",
      "mandated-punishers",
    ],
    tokenCount: 225,
    narratorOnly: true,
  },
  {
    slug: "npc-bornova-gustav",
    title: "Saint Bornova Gustav — Guardian Angel of Trier",
    category: "npc",
    content: `Saint Bornova is venerated as a Guardian Angel of Trier and is the youngest son of the transmigrator-emperor Roselle Gustav. More than a century old, he is a Knowledge Magister — a Sequence 2 Angel of the Paragon Pathway — in the service of the Church of the God of Steam and Machinery, whose Patriarchal Cathedral crowns the capital. His mother was Matilda Abel; his elder sister Bernadette Gustav still lives, his elder brother Ciel does not. The Twilight Hermit Order's Zaratul mockingly called him the "Lovely Angel." It is whispered at the Church's heights that the god of Steam used Bornova to keep a quiet hand on his own father, the Son of Steam — a burden the Saint carries behind his serene, radiant face. To the people of Trier he is simply one of the powers that keep the City of Fashion safe, an angel of brass and steam standing watch beside Saint Viève of the sun-faith.`,
    epoch: 5,
    city: "trier",
    npcs: ["Bornova Gustav", "Roselle Gustav", "Bernadette Gustav"],
    sequences: [2],
    tags: ["god-of-steam", "saint", "guardian-angel", "paragon-pathway", "trier"],
    tokenCount: 220,
    narratorOnly: true,
  },
  {
    slug: "npc-horamick-haydn",
    title: "Horamick Haydn — Archbishop of Steam and Machinery",
    category: "npc",
    content: `Horamick Haydn is an Archbishop of the Church of the God of Steam and Machinery and a member of its Divine Council, presiding now over the Trier diocese after years in Backlund. He leads a double life that the machine-faith finds no contradiction in: an emeritus professor of physics at Backlund University and a celebrated scientist, he is also a captain of the Machinery Hivemind and an Alchemist — a Sequence 4 demigod of the Paragon Pathway. In him the Church's love of invention and its Beyonder power meet in one man, equally at home before a lecture hall and at the head of a Hivemind team hunting supernatural contamination through the foundries and workshops. Patient and exacting, he embodies the Church's creed that the one who would be strong should be made strong — and that knowledge and machinery, rightly mastered, are themselves a kind of worship.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Horamick Haydn"],
    sequences: [4],
    tags: [
      "god-of-steam",
      "archbishop",
      "machinery-hivemind",
      "paragon-pathway",
      "backlund",
    ],
    tokenCount: 205,
    narratorOnly: true,
  },
  {
    slug: "npc-isengard-stanton",
    title: "Isengard Stanton — Mr. Eye of Wisdom",
    category: "npc",
    content: `Isengard Stanton, who styles himself Mr. Eye of Wisdom, is a private detective of Backlund and a believer of the Church of the God of Knowledge and Wisdom. He took up the faith while studying four years in Lenburg, and keeps a careful cover as an Evernight worshipper at home in Loen; in truth he is a Detective in the Beyonder sense too — a Sequence 7 of the White Tower Pathway, whose reason and deduction the god he serves prizes above birth or wealth. His cases bring him into the orbit of another Backlund detective, Sherlock Moriarty, with whom he keeps a wary friendship of professional equals. Devout in his own quiet way, he has asked that when he dies his remains be sent to the Holy Temple of Knowledge in distant Azshara — a scholar's last pilgrimage to the seat of the omniscient eye.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Isengard Stanton", "Klein Moretti"],
    sequences: [7],
    tags: ["god-of-knowledge", "detective", "white-tower-pathway", "backlund"],
    tokenCount: 195,
    narratorOnly: true,
  },
  {
    slug: "npc-edwina-edwards",
    title: "Edwina Edwards — Archbishop and Pirate Admiral 'Iceberg'",
    category: "npc",
    content: `Edwina Edwards is an Archbishop of the Church of the God of Knowledge and Wisdom — and, to the navies of the world, the Pirate Admiral "Vice Admiral Iceberg," captain of the Golden Dream with a great bounty on her head. Born in Lenburg, descended from a follower of Roselle Gustav whose family fled and converted to the wisdom-faith, she is a Prophet, a Sequence 4 demigod of the White Tower Pathway. She commands a crew of subordinates across the seas and keeps an old friendship with Anderson Hood, the Fog Sea's strongest hunter, from their schooldays at the Church's college. In the great events of the age she becomes an ally of the adventurer Gehrman Sparrow, lending the omniscient eye's foresight to causes that reach far beyond Lenburg's borders. Few embody the Church's prizing of talent over birth so plainly as a prophet who is also a pirate.`,
    epoch: 5,
    npcs: ["Edwina Edwards", "Anderson Hood"],
    sequences: [4],
    tags: ["god-of-knowledge", "archbishop", "white-tower-pathway", "pirate", "lenburg"],
    tokenCount: 200,
    narratorOnly: true,
  },
  {
    slug: "npc-brignais",
    title: "Baron Brignais — The Wisdom-Faith's Man in Trier",
    category: "npc",
    content: `Baron Brignais is a believer of the Church of the God of Knowledge and Wisdom who keeps his faith and his trade well apart: a nobleman by reputation, he is in fact the head of the Savoie Mob in the market district of Trier. A man of about thirty, married, he is a Student of Ratiocination — a Sequence 8 of the White Tower Pathway — using the god's gift of reason to run his rackets with uncanny shrewdness. He stands godfather to a young man named Ludwig, a tie that binds him into the quieter networks of the capital. In a city of sun-faith and steam, Brignais is a reminder that the wisdom-faith keeps its own people even where it does not rule: clever, watchful, and useful, valued by his god for exactly the talents the law would condemn.`,
    epoch: 5,
    city: "trier",
    npcs: ["Brignais", "Ludwig"],
    sequences: [8],
    tags: ["god-of-knowledge", "white-tower-pathway", "trier", "mob"],
    tokenCount: 185,
    narratorOnly: true,
  },
  {
    slug: "npc-emlyn-white",
    title: "Emlyn White — The Sanguine of the Harvest Church",
    category: "npc",
    content: `Emlyn White — once known as Bai Ailin — is a young Sanguine who fell into the keeping of the Harvest Church in Backlund and became a believer of the Earth Mother. A high-ranking deacon, or Hierophant, of the life-faith, he is a Beyonder of the Moon Pathway, rising from Shaman King to Life-Giver, and stands as the representative of Backlund's Sanguines after they merged with the Church. He came to the faith through Father Utravsky, the towering ex-pirate bishop who confiscated his Master Key and gave him his own blood, and whom Emlyn first despised as a "dirty old man" before coming to respect him. In the Tarot Club, that strange gathering of the Fool's chosen, he is known as The Moon. He also befriended the detective Sherlock Moriarty, and the Earth Mother herself is said to have entrusted him with a fragment of her own power before her long sleep.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Emlyn White", "Utravsky", "Klein Moretti"],
    sequences: [4, 2],
    tags: [
      "earth-mother",
      "harvest-church",
      "sanguine",
      "moon-pathway",
      "tarot-club",
      "backlund",
    ],
    tokenCount: 215,
    narratorOnly: true,
  },
  {
    slug: "npc-utravsky",
    title: "Father Utravsky — Bishop of the Harvest Church",
    category: "npc",
    content: `Father Utravsky is the bishop of the Harvest Church on Rose Street, the Church of the Earth Mother's house in Backlund. Born in the Feysac highlands and once a ruthless pirate of the Sonia Sea, he was turned to the life-faith by an Earth Mother missionary and swore upon her sacred emblem to spread her worship abroad before he would ask the Church for any help. A mountain of a man over two metres tall, gentle in the face for all his oppressive size, he is a Dawn Paladin — a Sequence 6 of the Twilight Giant Pathway — counted among the Earth Mother's Blessed, with a grounding in herbalism. He took in the lost Sanguine Emlyn White and shelters Backlund's poor through disaster and smog alike. It was to Utravsky that the detective Sherlock Moriarty came seeking the Apothecary potion's formula — earned only by mastering the bishop's own inner self.`,
    epoch: 5,
    city: "backlund",
    npcs: ["Utravsky", "Emlyn White", "Klein Moretti"],
    sequences: [6],
    tags: [
      "earth-mother",
      "harvest-church",
      "twilight-giant-pathway",
      "backlund",
      "bishop",
    ],
    tokenCount: 205,
    narratorOnly: true,
  },
  {
    slug: "npc-matriarch-roland",
    title: "Matriarch Roland — Leader of the Church of the Earth Mother",
    category: "npc",
    content: `Roland is the Matriarch of the Church of the Earth Mother — the leader of the whole life-faith — ruling from its seat in the Feynapotter Kingdom. She is a Desolate Matriarch, a Sequence 2 Angel of the Mother Pathway, the living head of a Church that prizes fertility and the return of every soul to the Mother's embrace. Her tragedy is the Church's gravest danger made flesh: in 1359 she was corrupted by the false revelations of the Mother Goddess of Depravity — the very deceit the Church's split into Favored and Blessed was meant to guard against — and became that Outer Deity's puppet. It is precisely because a Matriarch could fall this way that no order of the Church may issue without the countersignature of both its halves. Her fall is among the signs that the Earth Mother's house, for all its talk of life, stands nearer the abyss than any of the orthodox faiths.`,
    epoch: 5,
    npcs: ["Roland"],
    sequences: [2],
    tags: ["earth-mother", "matriarch", "mother-pathway", "feynapotter"],
    tokenCount: 205,
    narratorOnly: true,
  },
  {
    slug: "npc-larrion",
    title: "Larrion — Chief Shepherd of the God of Combat",
    category: "npc",
    content: `Larrion is the Chief Shepherd of the Church of the God of Combat, the highest operational hand of the war-faith in the Feysac Empire. Over two and a half metres tall, light-blue-eyed, speaking in a rough country dialect, he is a Glory — a Sequence 2 demigod of the Twilight Giant Pathway — and fanatically loyal, willing to make of his own body a vessel for his god's return. When the God of Combat was slain at the Battle of Gods over Backlund, Larrion burned the Church's records of its Sealed Artifacts and fled with the Trunsoest Brass Book, trapping his pursuers in Belltaine City; confronted there by the Evernight Goddess's Arianna and by Klein Moretti, he lost some of his characteristics but escaped through the Spirit World, his fate unknown. He believes, against all evidence, that his god will rise again in his own body — and waits.`,
    epoch: 5,
    city: "feysac",
    npcs: ["Larrion", "Arianna", "Klein Moretti"],
    sequences: [2],
    tags: ["god-of-combat", "chief-shepherd", "twilight-giant-pathway", "feysac"],
    tokenCount: 200,
    narratorOnly: true,
  },
  {
    slug: "npc-valentine-de-lacourt",
    title: "Valentine de Lacourt — Purifier of the Blazing Sun",
    category: "npc",
    content: `Valentine de Lacourt is a Purifier of the Inquisition of the Church of the Eternal Blazing Sun, serving in Trier under the Deacon Angoulême de François. A Solar High Priest — a Sequence 7 of the Sun Pathway — he is one of the radiant order's enforcers, hunting heresy, corruption, and the servants of the Outer Deities through the quartiers of the capital. He works alongside the other members of Angoulême's small team — Imre, of the same sun-faith, and Antoine of the Twilight Giant Pathway — the censer and the badge moving together in a city that keeps both. In the Inquisition's ranks he is the kind of steady middle hand on whom its grimmer work depends: devout, disciplined, and dangerous to the enemies of the light.`,
    epoch: 5,
    city: "trier",
    npcs: ["Valentine de Lacourt", "Angoulême de François", "Imre", "Antoine"],
    sequences: [7],
    tags: ["eternal-blazing-sun", "inquisition", "purifier", "sun-pathway", "trier"],
    tokenCount: 185,
    narratorOnly: true,
  },
  // ── Feysac Empire NPCs (world build-out 7, issue #136, corpus-verified) ──
  // The imperial Einhorn naval house and a Feysac-born Combat-faithful. City-keyed
  // to where canon places them; NOT pathway-keyed (the #132 leak rule — pathway
  // named only in prose); narratorOnly for the Angel/Beyonder truths.
  {
    slug: "npc-awatoma-einhorn",
    title: "Awatoma Einhorn — Supreme Commander of the Feysac Navy",
    category: "npc",
    content: `Awatoma Einhorn is the Supreme Commander of the Feysac Navy, the angel-general the empire hails as "the Great Awatoma Einhorn, Ruler of the Fog of the Battlefield." He is of the imperial Einhorn house — the Red Priest line that holds the Feysac throne and the Sonia Sea Fleet — and a Weather Warlock, a Sequence 2 Angel who turns sea and storm against the empire's enemies from the war-zone of the Sonia Sea. His kinsman Egor Einhorn serves as a commander beneath him; when Egor was once unmanned by a strange adventurer, it was Awatoma's honorific name he called upon for aid. In a realm that measures a man by his height and his battles, Awatoma stands near the summit of both — the Einhorns' war-leader and one of the deadliest servants of the militarist north.`,
    epoch: 5,
    city: "feysac",
    npcs: ["Awatoma Einhorn", "Egor Einhorn"],
    sequences: [2],
    tags: ["feysac", "einhorn", "red-priest", "navy", "angel"],
    tokenCount: 200,
    narratorOnly: true,
  },
  {
    slug: "npc-egor-einhorn",
    title: "Egor Einhorn — Commander of the Feysac Imperial Navy",
    category: "npc",
    content: `Egor Einhorn is a commander of the Feysac Imperial Navy and a son of the imperial Einhorn house — a burly, bearded giant of a man over two metres tall who kept the flagship Nepos in the Sonia Sea war-zone. An Iron-blooded Knight, a Sequence 4 of the Red Priest Pathway, he is a hard and capable officer of the militarist north, kin and subordinate to the Supreme Commander Awatoma Einhorn. His one famous humiliation came when a lone adventurer aboard a captured ship — a man quietly digesting a potion he could not yet control — unnerved him so badly that Egor broke off and called on Awatoma's name for protection. It is the kind of story Feysac's height-proud officers never let a man forget.`,
    epoch: 5,
    city: "feysac",
    npcs: ["Egor Einhorn", "Awatoma Einhorn", "Klein Moretti"],
    sequences: [4],
    tags: ["feysac", "einhorn", "red-priest", "navy"],
    tokenCount: 195,
    narratorOnly: true,
  },
  {
    slug: "npc-ozil",
    title: "Strongman Ozil — Combat-Faithful of the Underworld",
    category: "npc",
    content: `Ozil, called Strongman Ozil, was a Feysac-born son of the Church of the God of Combat and once a famous pirate of the seas before he sank into the Beyonder underworld of Bayam as the secret master of the Amyris Leaf Bar. A Pugilist — a Sequence 8 of the Twilight Giant Pathway — he carried the Combat faith's raw ferocity into the shadows of the Rorsted Archipelago, an ally of the smuggler Mithor King. His end came at the hands of the bounty hunter Gehrman Sparrow, who killed him in early 1350 and saw his Beyonder characteristic sold on to the alchemist Cattleya — one more violent Feysac export the wider world quietly absorbed.`,
    epoch: 5,
    city: "bayam",
    npcs: ["Ozil", "Mithor King", "Klein Moretti", "Cattleya"],
    sequences: [8],
    tags: ["feysac", "god-of-combat", "twilight-giant-pathway", "bayam", "pirate"],
    tokenCount: 175,
    narratorOnly: true,
  },
];
