import type { LoreEntry } from "./types";

export const ORGANIZATION_LORE: LoreEntry[] = [
  {
    slug: "nighthawks-overview",
    title: "Nighthawks — Overview",
    category: "organization",
    content: `The Nighthawks are the official Beyonder division of the Church of the Evernight Goddess. They function as a supernatural investigation and enforcement unit, handling incidents involving uncontrolled Beyonders, cursed artifacts, undead manifestations, and other threats that fall under the Evernight Goddess's domain: darkness, night, sleep, and death. Nighthawk teams are stationed in every major city across the Loen Kingdom, operating under cover identities — typically as security companies or private detective agencies. Their mandate is threefold: investigate supernatural incidents, contain or destroy dangerous artifacts and entities, and maintain the secrecy of the Beyonder world from ordinary citizens. Nighthawks are authorized to use lethal force against threats and carry both conventional firearms and mystical equipment. The organization has a military-style hierarchy with captains leading city-level teams, reporting through bishops to the church's central command. Members are recruited from church faithful who show aptitude, and they primarily follow the Sleepless (Darkness) pathway, though members of other pathways serve in support roles.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["nighthawks", "evernight-goddess", "beyonder-organization", "law-enforcement"],
    tokenCount: 220,
  },
  {
    slug: "nighthawks-tingen-team",
    title: "Nighthawks — Tingen Team",
    category: "organization",
    content: `The Tingen Nighthawks team operates out of Blackthorn Security Company on Zouteland Street. Led by Captain Dunn Smith, the team consists of roughly a dozen members, making it a standard-sized regional unit. The team handles all supernatural incidents in Tingen City and the surrounding Awwa County. Key members include Dunn Smith (Captain, Sequence 7 Nightmare), Leonard Mitchell (Sequence 9 Sleepless, later Sequence 8), Klein Moretti (Sequence 9 Seer, the Fool pathway — an unusual assignment since the Fool pathway is not native to the Nighthawks), Old Neil (team historian and artificer), and Daly Simone (Sequence 7 Spirit Medium from the Death pathway, on secondment). The team's daily operations involve monitoring reports of unexplained deaths, ghost sightings, and artifact smuggling; conducting investigations; performing containment rituals; and filing classified reports with the diocese. The Tingen team is considered a quiet posting compared to Backlund, though several major incidents during the narrative period — including the Antigonus Family Notebook case and the Ince Zangwill betrayal — dramatically escalate the danger.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Dunn Smith", "Leonard Mitchell", "Klein Moretti", "Old Neil", "Daly Simone"],
    sequences: [9, 8, 7],
    tags: ["nighthawks", "tingen", "team-composition"],
    tokenCount: 245,
  },
  {
    slug: "nighthawks-procedures",
    title: "Nighthawks — Standard Procedures",
    category: "organization",
    content: `Nighthawk operations follow strict protocols designed to minimize risk and maintain secrecy. Investigations begin with preliminary reports from informants, police contacts, or church sources. Team members are dispatched in pairs for routine investigations, with full-team deployment reserved for confirmed Beyonder-level threats. Standard equipment includes revolvers, holy water blessed by the Evernight Goddess, containment seals, and basic ritual materials. When encountering uncontrolled Beyonders or aberrations, the protocol is containment first, elimination if containment fails. All recovered artifacts are logged and stored in sealed evidence vaults, with particularly dangerous items sent to the diocese's central vault. After each operation, detailed reports are filed and all civilian witnesses are managed — through obfuscation, cover stories, or in extreme cases, memory-altering rituals performed by higher-sequence members. Nighthawks are forbidden from revealing their true nature to civilians, using Beyonder abilities in public view, or retaining confiscated artifacts for personal use. Violations are treated as potential signs of corruption or loss of control and trigger immediate internal review.`,
    epoch: 5,
    npcs: [],
    sequences: [],
    tags: ["nighthawks", "protocols", "operations", "secrecy"],
    tokenCount: 220,
  },
  {
    slug: "mandated-punishers-tingen",
    title: "Mandated Punishers — Tingen Presence",
    category: "organization",
    content: `The Mandated Punishers are the Beyonder division of the Church of the Lord of Storms, responsible for supernatural incidents related to maritime activity, weather phenomena, and the Tyrant pathway. In Tingen, they maintain a smaller presence than the Nighthawks, primarily operating near the Tussock River docks and handling cases involving smuggled Beyonder materials arriving by water, sea-creature manifestations, and conflicts between sailor Beyonders. Their jurisdiction sometimes overlaps with the Nighthawks, creating inter-organizational tension. The Mandated Punishers have a reputation for being more aggressive and direct than the Nighthawks — their operational style favors rapid force over careful investigation. Their members primarily follow the Sailor (Tyrant) pathway, granting them abilities related to storms, water, and physical combat. The Church of the Lord of Storms emphasizes masculine virtues, martial discipline, and dominion over nature, which shapes the Punishers' culture into a more militant organization compared to the contemplative Nighthawks.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["mandated-punishers", "lord-of-storms", "maritime", "beyonder-organization"],
    tokenCount: 210,
  },
  {
    slug: "machinery-hivemind-tingen",
    title: "Machinery Hivemind — Tingen Presence",
    category: "organization",
    content: `The Machinery Hivemind is the Beyonder division of the Church of the God of Steam and Machinery. In Tingen, they are the smallest of the three official Beyonder organizations, focused on cases involving industrial accidents with supernatural causes, malfunctioning mystical machinery, and the Savant pathway. Their members tend to be technically minded, often with engineering or scientific backgrounds, and they approach supernatural problems with an analytical methodology. The Hivemind's unique ability is a form of collective consciousness — members can share information and coordinate through a mystical network that connects their minds, giving them superior communication and coordination in the field. In Tingen's industrial landscape, the Hivemind monitors factories and workshops for signs of Beyonder contamination in manufactured goods and investigates cases where industrial processes accidentally interact with supernatural forces. Their relationship with both the Nighthawks and Mandated Punishers is generally cooperative but bureaucratically distant, with each organization guarding its jurisdictional boundaries.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["machinery-hivemind", "god-of-steam", "industrial", "beyonder-organization"],
    tokenCount: 210,
  },
  {
    slug: "psychology-alchemists-overview",
    title: "Psychology Alchemists — Overview",
    category: "organization",
    content: `The Psychology Alchemists are a semi-secret organization specializing in the Visionary pathway. They present themselves as a scholarly society dedicated to understanding the human mind through a blend of psychology, philosophy, and mystical practice. Their members include academics, doctors, and upper-class intellectuals who study mental phenomena, hypnosis, and the nature of consciousness. For aspiring Beyonders of the Visionary pathway, the Psychology Alchemists are one of the primary sources of potion formulas and advancement guidance outside the orthodox churches. However, the organization harbors a dark secret: it is a shadow subsidiary of the Twilight Hermit Order, controlled by the Angel of Imagination, Adam. Many rank-and-file members are unaware of this connection and genuinely believe in the organization's academic mission. The Psychology Alchemists operate through local chapters in major cities, including a presence in Tingen that becomes relevant when the narrative explores Audrey Hall's storyline and the broader conspiracy surrounding the Visionary pathway.`,
    epoch: 5,
    npcs: ["Audrey Hall"],
    sequences: [9, 8, 7, 6, 5],
    pathway: "visionary",
    tags: [
      "psychology-alchemists",
      "visionary-pathway",
      "secret-organization",
      "twilight-hermit-order",
    ],
    tokenCount: 225,
  },
  {
    slug: "aurora-order-overview",
    title: "Aurora Order — Overview",
    category: "organization",
    content: `The Aurora Order is a fanatical secret organization that worships the "True Creator," an entity connected to the ancient Sun God. Their members are often mentally unstable Beyonders who have been driven partially mad by their abilities or by direct exposure to the True Creator's influence. The Order seeks to bring about their god's physical descent into the world, believing this will usher in an age of divine truth. In Tingen, the Aurora Order operates clandestinely, recruiting from the margins of society — desperate individuals, failed Beyonders, and those who have been rejected by the orthodox churches. Their activities include terrorist attacks against church targets, attempts to steal powerful artifacts, and conducting dangerous rituals. The Aurora Order poses a recurring threat in the Tingen narrative, with several members appearing as antagonists. Their connection to the deeper conspiracy — that the True Creator and the Angel of Imagination Adam are both aspects of the ancient Sun God — only becomes clear much later in the story. For gameplay purposes, they serve as a dangerous faction that players may encounter as enemies.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["aurora-order", "true-creator", "antagonist", "secret-organization"],
    tokenCount: 225,
  },
];
