import type { LoreEntry } from "./types";

export const DARKNESS_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "darkness-pathway-overview",
    title: "Darkness Pathway — Overview",
    category: "pathway",
    content: `The Darkness pathway belongs to the Eternal Darkness group, anchored to the River of Eternal Darkness, the same Above-the-Sequence group as the Death pathway. Its powers turn on night, sleep, and concealment: Beyonders grow stronger as the night deepens, can pacify and host souls, walk into the dreams of others, blanket areas in sleep, see in the dark, and suppress the moods and desires of their enemies. Its authority embodies Silence and Darkness. At high sequences a Darkness Beyonder can raise domains of darkness, weave realistic dreams, shroud regions in secrecy, erase or hide things, bestow misfortune, and become an immortal within the dark. The mythical-creature form of the pathway is a demonic wolf, its limbs covered in short black fur. Its corresponding tarot card is The Star, and its symbolic colour is purpureus. Night vanilla, moon flowers, and slumber flowers are ingredients of the Darkness domain, while white chestnut flowers and wild rose stand for Concealment. The Church of the Evernight Goddess holds and protects much of the Darkness pathway's knowledge, which is why it neighbours the Fool pathway's resources only at a remove.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "darkness-pathway",
      "eternal-darkness-group",
      "river-of-eternal-darkness",
      "overview",
    ],
    tokenCount: 240,
  },
  {
    slug: "darkness-seq9-sleepless",
    title: "Darkness Pathway — Sequence 9: Sleepless",
    category: "pathway",
    content: `The Sleepless is the entry point of the Darkness pathway. Its defining trait is Nocturnality: the deeper into the night, the stronger a Sleepless becomes — physical strength, intuition, and mental clarity all sharpen after dark, and they need only three or four hours of sleep. They possess Night Vision, seeing clearly through total darkness and sensing dangers hidden within it, and carry the High Spirituality common to the pathway, granting a serviceable Spirit Vision for perceiving spiritual things. The potion's main ingredients are a Midnight Beauty Flower (which opens only in the dead of night) and a pair of Six-Footed Owl eyes, supplemented by strong liquor, Night Vanilla essential oil, Midnight Beauty leaves, and a symbolic measure of coffee beans or tea leaves. The acting method demands keeping to the night — working, watching, and acting under cover of darkness, cultivating stillness and concealment, and standing vigil while others rest. As a Sequence 9 sequence it has no advancement ritual; digesting the potion through acting is enough to progress to Midnight Poet.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: ["darkness-pathway", "sleepless", "night", "concealment", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "darkness-seq8-midnight-poet",
    title: "Darkness Pathway — Sequence 8: Midnight Poet",
    category: "pathway",
    content: `The Midnight Poet wields verse as a vehicle for supernatural power. A Midnight Poem can be recited to produce a range of distinct effects in the dark; among them are the Lullaby, which sings listeners into drowsiness and unnatural sleep, and Pacify, which quiets emotions and suppresses the desires and moods of those nearby. The potion's main ingredients are the vocal cords of a Red-Moon Roarer and a Soul-Snatching Wind Chime Flower, with red wine, Red-Moon Roarer hair, deep crimson sandalwood, and the soil the chime-flower grew in as supplementaries. The advancement ritual calls for composing and performing a Midnight Poem at the dead of night that bends a gathered audience to sleep, holding the working until every listener has succumbed. The acting method asks the Midnight Poet to compose and recite by night, to soothe and lull rather than confront, and to keep their true intent veiled behind verse and quiet — the pathway's themes of darkness, sleep, and concealment beginning to deepen.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["darkness-pathway", "midnight-poet", "sleep", "poetry", "acting-method"],
    tokenCount: 240,
  },
  {
    slug: "darkness-seq7-nightmare",
    title: "Darkness Pathway — Sequence 7: Nightmare",
    category: "pathway",
    content: `The Nightmare carries the Darkness pathway into the mid sequences and into the dream world itself. A Nightmare can perform Dream Invasion — entering a sleeping target's dream and moving through its landscape — and Dream Shaping, reshaping the dream's contents into a nightmare of their own design. They can manifest Nightmare Limbs of shadowy dream-stuff to seize and strike, and project a Nightmare State, a dreadful, oppressive aura that erodes the resolve of those around them. The potion's main ingredients are the heart of a Dream-Eating Black Crow and a captured Shadow of Nightmares, supplemented by spirit-world moon water drawn from the crimson moon, a Dream-Eating Crow phantom feather, and pages recording one of the Beyonder's own recent nightmares. The advancement ritual requires invading and mastering the nightmare of a sleeping Beyonder, twisting it to one's own shaping and withdrawing before the dreamer wakes. The acting method has the Nightmare walk the dreams of others, conceal every trace of their passage, and master their own nightmares before wielding those of others.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: ["darkness-pathway", "nightmare", "dreams", "mid-sequence", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "darkness-seq6-soul-assurer",
    title: "Darkness Pathway — Sequence 6: Soul Assurer",
    category: "pathway",
    content: `The Soul Assurer turns the Darkness pathway toward the souls of the dead and the restless. Its signature is the Requiem, a song that soothes troubled spirits and lays them to rest; the Soul Assurer can pacify, calm, and provide refuge to wandering or agitated spirits, and inversely can perform Agitating, stirring a spirit into frenzy or torment when needed. Their spirituality is greatly heightened, sharpening their ritual sensitivity and perception. The potion's main ingredients are the spirit-body crystal of a Rotting Shepherd and the skull of an Otherworldly Deep Sleeper, supplemented by blessed holy water, Rotting Shepherd pus, soil mingled with the Deep Sleeper's shadow, and Deep Sleep Flower powder. The advancement ritual requires laying to rest a powerful, anguished spirit that resists all comfort, offering it refuge within the dark without being dragged into its anguish. The acting method asks the Soul Assurer to tend the dead and the dreaming, to work unseen in silence and concealment, and to hold to serenity so the torment of spirits never becomes their own.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: ["darkness-pathway", "soul-assurer", "spirits", "requiem", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "darkness-seq5-spirit-warlock",
    title: "Darkness Pathway — Sequence 5: Spirit Warlock",
    category: "pathway",
    content: `The Spirit Warlock is the apex of mid-sequence power in the Darkness pathway, a commander of spirits and the night. Spirit Commanding lets them summon, bind, and command a host of spirits and spirit-world creatures to fight and serve; they wield Dream Invasion with far greater reach than a Nightmare, can project their own spirit body to act apart from their flesh, and command near-total dominion over darkness and the spirit world after nightfall. The potion's main ingredients are a portion of the Source of Mad Dreams and a Spirit Nest, supplemented by Source-of-Mad-Dreams blood, gas vented from the Spirit Nest, a soul on the verge of dispersing, and a milk tooth that fell out under a full moon. The advancement ritual is among the strangest of the pathway: the Spirit Warlock must find a way to enter the spirit world in the flesh rather than as a spirit, locate and merge with their own key information mirrored there, and consume the potion at the moment of reunion. The acting method has them marshal and command spirits as a warlock of the dark, operate from concealment rather than acting openly, and guard their own soul against the spirits they bind.`,
    pathway: "darkness",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "darkness-pathway",
      "spirit-warlock",
      "spirits",
      "mid-sequence-apex",
      "acting-method",
    ],
    tokenCount: 270,
  },
];
