import type { LoreEntry } from "./types";

export const DEATH_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "death-pathway-overview",
    title: "Death Pathway — Overview",
    category: "pathway",
    content: `The Death pathway belongs to the Eternal Darkness group, anchored to the River of Eternal Darkness. It is the pathway of spirits, undead, and the boundary between life and death — progressing from speaking with the dead at low sequences to commanding legions of undead and achieving a form of immortality at higher levels. The Death pathway's neighboring pathways within the Eternal Darkness group are the Darkness (Sleepless) pathway and the Twilight Giant pathway. In the Fifth Epoch, the Death pathway has no single orthodox church controlling it. The Church of the Evernight Goddess possesses knowledge of the Death pathway through its connection to night and death, and some Nighthawk team members follow the Death pathway. The Southern Continent holds many Death pathway secrets. The Death pathway is the darkest and most macabre of the four MVP pathways, dealing directly with corpses, spirits, and the death realm. Its practitioners serve as mediators between the living and the dead. The pathway's abilities are particularly effective against undead threats and in investigations involving murder victims, making Death pathway Beyonders valuable specialists. Daly Simone and Azik Eggers represent different expressions of this pathway in the Tingen narrative.`,
    pathway: "death",
    epoch: 5,
    npcs: ["Daly Simone", "Azik Eggers"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "death-pathway",
      "eternal-darkness-group",
      "river-of-eternal-darkness",
      "overview",
    ],
    tokenCount: 255,
  },
  {
    slug: "death-seq9-corpse-collector",
    title: "Death Pathway — Sequence 9: Corpse Collector",
    category: "pathway",
    content: `The Corpse Collector is the entry point of the Death pathway, granting abilities centered on interaction with the dead. A Corpse Collector gains Corpse Communication — the ability to speak with recently deceased individuals and learn their final moments, making them invaluable for murder investigations and recovering information from the dead. Death Sense provides passive detection of death, undead, and lingering spirits in the vicinity, acting as an early warning system in haunted locations. Preserve Remains allows slowing or halting decomposition through spiritual means, useful for preserving evidence or maintaining bodies for later communication. The potion requires Corpse Grass and Black-faced Vulture Oil. The acting method requires treating the dead with respect, performing proper burial rites, spending time among graves without fear, and cataloging remains encountered. The Corpse Collector's acting method is psychologically challenging in a different way from other pathways: it demands comfort with death and corpses, requiring the practitioner to overcome natural human revulsion. Those who succeed develop a respectful, professional relationship with death itself. No advancement ritual is required — the potion is digested through consistent acting. The Corpse Collector is a support and investigation specialist, better suited to forensic work than combat.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: [
      "death-pathway",
      "corpse-collector",
      "forensic",
      "spirit-communication",
      "acting-method",
    ],
    tokenCount: 260,
  },
  {
    slug: "death-seq8-gravedigger",
    title: "Death Pathway — Sequence 8: Gravedigger",
    category: "pathway",
    content: `The Gravedigger sequence advances the Corpse Collector's connection to death into active combat capability. A Gravedigger gains Undead Command — the ability to raise and command a small number of basic undead such as skeletons and zombies, making them the only low-sequence Beyonder among the four MVP pathways who can create minions. Bone Weapon allows shaping bones into supernatural weapons, providing melee combat tools enhanced with death energy. Death's Endurance reduces the need for sleep and food while granting resistance to cold and disease — the Gravedigger's body begins its slow transition away from normal human biology. The potion requires a Zombie Heart and Graveyard Soil. The advancement ritual requires putting a restless undead to permanent rest through a rite of final rest at the undead's original grave. The acting method demands digging graves and burying the dead as community service, studying the nature of death and undeath, and protecting burial sites from desecration. The Gravedigger sequence introduces the Death pathway's dual nature: the practitioner both commands and respects the dead. The ability to raise undead is not about domination but stewardship — the Gravedigger maintains order in the boundary between life and death. This sequence's combat abilities are modest but unique, establishing the Death pathway's role as the "summoner" among MVP pathways.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: [
      "death-pathway",
      "gravedigger",
      "undead-command",
      "bone-weapons",
      "acting-method",
    ],
    tokenCount: 275,
  },
  {
    slug: "death-seq7-spirit-medium",
    title: "Death Pathway — Sequence 7: Spirit Medium",
    category: "pathway",
    content: `The Spirit Medium marks the Death pathway's entry into mid-sequence power, focusing on the boundary between the living and the dead. A Spirit Medium gains Spirit Channeling — the ability to allow a spirit to temporarily inhabit their body to communicate, a dangerous ability that risks losing oneself if the spirit is too powerful. Ghost Walk enables becoming partially incorporeal for short periods, passing through solid objects for infiltration or escape. Death Domain Awareness provides wide-area sensing of disturbances in the life-death boundary. Spirit Binding allows anchoring a willing or weakened spirit to an object or location, creating wards or sentinels. The potion requires a Wraith Crystal, Spirit World Incense, and Tears of the Bereaved. The advancement ritual requires channeling a powerful spirit (at least Sequence 8) through the body without losing control and delivering its final message. The acting method demands regular communion with spirits, mediating between living and dead, and never abusing spirits' trust. Daly Simone exemplifies the Spirit Medium's role on the Tingen Nighthawks: she channels murder victims to gather evidence, senses undead presences during investigations, and serves as the team's specialist for ghost-related incidents. The Spirit Medium's psychological burden is heavy — they regularly experience the grief, trauma, and confusion of the dead firsthand through channeling.`,
    pathway: "death",
    epoch: 5,
    npcs: ["Daly Simone"],
    sequences: [7],
    tags: ["death-pathway", "spirit-medium", "channeling", "ghost-walk", "mid-sequence"],
    tokenCount: 280,
  },
  {
    slug: "death-seq6-spirit-guide",
    title: "Death Pathway — Sequence 6: Spirit Guide",
    category: "pathway",
    content: `The Spirit Guide sequence is the most transformative in the Death pathway's low-to-mid arc: the practitioner crosses a threshold from which there is no return, becoming a being that straddles life and death rather than merely mediating between them. The Spirit Guide's most feared ability is the Gaze of Death — any living being who makes direct eye contact risks instant death; even entities of godlike power suffer devastating damage from the exchange. Beyond the gaze, the Spirit Guide emits a passive Withering effect: targets within line of sight begin to wither slowly even without direct eye contact, as though crossing the River of Death inch by inch. The Spirit Guide's body is also nearly invulnerable to conventional attack — physical and supernatural force alike bounce off one who already belongs to death. Only purification effects from pathways like the Sun remain genuinely dangerous. A more nuanced ability is the Touch of Death and Life: touching a living being with the left hand inflicts near-irreversible death; a subsequent touch with the right hand reverses the condition and restores life. The potion requires a Shadow of Death and the Soul Essence of a Pale Lich. The acting method demands that the Spirit Guide walk among the living with eyes controlled — the death energy in the gaze must not kill indiscriminately. They must guide every soul that approaches them seeking passage. The advancement ritual requires confronting the full weight of the transformation and demonstrating mastery of the Touch of Death and Life.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: [
      "death-pathway",
      "spirit-guide",
      "gaze-of-death",
      "death-immunity",
      "touch-of-death",
    ],
    tokenCount: 285,
  },
  {
    slug: "death-seq5-gatekeeper",
    title: "Death Pathway — Sequence 5: Gatekeeper",
    category: "pathway",
    content: `The Gatekeeper is the apex of mid-sequence power in the Death pathway, and represents the most dramatic transformation yet: the practitioner does not merely walk the boundary between life and death — they become it. A Gatekeeper gains the Door to the Underworld ability: they can sense the entrance to the Underworld, control the undead within it, and solidify the door as a brand in the palm of their hand. They can summon this door at critical moments to drag targets behind it — a combat ability with no conventional defence. Their most unique power is the Internal Underworld: the Gatekeeper's own body becomes a cage that houses souls, deceased spirits, and natural spirits within an inner death realm accessible through an entrance at the centre of their brow. This allows a Gatekeeper to carry an entire undead army within themselves, deploying it through the Internal Underworld gate wherever they travel without drawing outward attention. Underworld Sense provides comprehensive awareness of all disturbances across a vast area of the death domain. The potion requires the Skull of an Underworld Wanderer and the Crystal Core of a Myriad-Armed Wraith. The advancement ritual requires opening the Internal Underworld gate within their own body for the first time and housing at least three bound souls within it. The acting method demands guarding the boundary as a sacred responsibility, maintaining order among the dead within the Internal Underworld, and never permitting unauthorized passage through the gate the practitioner now embodies. The Gatekeeper sequence is the point at which the Death pathway practitioner stops being a visitor to the realm of the dead and becomes one of its fundamental institutions.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "death-pathway",
      "gatekeeper",
      "internal-underworld",
      "door-to-underworld",
      "mid-sequence-apex",
    ],
    tokenCount: 295,
  },
];
