import type { LoreEntry } from "./types";

export const DEATH_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "death-pathway-overview",
    title: "Death Pathway — Overview",
    category: "pathway",
    content: `The Death pathway belongs to the Eternal Darkness group, anchored to the River of Eternal Darkness. It is the pathway of spirits, undead, and the boundary between life and death — progressing from speaking with the dead at low sequences to commanding legions of undead and achieving a form of immortality at higher levels. The Death pathway's neighboring pathways within the Eternal Darkness group are the Darkness (Sleepless) pathway and the Twilight Giant pathway. In the Fifth Epoch, the Death pathway has no single orthodox church controlling it. The Church of the Evernight Goddess possesses knowledge of the Death pathway through its connection to night and death, and some Nighthawk team members follow the Death pathway. The Southern Continent holds many Death pathway secrets. The Death pathway is the darkest and most macabre of the four MVP pathways, dealing directly with corpses, spirits, and the death realm. Its practitioners serve as mediators between the living and the dead. The pathway's abilities are particularly effective against undead threats and in investigations involving murder victims, making Death pathway Beyonders valuable specialists. Daly Simone and Azik Eggers represent different expressions of this pathway in the Tingen narrative.`,
    pathway: "death",
    epoch: 5,
    npcs: ["Daly Simone", "Azik Eggers"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "death-pathway",
      "eternal-darkness-group",
      "river-of-eternal-darkness",
      "overview",
    ],
    tokenCount: 255,
  },
  {
    slug: "death-seq9-corpse-collector",
    title: "Death Pathway — Sequence 9: Corpse Collector",
    category: "pathway",
    content: `The Corpse Collector is the entry point of the Death pathway, granting abilities centered on interaction with the dead. A Corpse Collector gains Corpse Communication — the ability to speak with recently deceased individuals and learn their final moments, making them invaluable for murder investigations and recovering information from the dead. Death Sense provides passive detection of death, undead, and lingering spirits in the vicinity, acting as an early warning system in haunted locations. Preserve Remains allows slowing or halting decomposition through spiritual means, useful for preserving evidence or maintaining bodies for later communication. The potion requires Corpse Grass and Black-faced Vulture Oil. The acting method requires treating the dead with respect, performing proper burial rites, spending time among graves without fear, and cataloging remains encountered. The Corpse Collector's acting method is psychologically challenging in a different way from other pathways: it demands comfort with death and corpses, requiring the practitioner to overcome natural human revulsion. Those who succeed develop a respectful, professional relationship with death itself. No advancement ritual is required — the potion is digested through consistent acting. The Corpse Collector is a support and investigation specialist, better suited to forensic work than combat.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: [
      "death-pathway",
      "corpse-collector",
      "forensic",
      "spirit-communication",
      "acting-method",
    ],
    tokenCount: 260,
  },
  {
    slug: "death-seq8-gravedigger",
    title: "Death Pathway — Sequence 8: Gravedigger",
    category: "pathway",
    content: `The Gravedigger sequence advances the Corpse Collector's connection to death into active combat capability. A Gravedigger gains Undead Command — the ability to raise and command a small number of basic undead such as skeletons and zombies, making them the only low-sequence Beyonder among the four MVP pathways who can create minions. Bone Weapon allows shaping bones into supernatural weapons, providing melee combat tools enhanced with death energy. Death's Endurance reduces the need for sleep and food while granting resistance to cold and disease — the Gravedigger's body begins its slow transition away from normal human biology. The potion requires a Zombie Heart and Graveyard Soil. The advancement ritual requires putting a restless undead to permanent rest through a rite of final rest at the undead's original grave. The acting method demands digging graves and burying the dead as community service, studying the nature of death and undeath, and protecting burial sites from desecration. The Gravedigger sequence introduces the Death pathway's dual nature: the practitioner both commands and respects the dead. The ability to raise undead is not about domination but stewardship — the Gravedigger maintains order in the boundary between life and death. This sequence's combat abilities are modest but unique, establishing the Death pathway's role as the "summoner" among MVP pathways.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: [
      "death-pathway",
      "gravedigger",
      "undead-command",
      "bone-weapons",
      "acting-method",
    ],
    tokenCount: 275,
  },
  {
    slug: "death-seq7-spirit-medium",
    title: "Death Pathway — Sequence 7: Spirit Medium",
    category: "pathway",
    content: `The Spirit Medium marks the Death pathway's entry into mid-sequence power, focusing on the boundary between the living and the dead. A Spirit Medium gains Spirit Channeling — the ability to allow a spirit to temporarily inhabit their body to communicate, a dangerous ability that risks losing oneself if the spirit is too powerful. Ghost Walk enables becoming partially incorporeal for short periods, passing through solid objects for infiltration or escape. Death Domain Awareness provides wide-area sensing of disturbances in the life-death boundary. Spirit Binding allows anchoring a willing or weakened spirit to an object or location, creating wards or sentinels. The potion requires a Wraith Crystal, Spirit World Incense, and Tears of the Bereaved. The advancement ritual requires channeling a powerful spirit (at least Sequence 8) through the body without losing control and delivering its final message. The acting method demands regular communion with spirits, mediating between living and dead, and never abusing spirits' trust. Daly Simone exemplifies the Spirit Medium's role on the Tingen Nighthawks: she channels murder victims to gather evidence, senses undead presences during investigations, and serves as the team's specialist for ghost-related incidents. The Spirit Medium's psychological burden is heavy — they regularly experience the grief, trauma, and confusion of the dead firsthand through channeling.`,
    pathway: "death",
    epoch: 5,
    npcs: ["Daly Simone"],
    sequences: [7],
    tags: ["death-pathway", "spirit-medium", "channeling", "ghost-walk", "mid-sequence"],
    tokenCount: 280,
  },
  {
    slug: "death-seq6-spirit-guide",
    title: "Death Pathway — Sequence 6: Spirit Guide",
    category: "pathway",
    content: `The Spirit Guide sequence grants the Death pathway's ability to cross between the realms of the living and the dead. A Spirit Guide gains Death Gate — the ability to open a temporary passage to the death realm, a vast, terrifying dimension where spirits wander and powerful death-related entities dwell. Soul Harvest allows extracting the soul of a recently deceased being before it dissipates, preserving it for communication, protection, or other purposes. Deathly Resilience enables surviving injuries that would kill ordinary beings and dramatically slows aging. Spirit Army allows commanding a small host of bound spirits in combat. The potion requires a Heart of a Death Elemental, a Veil Fragment, and Ancient Funeral Ash. The advancement ritual requires entering the death realm through a Death Gate, locating a specific lost soul, and guiding it to its final rest. The acting method demands guiding lost souls regularly, walking the boundary between life and death, and treating death as a domain to steward rather than fear. The Spirit Guide represents a fundamental shift in the Death pathway practitioner's relationship with death: they are no longer visitors to death's domain but residents of it, moving freely between the living and dead worlds. The Spirit Army ability transforms the practitioner into a commander of ghostly forces.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: ["death-pathway", "spirit-guide", "death-realm", "soul-harvest", "spirit-army"],
    tokenCount: 275,
  },
  {
    slug: "death-seq5-undying",
    title: "Death Pathway — Sequence 5: Undying",
    category: "pathway",
    content: `The Undying is the apex of mid-sequence power in the Death pathway, granting a form of pseudo-immortality and supreme command over the undead. An Undying gains Resurrection — the passive ability to revive from death once, their body reforming over time from accumulated death energy. This makes the Undying the only MVP pathway Beyonder with a built-in second chance at life. Death's Embrace allows inflicting severe necrotic damage through touch, the damage resisting conventional healing. Undead Legion enables raising and commanding a large force of powerful undead — far exceeding the Gravedigger's modest skeletons. Deathless Form causes the body to exist partially in the death realm, rendering the practitioner immune to most physical damage. The potion requires a Beyonder Characteristic of a Spirit Guide, a Lich Bone Fragment, and Essence of the Death Realm. The advancement ritual is the most dramatic among the four MVP pathways: the practitioner must truly die and then reconstitute themselves through death energy and force of will. The acting method demands embracing the duality of life and death, maintaining dominion over a territory where the dead outnumber the living, and accepting death as something to transcend rather than fear. The Undying represents the Death pathway's ultimate promise: mastery over death itself, beginning the practitioner's transformation from a mortal who studies death into a being who has conquered it.`,
    pathway: "death",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "death-pathway",
      "undying",
      "resurrection",
      "undead-legion",
      "mid-sequence-apex",
    ],
    tokenCount: 290,
  },
];
