import type { LoreEntry } from "./types";

export const FOOL_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "fool-pathway-overview",
    title: "Fool Pathway — Overview",
    category: "pathway",
    content: `The Fool pathway belongs to the Mysteries group, anchored to the Sefirah Castle. It is one of the most versatile and deceptive pathways, progressing from perception and divination at low sequences to reality manipulation and cosmic authority at high sequences. The pathway's neighboring pathways are Error (Marauder) and Door (Apprentice), all sharing themes of fate, deception, and hidden knowledge. The Fool pathway is unique in that its Sequence 0 position — "The Fool" — is the Lord of Mysteries, one of the three Pillars of the universe. This makes it one of the most powerful and consequential pathways in existence. In the Fifth Epoch, the Fool pathway has no single orthodox church controlling it; its sequences are scattered among various organizations and individuals, making it rare and difficult to advance. The Church of the Evernight Goddess possesses some related knowledge through the neighboring Darkness pathway but does not directly control Fool pathway resources. Klein Moretti's choice of this pathway, initially accidental, sets him on a collision course with the highest powers in the universe.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [9, 8, 7, 6, 5],
    tags: ["fool-pathway", "mysteries-group", "sefirah-castle", "overview"],
    tokenCount: 240,
  },
  {
    slug: "fool-seq9-seer",
    title: "Fool Pathway — Sequence 9: Seer",
    category: "pathway",
    content: `The Seer is the entry point of the Fool pathway, granting abilities centered on perception of the supernatural world. A Seer gains Spirit Vision — the ability to see the spirit world overlaid on physical reality, perceiving lingering spiritual traces, emotional auras, and supernatural entities invisible to normal sight. They can perform divination using mediums such as tarot cards, pendulums, crystal balls, or dream interpretation, receiving limited but often cryptic answers about past events or near-future possibilities. Spiritual Intuition provides a passive danger sense, alerting the Seer to anomalies and threats. The potion formula requires Dragon Blood Grass, Night Vale Flower, and Stellar Aqua Crystal. The acting method for a Seer demands speaking and acting with mystery and reserve, observing more than revealing, and avoiding proactive divination without proper ritual preparation. Klein Moretti exemplifies the Seer's role: his early Nighthawk investigations rely heavily on divination rituals performed above the gray fog of Sefirah Castle, and his deliberate air of mysteriousness at the Divination Club helps him digest the potion. The Seer sequence has no advancement ritual — digesting the potion through acting is sufficient for progressing to Sequence 8.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [9],
    tags: ["fool-pathway", "seer", "divination", "spirit-vision", "acting-method"],
    tokenCount: 260,
  },
  {
    slug: "fool-seq8-clown",
    title: "Fool Pathway — Sequence 8: Clown",
    category: "pathway",
    content: `The Clown sequence builds on the Seer's perceptive abilities with physical enhancement and performance-based powers. A Clown gains supernatural agility and acrobatic ability, making them nimble fighters. They can perform Distraction — using sleight of hand and misdirection enhanced by spiritual energy to redirect attention. Flame Manipulation allows control of small flames, useful for both performance and combat. Paper Figurine Substitution enables escape from danger by leaving a paper decoy in the Clown's place. The potion requires a Manhal Fish Eyeball and Dream Honeydew. The advancement ritual requires performing before a live audience while channeling spiritual power. The acting method is emotionally challenging: a Clown must perform for audiences and make others laugh or feel joy, while never revealing their true emotions. This duality of outward cheerfulness concealing inner turmoil defines the sequence. Klein struggles with this acting requirement, as he must maintain a facade of humor and showmanship while dealing with genuine grief and danger. The Clown sequence's abilities make it effective for investigation work — misdirection, agility, and flame control provide both combat utility and infiltration tools. The Clown is where the Fool pathway begins to reveal its core theme: the separation between appearance and reality.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [8],
    tags: ["fool-pathway", "clown", "performance", "agility", "acting-method"],
    tokenCount: 270,
  },
  {
    slug: "fool-seq7-magician",
    title: "Fool Pathway — Sequence 7: Magician",
    category: "pathway",
    content: `The Magician represents the Fool pathway's entry into mid-sequence power. Magicians gain Damage Transfer — the ability to redirect damage from themselves onto a connected object or person, making them deceptively durable in combat. They can create mystical Seals to bind or contain supernatural entities. Item Affinity enhances their interaction with enchanted objects, and Conjuring allows summoning small objects from hidden spaces. The potion requires a Thousand-faced Hunter Eye Crystal, Rosemary Essential Oil, and Ghost Shark Blood. The advancement ritual involves drawing a ritual circle, reciting the Magician invocation at midnight, and sealing a minor supernatural entity. The acting method requires daily practice of magic tricks and illusions, always carrying props and mystical tools, and maintaining showmanship in all interactions. At Sequence 7, the Fool pathway begins to demonstrate its theme of control through deception — the Magician doesn't overpower opponents directly but redirects damage, seals threats, and manipulates the battlefield through misdirection. This sequence is also where Beyonders begin facing the "initial onset of madness" common to mid-sequence advancement, requiring stronger mental discipline to maintain identity.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [7],
    tags: ["fool-pathway", "magician", "mid-sequence", "damage-transfer", "sealing"],
    tokenCount: 260,
  },
  {
    slug: "fool-seq6-faceless",
    title: "Fool Pathway — Sequence 6: Faceless",
    category: "pathway",
    content: `The Faceless sequence grants the Fool pathway's signature identity manipulation abilities. A Faceless can completely transform their appearance, voice, and physique to perfectly imitate another person through Shapeshifting. Identity Theft allows temporary absorption of a touched target's surface memories and mannerisms, enabling convincing impersonation. Body Malleability lets them reshape their body to squeeze through gaps or resist physical impacts. The potion requires a Thousand-faced Hunter Mutant Pituitary Gland, Hound of Fulgrim Saliva, and Three Petals of Spirit World Celandine. The advancement ritual demands assuming a false identity and maintaining it through a crisis without breaking character. The acting method is perhaps the most psychologically demanding thus far: the Faceless must adopt a new identity for at least one full day each week, live convincingly as someone else, and never grow too attached to a single identity. This creates a genuine risk of identity dissolution — the Beyonder must constantly ask "who am I really?" while pretending to be others. Klein uses the Faceless abilities extensively in Backlund, adopting personas like detective Sherlock Moriarty. The Faceless sequence embodies the pathway's philosophical core: identity is a performance, and the self is the ultimate illusion.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [6],
    tags: ["fool-pathway", "faceless", "identity", "shapeshifting", "acting-method"],
    tokenCount: 275,
  },
  {
    slug: "fool-seq5-marionettist",
    title: "Fool Pathway — Sequence 5: Marionettist",
    category: "pathway",
    content: `The Marionettist is the apex of mid-sequence power in the Fool pathway, granting abilities centered on control and manipulation of others. Marionette Control allows taking direct control of a living person's body, turning them into a puppet. Thread Manipulation creates invisible spiritual threads to manipulate objects and people at range. Grafting enables absorbing abilities from defeated Beyonders onto the Marionettist or their marionettes, creating an ever-expanding repertoire of stolen powers. Enhanced Spiritual Perception greatly improves detection of spiritual fluctuations. The potion requires a Beyonder Characteristic of a Faceless, a Mind Dragon Tendon, and a Psychic Puppet Core. The advancement ritual requires overpowering a Beyonder's will and converting them into a marionette through spiritual domination. The acting method demands controlling at least one marionette at all times, directing events from behind the scenes, and treating every interaction as a stage. Klein's advancement to Marionettist transforms his combat effectiveness — he begins collecting powerful marionettes, effectively fielding a small army of stolen Beyonder abilities. The Marionettist sequence crystallizes the Fool pathway's ultimate theme: the world is a stage, and the Fool pulls the strings from behind the curtain. At this level, the Beyonder transitions from performer to director.`,
    pathway: "fool",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [5],
    tags: ["fool-pathway", "marionettist", "puppeteer", "control", "mid-sequence-apex"],
    tokenCount: 280,
  },
];
