import type { LoreEntry } from "./types";

export const TYRANT_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "tyrant-pathway-overview",
    title: "Tyrant Pathway — Overview",
    category: "pathway",
    content: `The Tyrant pathway belongs to the God Almighty group, anchored to the Chaos Sea — the same Above-the-Sequence group as the Visionary, Sun, and Hanged Man pathways. It specialises in water and weather: a Tyrant Beyonder can cast powerful water, wind, and electricity spells, gains strength in water, can sing to disable opponents, glide on the air, act underwater for long periods, and grows enraged to amplify their power. They are famously bad-tempered and quick to bristle at high-handed authority. At high sequences they command sea creatures, walk the ocean freely, raise earthquakes, travel at tremendous speed, and produce electrical power to rival a star — the pathway is described as omnipotent across sea, land, and air. Its mythical-creature form is a gigantic octopus-like being wreathed in silver-white lightning, and its symbol is the Windstorm; the pathway's colour is dark blue. Tyrant Beyonders often manifest blue hair, a trait that can pass to their descendants. In the orthodoxy of the Fifth Epoch the Church of the Lord of Storms — whose Mandated Punishers operate in Tingen City — holds and guards the Tyrant pathway.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [9, 8, 7, 6, 5],
    tags: ["tyrant-pathway", "god-almighty-group", "chaos-sea", "storm", "overview"],
    tokenCount: 240,
  },
  {
    slug: "tyrant-seq9-sailor",
    title: "Tyrant Pathway — Sequence 9: Sailor",
    category: "pathway",
    content: `The Sailor is the entry point of the Tyrant pathway, a creature of the water before it is a creature of the storm. A Sailor possesses Aquatic Affinity — submerging and moving underwater with the ease of a sea creature, holding their breath for many minutes and diving deep without equipment — and Phantom Scales, illusory scales hidden beneath the skin that make them slippery and hard to grasp. Their Balance is exceptional, keeping perfect footing on a deck in a rainstorm as though on solid ground, and their bodily strength is markedly enhanced. The potion's main ingredients are the heart of a storm petrel and the blood of a Deep-Sea Lvoque Fish, supplemented by sea-salt crystals, brineweed extract, and strong liquor. The acting method asks the Sailor to live by sea and storm — to sail, swim, and brave rough water, to give vent to their temper rather than swallow their anger, and to test themselves against wind and wave at every chance. As a Sequence 9 sequence it has no advancement ritual; acting digests the potion before advancing to Folk of Rage.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: ["tyrant-pathway", "sailor", "sea", "wrath", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "tyrant-seq8-folk-of-rage",
    title: "Tyrant Pathway — Sequence 8: Folk of Rage",
    category: "pathway",
    content: `The Folk of Rage — also styled Guardian of the Storm — channels anger itself into power. Its defining ability is Wrath: the angrier a Folk of Rage grows, the stronger they become, and they can unleash a Raging Blow of overwhelming, wrath-fuelled force. Their toughness and endurance are greatly enhanced, especially amid wind and rain. The potion's main ingredients are the blood of a Furious Sea-Ape and a fragment of thunder-charged coral, supplemented by foam skimmed from a storm tide, Sea-Ape hair, and strong liquor. The advancement ritual demands mastering one's wrath in a true storm — standing alone against raging wind or sea, letting fury rise to its peak and channelling it into a single working without breaking or losing control. The acting method has the Folk of Rage let their anger run free, meet provocation with the storm's fury, stand against the powerful and bow to no high-handed authority, and throw themselves into the heart of wind, rain, and rough sea. The Tyrant pathway's bad temper is not merely flavour here — it is the engine of the sequence's strength.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["tyrant-pathway", "folk-of-rage", "wrath", "storm", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "tyrant-seq7-seafarer",
    title: "Tyrant Pathway — Sequence 7: Seafarer",
    category: "pathway",
    content: `The Seafarer — also called the Storm Priest — carries the Tyrant pathway into the mid sequences with mastery of the open sea. A Seafarer can perform unerring Navigation, finding their bearings and reading wind, current, and weather, and possesses a Weather Sense that warns of oncoming storms and squalls before they arrive. Their memory and mental acuity are sharply heightened, and they draw strength and recovery from contact with the open sea. The potion's main ingredients are the pituitary gland of a Storm-Whale and the spinal fluid of a Tempest Sea-Serpent, supplemented by Compass-Rose Coral powder, deep-sea pearl dust, and aged rum. The advancement ritual requires crossing a deadly stretch of storm-wracked sea — waters known to wreck ships, in the teeth of a storm — relying solely on one's own senses and command of the sea. The acting method asks the Seafarer to sail the open sea and command the respect of those who travel it, to pit themselves against storm and tide as a master of the waters, and to carry the bearing of one born to wind and weather.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: ["tyrant-pathway", "seafarer", "sea", "navigation", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "tyrant-seq6-wind-blessed",
    title: "Tyrant Pathway — Sequence 6: Wind-blessed",
    category: "pathway",
    content: `The Wind-blessed takes the Tyrant pathway into the sky. A Wind-blessed can perform Wind Manipulation — summoning and commanding gusts, gales, and cutting wind-blades — and achieves Flight, riding the wind to glide and soar. Their Wind-blades loose compressed air sharp enough to cut through armour and stone, and they begin to exert real Water Control alongside their command of the wind. The potion's main ingredients are the wing bone of a Gale-Roc and the crystallised heart of a living cyclone-spirit, supplemented by vapour drawn from a thunderhead, Gale-Roc feathers, and salt powder gathered from high mountain storms. The advancement ritual requires riding a great storm to its heart and bending its winds to one's will, descending in command of the gale rather than scattered by it. The acting method has the Wind-blessed take to the skies and storm winds as their true element, wield wind and water with a free and untrammelled temper, and answer slights with the swift fury of a gale.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: ["tyrant-pathway", "wind-blessed", "wind", "flight", "acting-method"],
    tokenCount: 240,
  },
  {
    slug: "tyrant-seq5-ocean-songster",
    title: "Tyrant Pathway — Sequence 5: Ocean Songster",
    category: "pathway",
    content: `The Ocean Songster is the apex of mid-sequence power in the Tyrant pathway, master of wind, water, and the storm's lightning. The sequence's signature is Lightning Manipulation — calling down and hurling bolts, lightning arrows, and shattering strikes — and the Lightning Strike, concentrating the storm's charge into a single devastating discharge. They can sing songs of the sea that disable, command, or bewitch those who hear, and command wind, water, and lightning together as a near-absolute sovereign of weather. The potion's main ingredients are the vocal cords of a Thunder-Leviathan and the storm-charged core of a slain Sea-Tyrant, supplemented by Thunder-Leviathan blood, fulgurite sand fused by a sea-storm's lightning, and a siren-song pearl. The advancement ritual requires raising and commanding a storm at sea by song alone, binding its wind, wave, and lightning to one's voice, then dispersing it at a word. The acting method has the Ocean Songster reign over sea, sky, and storm as their singer and sovereign, sing the songs of the deep, and brook no defiance — answering challenge with thunder.`,
    pathway: "tyrant",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "tyrant-pathway",
      "ocean-songster",
      "lightning",
      "mid-sequence-apex",
      "acting-method",
    ],
    tokenCount: 260,
  },
];
