import type { LoreEntry } from "./types";

export const VISIONARY_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "visionary-pathway-overview",
    title: "Visionary Pathway — Overview",
    category: "pathway",
    content: `The Visionary pathway belongs to the God Almighty group, anchored to the Chaos Sea. It is the pathway of the mind — progressing from emotional perception at low sequences to reality-shaping imagination at the highest levels. The pathway's neighboring pathway is the Sun pathway, and both share the God Almighty group with the Tyrant, White Tower, and Hanged Man pathways. The Visionary pathway's Sequence 0 position is one of the thrones of God Almighty, making it cosmically significant. In the Fifth Epoch, the Psychology Alchemists serve as the primary non-church organization for the Visionary pathway, though they are secretly controlled by the Twilight Hermit Order. The Church of the God of Knowledge and Wisdom also possesses related knowledge. The Visionary pathway is particularly suited to investigation, social manipulation, and support roles. Its practitioners excel at reading people, healing psychological trauma, and eventually reshaping reality through pure imagination. Audrey Hall, "Justice" of the Tarot Club, is the narrative's primary Visionary pathway Beyonder, advancing from Spectator through multiple sequences while navigating the Psychology Alchemists' hidden corruption.`,
    pathway: "visionary",
    epoch: 5,
    npcs: ["Audrey Hall"],
    sequences: [9, 8, 7, 6, 5],
    tags: ["visionary-pathway", "god-almighty-group", "chaos-sea", "overview"],
    tokenCount: 245,
  },
  {
    slug: "visionary-seq9-spectator",
    title: "Visionary Pathway — Sequence 9: Spectator",
    category: "pathway",
    content: `The Spectator is the entry point of the Visionary pathway, granting abilities focused on observation and emotional perception. A Spectator gains Emotion Reading — the ability to read micro-expressions, body language, and subtle physiological cues to detect lies, hidden emotions, and psychological states with preternatural accuracy. Psychological Analysis allows rapid assessment of a person's motivations, fears, and mental vulnerabilities. Enhanced Perception heightens awareness of subtle social and environmental cues that ordinary people miss. The potion requires the Placenta of a Beyond-level Demon Cat and Tears of a Willow Sprite. The acting method requires observing people and social dynamics without interfering, recording observations in a journal, and analyzing motivations before taking action. The Spectator must be a watcher, not a participant. Audrey Hall demonstrates this sequence's potential: as a high-society noblewoman, she uses her Spectator abilities to navigate the complex social politics of Backlund's aristocracy, reading the true intentions behind polite conversation and diplomatic posturing. The Spectator sequence has no advancement ritual — acting is sufficient. This sequence is ideal for characters who favor investigation and social interaction over combat.`,
    pathway: "visionary",
    epoch: 5,
    npcs: ["Audrey Hall"],
    sequences: [9],
    tags: [
      "visionary-pathway",
      "spectator",
      "observation",
      "emotion-reading",
      "acting-method",
    ],
    tokenCount: 255,
  },
  {
    slug: "visionary-seq8-telepathist",
    title: "Visionary Pathway — Sequence 8: Telepathist",
    category: "pathway",
    content: `The Telepathist sequence advances the Spectator's passive observation into active mental communication and influence. A Telepathist gains Telepathy — the ability to read surface thoughts and send mental messages, enabling silent communication and basic mind-reading. Mental Shield constructs a psychic barrier protecting against mental intrusion from other Beyonders. Empathic Influence allows subtly shifting a nearby target's emotional state without their awareness. The potion requires Mirror Hedgehog Spinal Fluid and Piper Fruit. The advancement ritual requires establishing a sustained two-way telepathic link with another Beyonder for one full hour and transmitting a complex memory through it. The acting method emphasizes practicing telepathic communication daily, respecting mental boundaries, and meditating to strengthen psychic fortitude. The Telepathist represents the Visionary pathway's transition from observer to participant: where the Spectator merely watches, the Telepathist begins to touch minds. This sequence introduces the pathway's core ethical tension — the ability to read thoughts creates constant temptation to invade privacy, and the acting method's emphasis on respecting boundaries reflects the danger of losing one's moral compass when others' thoughts become accessible.`,
    pathway: "visionary",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: [
      "visionary-pathway",
      "telepathist",
      "telepathy",
      "mental-shield",
      "acting-method",
    ],
    tokenCount: 260,
  },
  {
    slug: "visionary-seq7-psychiatrist",
    title: "Visionary Pathway — Sequence 7: Psychiatrist",
    category: "pathway",
    content: `The Psychiatrist sequence marks the Visionary pathway's entry into mid-sequence power, focusing on deep mental manipulation and healing. A Psychiatrist gains Deep Mental Probe — the ability to dive into a subject's subconscious and uncover hidden or suppressed memories. Psychological Healing allows repairing trauma and mental afflictions through psychic therapy, making Psychiatrists invaluable for treating Beyonders suffering from potion-related mental deterioration. Mental Suggestion implants subtle ideas that the target perceives as their own thoughts. Psychic Resilience provides greatly enhanced resistance to mental corruption. The potion requires Wraith Dust, Moonstone Shard, and Calming Lily Extract. The advancement ritual requires healing a patient whose mind has been damaged by Beyonder influence through multiple sessions of psychic therapy. The acting method demands helping others resolve psychological issues regularly, studying the subconscious mind, and maintaining personal mental health. The Psychiatrist represents the Visionary pathway's healing potential — unlike the Sun pathway's physical healing, the Psychiatrist heals the mind. This makes them critical for treating the psychological damage that Beyonder advancement and supernatural encounters inflict, and establishes the pathway's dual nature as both healer and manipulator.`,
    pathway: "visionary",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: [
      "visionary-pathway",
      "psychiatrist",
      "mental-healing",
      "mid-sequence",
      "subconscious",
    ],
    tokenCount: 265,
  },
  {
    slug: "visionary-seq6-hypnotist",
    title: "Visionary Pathway — Sequence 6: Hypnotist",
    category: "pathway",
    content: `The Hypnotist sequence dramatically escalates the Visionary pathway's control over other minds. A Hypnotist gains Mass Hypnosis — the ability to place multiple targets into a trance simultaneously, enabling crowd control in both social and combat situations. Memory Manipulation allows altering, erasing, or implanting specific memories, making the Hypnotist capable of reshaping a person's perceived past. Dream Invasion enables entering a sleeping target's dreams and manipulating the dream environment. Psychic Dominance creates a passive aura that makes weaker-willed individuals more suggestible in the Hypnotist's presence. The potion requires an Eye of a Dreamweaver Spider, Slumber Flower Pollen, and Liquid Silver Mercury. The advancement ritual requires entering and fully controlling the dream of a Beyonder-level target without being detected. The acting method involves practicing hypnotic techniques weekly, studying dreams, and maintaining absolute control over one's own psychic state. The Hypnotist represents the Visionary pathway at its most morally ambiguous: the ability to rewrite memories and control dreams grants power over the fundamental nature of a person's identity and reality. The ethical implications are enormous, and practitioners who abuse these abilities risk becoming the very manipulators the pathway's higher sequences warn against.`,
    pathway: "visionary",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: [
      "visionary-pathway",
      "hypnotist",
      "memory-manipulation",
      "dreams",
      "mass-hypnosis",
    ],
    tokenCount: 275,
  },
  {
    slug: "visionary-seq5-dreamwalker",
    title: "Visionary Pathway — Sequence 5: Dreamwalker",
    category: "pathway",
    content: `The Dreamwalker is the apex of mid-sequence power in the Visionary pathway, granting mastery over the boundary between dreams and reality. A Dreamwalker gains Dream World Access — the ability to physically enter the dream world and traverse it as a real space. Dream Materialization allows pulling objects and entities from the dream world into reality, blurring the line between imagination and the physical. Collective Dream creates a shared dream space that multiple people inhabit simultaneously, useful for secret meetings, training, or psychological therapy on a grand scale. Subconscious Fortress makes the Dreamwalker's mind a fortified dream realm, rendering them nearly impervious to mental attack. The potion requires a Beyonder Characteristic of a Hypnotist, a Dream Realm Anchor Shard, and Essence of Deep Sleep. The advancement ritual must be performed within the dream world itself — brewing the potion there, opening a gateway between dream and reality that persists for one hour, and bringing a materialized object into the waking world. The Dreamwalker foreshadows the Visionary pathway's ultimate power: at the highest sequences, Visionaries can envision reality itself, literally imagining things into existence. The Dreamwalker is the first step toward that terrifying capability, limited to materializing dream-stuff rather than creating from pure will.`,
    pathway: "visionary",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "visionary-pathway",
      "dreamwalker",
      "dream-world",
      "materialization",
      "mid-sequence-apex",
    ],
    tokenCount: 280,
  },
];
