import type { LoreEntry } from "./types";

export const DOOR_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "door-pathway-overview",
    title: "Door Pathway — Overview",
    category: "pathway",
    content: `The Door pathway belongs to the Lord of the Mysteries group, anchored to the Sefirah Castle — the same Above-the-Sequence group as the Fool and Error pathways, and a neighbour of both. Its powers grant an unrestrained freedom of movement: a Door Beyonder can phase through objects, teleport, divine the future through astrology, and fight with tricky spells or the recorded powers of other Beyonders. At high sequences they gain deep mastery of space — teleportation no longer confined to the spirit world, the concealment of whole spaces to avoid Beyonder detection, the direct replication of others' powers without first recording them, the sealing of things within space-time, the manipulation of gravity through the power of stars, and the creation of entire alternate spaces. Their authority represents the concept of Door, Alternate Worlds, and Space. The mythical-creature form is a huge humanoid figure built from layers of doors and balls of light formed by Worms of Stars. Its corresponding tarot card is The Magician, and its colour is turquoise. Like the Error pathway, Door Beyonders can safely switch pathways only from Sequence 3 upward.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [9, 8, 7, 6, 5],
    tags: ["door-pathway", "mysteries-group", "sefirah-castle", "space", "overview"],
    tokenCount: 240,
  },
  {
    slug: "door-seq9-apprentice",
    title: "Door Pathway — Sequence 9: Apprentice",
    category: "pathway",
    content: `The Apprentice is the entry point of the Door pathway, and its abilities are, as the wiki puts it, rather strange — Apprentices pursue the footprints of freedom and are very difficult to trap or stop. Their signature is Door Opening: using the unique traits of the spirit world, an Apprentice can phase through walls and other barriers by opening a symbolic, incorporeal door, provided no Beyonder power reinforces the barrier and it is not, in mystical terms, too thick to still be called a wall. They slip free of restraints and barriers, are rarely cornered, and possess a keen Spatial Intuition for the layout of a space and the routes that lead out of it. The potion's main ingredients are a Gem-Eating Worm and a Phantom Crystal, supplemented by goat's-beard grass hydrosol, ancient well water, any flower grown from a corpse, and soil contaminated by spirit-world creatures. The acting method asks the Apprentice to travel and roam freely, to probe doors, thresholds, and passages with restless curiosity, and to find the way out of any space they enter. As a Sequence 9 sequence it has no advancement ritual; acting alone digests the potion before advancing to Trickmaster.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: ["door-pathway", "apprentice", "travel", "space", "acting-method"],
    tokenCount: 260,
  },
  {
    slug: "door-seq8-trickmaster",
    title: "Door Pathway — Sequence 8: Trickmaster",
    category: "pathway",
    content: `The Trickmaster turns the Door pathway's spatial freedom into a repertoire of tricks. A Trickmaster can Flash — blinking a short distance through space, vanishing and reappearing nearby — and perform Escape Tricks to slip out of bindings, traps, and tight corners. They can manipulate objects at a distance through small spatial tricks and loose minor elemental tricks of electric shock, freezing, or sudden gas. The potion's main ingredients are the stomach sac of a Spirit-Eater and the blood of a Deep-Sea Garfish, supplemented by hornbeam essential oil, thread-ball grass powder, a fully open red chestnut flower, and pure water. The advancement ritual requires escaping an inescapable confinement — a bound and warded space with no ordinary exit — using only Flash, Escape Trick, and spatial sleight, and leaving behind no sign of how it was done. The acting method has the Trickmaster delight in movement and misdirection, make a performance of slipping away, keep wandering rather than settling, and treat every obstacle as a puzzle of space to be tricked open.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["door-pathway", "trickmaster", "travel", "trickery", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "door-seq7-astrologer",
    title: "Door Pathway — Sequence 7: Astrologer",
    category: "pathway",
    content: `The Astrologer carries the Door pathway into the mid sequences and into the reading of the stars. An Astrologer practises Divination Arts, reading the stars and the spirit world to divine the future and the hidden, and gains Spirit Vision to perceive the spirit world and the traces upon it. They can cloak themselves and their doings with Anti-Divination, frustrating the divination of others, and carry a Spiritual Intuition that warns of danger and anomalies. The potion's main ingredients are a Meteor Crystal and a crystallised lump of Lavos Squid blood, supplemented by clematis powder, a length of withered grapevine, a pair of octopus eyes, and strong liquor. The advancement ritual requires charting a true and hidden course of the stars — mapping them as they truly stand, beyond ordinary astronomy — to divine a secret guarded against divination, recording the working without alerting what has been spied upon. The acting method asks the Astrologer to chart the stars and the spirit world with driving curiosity, to wander far in pursuit of secret knowledge, and to keep their own path veiled even as they read the paths of others.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: ["door-pathway", "astrologer", "divination", "mid-sequence", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "door-seq6-scribe",
    title: "Door Pathway — Sequence 6: Scribe",
    category: "pathway",
    content: `The Scribe — also rendered Recorder — gives the Door pathway its signature ability to capture and replay the powers of others. A Scribe can Record the Beyonder power of another into themselves, storing it to be replayed at need, and loose a recorded ability as if it were their own. They can fold objects and writings away into a small pocket of space, and carry a flawless, perfect recall of everything they have recorded and read. The potion's main ingredients are one complete brain of an Asman and a cursed object left by an ancient wraith, supplemented by three pages of a diary more than twenty-two years old, quicksilver, honeysuckle essential oil, and equal measures of seawater, lake water, and glacier water. The advancement ritual requires recording and faithfully replaying the power of a hostile Beyonder, witnessing the ability in the midst of a true conflict and reproducing it exactly. The acting method has the Scribe record, catalogue, and preserve knowledge and power alike, roam widely to gather what is worth recording, and guard both their records and the spaces they fold them into.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: ["door-pathway", "scribe", "recording", "mid-sequence", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "door-seq5-traveler",
    title: "Door Pathway — Sequence 5: Traveler",
    category: "pathway",
    content: `The Traveler is the apex of mid-sequence power in the Door pathway, a master of distance and the doors between places. A Traveler can perform Traveling — opening doors across great distances and journeying through the spirit world — and Blink, teleporting themselves and what they carry across their line of sight. Through Positioning they fix and recall spatial coordinates, returning to them at will, and with the Invisible Hand they reach through folded space to act on things far from their body. The potion's main ingredients are the Wandering Hide (the cast-off skin of a spirit-world rover) and the heart of a Shadowless Demon Wolf, supplemented by powder left by a trapped ghost, lemon balm powder, a star map drawn in spiritually-charged blood, and Shadowless Demon Wolf blood. The advancement ritual requires establishing four distinct, far-flung coordinates deep within the spirit world, binding them into a single network the Traveler can traverse at will, and travelling the full circuit safely. The acting method has the Traveler journey without limit, let no distance or border hold them, map the spirit world's far places, and carry their curiosity to every threshold they can reach.`,
    pathway: "door",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "door-pathway",
      "traveler",
      "teleportation",
      "mid-sequence-apex",
      "acting-method",
    ],
    tokenCount: 270,
  },
];
