import type { LoreEntry } from "./types";

export const HANGED_MAN_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "hanged-man-pathway-overview",
    title: "Hanged Man Pathway — Overview",
    category: "pathway",
    content: `The Hanged Man pathway belongs to the God Almighty group, anchored to the Chaos Sea — the same Above-the-Sequence group as the Visionary, Sun, and Tyrant pathways. It represents Degeneration, but also sacrifice and responsibility in a positive sense, holding the symbolisms of Sin and Sacrifice and partial authority over Shadow, Darkness, Degeneration, Corruption, and Mutation. Its Beyonders carry innate knowledge of ritualistic magic and secret entities, high spiritual intuition, shadow spells, and flesh-and-blood magic, and can graze upon souls to use their powers. At high sequences they can peel evil thoughts and fuse them with a shadow to form a second self, manipulate flesh and blood into a trinity, twist the ambiguity of others' words, bring degeneration to all things, spread betrayal, and become the embodiment of Sacrifice and Sin. Its mythical-creature form is a black shadow and writhing flesh, its tarot card is The Hanged Man — the card of surrender, martyrdom, and sacrifice to the greater good — and its colour is blood red. According to Klein Moretti this pathway is the easiest of all to lose control on and fall to madness.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: ["Klein Moretti"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "hanged-man-pathway",
      "god-almighty-group",
      "chaos-sea",
      "sacrifice",
      "overview",
    ],
    tokenCount: 250,
  },
  {
    slug: "hanged-man-seq9-secrets-suppliant",
    title: "Hanged Man Pathway — Sequence 9: Secrets Suppliant",
    category: "pathway",
    content: `The Secrets Suppliant is the entry point of the Hanged Man pathway, and its gifts are knowledge bought with sacrifice. A Secrets Suppliant is bestowed, through the potion itself, with Mysticism Knowledge — a decent grounding in sacrifices and some ritualistic magic, including a handful of honorific names of secret, sinister entities tied to depravity, true kin, and the gaze of fate. They can perform Ritualistic Magic and divination drawn from those entities, and carry the High Spirituality common to the pathway. The knowledge attached to the potion more or less distorts a Secrets Suppliant's perception — the first taste of why this pathway corrupts so readily. The potion's main ingredients are the heart of a Shadow-Touched Toad and ash gathered from a sacrificial altar, supplemented by black goat's blood, mandrake root powder, and oil pressed from graveyard wormwood. The acting method asks the Secrets Suppliant to seek forbidden secrets and offer the sacrifices the rites demand, to embrace self-denial and burden, and to bear the distortions of dark knowledge without surrendering their humanity. As a Sequence 9 sequence it has no advancement ritual; acting digests the potion before advancing to Listener.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: [
      "hanged-man-pathway",
      "secrets-suppliant",
      "sacrifice",
      "ritual",
      "acting-method",
    ],
    tokenCount: 270,
  },
  {
    slug: "hanged-man-seq8-listener",
    title: "Hanged Man Pathway — Sequence 8: Listener",
    category: "pathway",
    content: `The Listener — also styled the Whispered — turns the Hanged Man pathway toward the gathering of secrets. A Listener can Listen, hearing whispers carried on shadow and wind: secrets, intentions, and distant words otherwise hidden. They can also Whisper, sending words that worm into a target's mind to unsettle or mislead, and their spiritual sensitivity to the unseen is greatly heightened. The potion's main ingredients are the ears of a Whispering Shadow-Bat and a fragment of wood from a confessional steeped in secrets, supplemented by nightshade hydrosol, a strip of Shadow-Bat wing membrane, and wax from a black ritual candle. The advancement ritual requires keeping a vigil of silence and listening — denying oneself speech and comfort — until the shadows yield a secret hidden from all others, and setting it down faithfully without acting on it for gain. The acting method has the Listener listen for the secrets others bury, give up their own voice in the world's affairs to observe and abstain, and carry the weight of what they hear without letting it corrupt them — the pathway's themes of self-denial and dangerous knowledge tightening.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["hanged-man-pathway", "listener", "secrets", "self-denial", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "hanged-man-seq7-shadow-ascetic",
    title: "Hanged Man Pathway — Sequence 7: Shadow Ascetic",
    category: "pathway",
    content: `The Shadow Ascetic carries the Hanged Man pathway into the mid sequences and into mastery of shadow through self-denial. A Shadow Ascetic can perform Shadow Summon, calling shadows into form to serve, scout, and strike; Shadow Manipulation, shaping, extending, and commanding the shadows around them; Shadow Lurking, sinking into shadow to move unseen and lie in wait; and Shadow Curse, laying curses carried through a target's own shadow. The potion's main ingredients are the heart of a Shadow-Crawler and a scrap of a penitent's hair shirt, supplemented by Shadow-Crawler blood, powdered black tourmaline, and salt blessed through ritual fasting. The advancement ritual requires enduring a trial of self-denial in darkness — withdrawing into the dark and denying oneself food, light, and ease — while mastering one's summoned shadows through the privation rather than despite it. The acting method has the Shadow Ascetic live as an ascetic of shadow, master the shadows through discipline and sacrifice rather than indulgence, and take on burdens others refuse while asking nothing in return.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: [
      "hanged-man-pathway",
      "shadow-ascetic",
      "shadow",
      "self-denial",
      "acting-method",
    ],
    tokenCount: 250,
  },
  {
    slug: "hanged-man-seq6-rose-bishop",
    title: "Hanged Man Pathway — Sequence 6: Rose Bishop",
    category: "pathway",
    content: `The Rose Bishop — also rendered Rose Priest — gives the Hanged Man pathway its signature flesh-and-blood magic. A Rose Bishop works magic through flesh and blood, their own or another's; they can shape Flesh and Blood Servants and constructs to do their bidding, soften and reshape flesh to slip through gaps or absorb blows, and lay a Blood Curse through a victim's flesh and blood. The potion's main ingredients are the heart of a Blood-Rose and the spinal fluid of a Flesh-Weaver, supplemented by ninety millilitres of sacrificial blood, seven crimson Blood-Rose petals, and carmine sandalwood oil. The advancement ritual requires completing a great flesh-and-blood rite that cannot be done without genuine sacrifice, offering up the required cost from one's own flesh and blood — not only another's — without letting the working corrupt one's purpose. The acting method has the Rose Bishop offer flesh and blood in sacrifice, their own offerings first of all, take up the responsibility of the rite and bear its cost willingly, and hold to their vows even as the flesh-magic tempts them toward depravity.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: [
      "hanged-man-pathway",
      "rose-bishop",
      "flesh-and-blood",
      "sacrifice",
      "acting-method",
    ],
    tokenCount: 250,
  },
  {
    slug: "hanged-man-seq5-shepherd",
    title: "Hanged Man Pathway — Sequence 5: Shepherd",
    category: "pathway",
    content: `The Shepherd is the apex of mid-sequence power in the Hanged Man pathway, where flesh, shadow, and the grazing of souls converge. A Shepherd can Graze upon souls and spirits, devouring a portion of their power to fuel their own; they command greatly amplified flesh-and-blood and shadow magic, can devour spirits and flesh to grow their dominion and replenish themselves, and marshal a Shepherd's Flock of shadow- and flesh-servants bound to their will. The potion's main ingredients are the stomach of a Soul-Grazing Beast and the spirit-crystal of a Degenerate Shepherd, supplemented by a soul freely surrendered in sacrifice, Soul-Grazing Beast blood, soil steeped in a Degenerate Shepherd's shadow, and sap from a crimson flesh-tree. The advancement ritual requires gathering a flock of bound souls and spirits and sustaining them through one's own sacrifice — by grazing and offering rather than mere devouring — while holding one's purpose against the depravity the power presses upon one. The acting method has the Shepherd tend the souls and shadows in their keeping, sacrifice and deny themselves for the flock's sake, and resist the constant pull toward sin and degeneration that defines the pathway.`,
    pathway: "hanged-man",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "hanged-man-pathway",
      "shepherd",
      "souls",
      "mid-sequence-apex",
      "acting-method",
    ],
    tokenCount: 270,
  },
];
