import type { LoreEntry } from "./types";

export const SUN_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "sun-pathway-overview",
    title: "Sun Pathway — Overview",
    category: "pathway",
    content: `The Sun pathway belongs to the God Almighty group, anchored to the Chaos Sea. It is the pathway of holy light, purification, and healing — progressing from simple hymns and minor healing at low sequences to devastating solar judgment and sanctified authority at higher levels. The Sun pathway neighbors the Visionary pathway within the God Almighty group. In the Fifth Epoch, the Church of the Eternal Blazing Sun is the primary orthodox institution controlling the Sun pathway, with its Beyonder division — the Inquisition — serving as both supernatural enforcement and religious authority, particularly dominant in the Intis Republic. The Sun pathway is unique in the Forsaken Land of the Gods, where the City of Silver (sealed from sunlight for millennia) reveres the God of the Sun and maintains its own tradition of Sun pathway Beyonders. Derrick Berg, "The Sun" of the Tarot Club, comes from this tradition. The Sun pathway is the most straightforwardly "heroic" of the four MVP pathways: its practitioners heal the wounded, purify corruption, and smite evil with holy light. This makes it both powerful in combat against undead and evil entities and invaluable as a support role.`,
    pathway: "sun",
    epoch: 5,
    npcs: ["Derrick Berg"],
    sequences: [9, 8, 7, 6, 5],
    tags: [
      "sun-pathway",
      "god-almighty-group",
      "chaos-sea",
      "overview",
      "eternal-blazing-sun",
    ],
    tokenCount: 255,
  },
  {
    slug: "sun-seq9-bard",
    title: "Sun Pathway — Sequence 9: Bard",
    category: "pathway",
    content: `The Bard is the entry point of the Sun pathway, granting abilities tied to music, warmth, and minor healing. A Bard gains Holy Hymn — the ability to sing songs that channel purifying energy, cleansing minor corruption and bolstering the morale of allies. Minor Healing allows channeling warmth through touch to mend small wounds and ease pain, making the Bard an immediate asset in any group. Light Sensitivity provides enhanced perception in well-lit environments, complementing the pathway's solar theme. The potion requires two main ingredients — Crystal Sunflower and Siren Rock — and three supplementary ingredients: Midsummer Grass, July Wine Juice, and Elf Dark Leaf. The acting method requires singing or performing music daily, spreading warmth and hope to those in despair, and rising with the sun to greet the dawn. The Bard's acting method is one of the most positive of any pathway — it demands genuine optimism and a commitment to uplifting others. This makes it emotionally sustainable compared to pathways like the Clown, which require suppressing true emotions. However, maintaining constant positivity in the face of the Beyonder world's horrors presents its own challenge. Derrick Berg's earnest, almost naive optimism in the Tarot Club reflects the Bard sequence's ideal. No advancement ritual is required.`,
    pathway: "sun",
    epoch: 5,
    npcs: ["Derrick Berg"],
    sequences: [9],
    tags: ["sun-pathway", "bard", "healing", "music", "purification", "acting-method"],
    tokenCount: 255,
  },
  {
    slug: "sun-seq8-light-suppliant",
    title: "Sun Pathway — Sequence 8: Light Suppliant",
    category: "pathway",
    content: `The Light Suppliant sequence enhances the Bard's abilities with focused light manipulation and stronger healing. A Light Suppliant gains Light Beam — the ability to project a focused beam of purifying light that damages supernatural evil. Healing Touch upgrades Minor Healing to cure moderate wounds and minor diseases through direct contact. Radiant Aura creates a passive glow that repels weaker undead and evil spirits, making the Light Suppliant a natural enemy of the Death pathway's lower-sequence creations. The potion requires one main ingredient — Brilliance Rock — and two supplementary ingredients: Golden-Edged Sunflower and Aconite Juice. The advancement ritual requires conducting a healing ceremony under direct sunlight, gathering those in need of healing, channeling sunlight through prayer, and healing at least three people. The acting method demands praying at dawn and dusk without fail, aiding the sick whenever possible, and carrying light into darkness — never shying away from it. The Light Suppliant embodies the Sun pathway's priestly aspect: the practitioner is a servant of the light, healing and protecting as a sacred duty. This sequence begins to establish the Sun pathway's combat niche as an anti-undead and anti-corruption specialist, making Sun Beyonders highly valued partners for Darkness and Death pathway operatives who regularly face such threats.`,
    pathway: "sun",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["sun-pathway", "light-suppliant", "healing", "purification", "anti-undead"],
    tokenCount: 270,
  },
  {
    slug: "sun-seq7-solar-high-priest",
    title: "Sun Pathway — Sequence 7: Solar High Priest",
    category: "pathway",
    content: `The Solar High Priest marks the Sun pathway's entry into mid-sequence power, combining area-effect purification with religious authority. A Solar High Priest gains Blazing Radiance — an intense burst of holy light that deals heavy damage to evil entities in a wide area. Purification Ritual allows cleansing an entire location of spiritual corruption through extended prayer. Endurance of the Sun provides enhanced physical stamina and resistance to cold and darkness effects. Consecration blesses an object or location to repel evil for a sustained duration. The potion requires a Phoenix Feather Fragment, Sacred Incense Resin, and Dawn Dew. The advancement ritual requires identifying a location tainted by supernatural darkness and performing a purification from dawn to noon, successfully cleansing the corruption. The acting method demands leading religious ceremonies regularly, protecting the faithful, defending sacred sites, and embodying scriptural teachings. The Solar High Priest represents the Sun pathway's transition from individual healer to community leader — the practitioner becomes a focal point of faith and protection for others. The Consecration ability is particularly significant for gameplay: it allows establishing safe zones in hostile environments, a capability no other MVP pathway provides.`,
    pathway: "sun",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: [
      "sun-pathway",
      "solar-high-priest",
      "mid-sequence",
      "purification",
      "consecration",
    ],
    tokenCount: 265,
  },
  {
    slug: "sun-seq6-notary",
    title: "Sun Pathway — Sequence 6: Notary",
    category: "pathway",
    content: `The Notary sequence introduces the Sun pathway's authority and justice-based abilities. A Notary gains Sacred Contract — the power to create supernaturally binding agreements where breakers suffer divine retribution, making them invaluable for enforcing deals between Beyonders. Truth Detection compels honesty during formal questioning. Aura of Authority projects a presence that compels respect and obedience from weaker-willed beings. Holy Fire summons flames of purification that burn evil but spare the innocent — a more targeted version of earlier light-based attacks. The potion requires a Scale of a Golden Serpent, Ink of Binding, and Judgment Stone Dust. The advancement ritual requires adjudicating a dispute between two Beyonders and enforcing the outcome through Sacred Contract. The acting method demands upholding justice, serving as arbiter when called upon, and never breaking one's own word. The Notary represents a thematic shift in the Sun pathway from healer to judge. This sequence is narratively significant because it establishes the Sun pathway's connection to law and order — at higher sequences, this evolves into divine authority over truth and morality. For gameplay, Sacred Contract creates unique social mechanics: the ability to enforce agreements supernaturally adds a powerful diplomatic tool.`,
    pathway: "sun",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: ["sun-pathway", "notary", "contracts", "justice", "truth", "authority"],
    tokenCount: 270,
  },
  {
    slug: "sun-seq5-priest-of-light",
    title: "Sun Pathway — Sequence 5: Priest of Light",
    category: "pathway",
    content: `The Priest of Light is the apex of mid-sequence power in the Sun pathway, combining devastating solar combat with supreme healing and protective abilities. A Priest of Light gains Divine Healing — the ability to heal severe wounds and cure serious diseases through channeled light, making them the most powerful healers among the four MVP pathways at this level. Solar Judgment calls down a pillar of concentrated sunlight to smite a target area, functioning as the pathway's ultimate offensive ability. Sanctuary creates a zone of holy light that protects all within from evil influence, establishing a fortified position. Radiant Constitution suffuses the body with light, granting high resistance to corruption, poison, and disease. The potion requires three main ingredients — Eyes of a Radiant Giant, Blood of a Radiant Giant (300ml), and a Self-Transcribed Holy Book. The advancement ritual requires establishing a new consecrated sanctuary through a day-long ritual and defending it against a supernatural assault. The acting method demands leading a congregation, performing major healing works weekly, and standing as a beacon of light. The Priest of Light embodies the Sun pathway's highest ideal within the MVP scope: a spiritual leader who heals the broken, shields the vulnerable, and burns away evil. At this level, the practitioner's body literally begins to radiate light, marking them as something more than human.`,
    pathway: "sun",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "sun-pathway",
      "priest-of-light",
      "divine-healing",
      "solar-judgment",
      "mid-sequence-apex",
    ],
    tokenCount: 285,
  },
];
