import type { LoreEntry } from "./types";

export const ERROR_PATHWAY_LORE: LoreEntry[] = [
  {
    slug: "error-pathway-overview",
    title: "Error Pathway — Overview",
    category: "pathway",
    content: `The Error pathway belongs to the Lord of the Mysteries group, anchored to the Sefirah Castle — the same Above-the-Sequence group as the Fool and Door pathways, and a neighbour of both. Its powers deceive and steal: an Error Beyonder can trick others with eloquence and sleight of hand, steal Beyonder or mundane abilities, decrypt secrets, and steal thoughts and intentions. Theft is the pathway's core skill, and it deepens as one advances. At low sequences theft targets physical items; it grows to encompass Beyonder abilities, then thoughts and ideas, then life itself through parasitism, then fate, identity, and self-awareness, and finally — at the highest sequences — time, anchors, and authorities. At high sequences an Error Beyonder can become a parasite within a host, deceive the world's rules, create avatars, tamper with fate, manipulate time, and exploit loopholes like a "BUG" in reality itself. Its mythical-creature form is the Worms of Time, and its tarot card is The Lovers; its colour is snow-white platinum. Like the Door pathway, Error Beyonders can safely switch pathways only from Sequence 3 upward.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [9, 8, 7, 6, 5],
    tags: ["error-pathway", "mysteries-group", "sefirah-castle", "theft", "overview"],
    tokenCount: 250,
  },
  {
    slug: "error-seq9-marauder",
    title: "Error Pathway — Sequence 9: Marauder",
    category: "pathway",
    content: `The Marauder is the entry point of the Error pathway and is, the wiki notes, hard to tell apart from an ordinary bandit or thief — though for a Marauder the theft of riches is less about enjoyment or survival than answering a calling. Their defining ability is Theft: Marauders steal physical items with supernatural deftness. They possess Agile Hands — wrist and finger flexibility heightened far beyond the general bodily enhancement — making them experts at sleight of hand, and Superior Observation, an intuition that lets them sense at a glance where valuable items are hidden within reach. The potion's main ingredients are a Blood-Spotted Black Mosquito and the core of a Candle-Eating Spirit, supplemented by a hundred millilitres of others' blood, nine nail fragments each from a different person, a sapphire, and vervain powder. The acting method asks the Marauder to steal and pilfer as a calling, to trick and deceive their marks rather than take by force what guile can lift, and to slip away unseen with what they have taken. As a Sequence 9 sequence it has no advancement ritual; acting digests the potion before advancing to Swindler.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [9],
    tags: ["error-pathway", "marauder", "theft", "trickery", "acting-method"],
    tokenCount: 260,
  },
  {
    slug: "error-seq8-swindler",
    title: "Error Pathway — Sequence 8: Swindler",
    category: "pathway",
    content: `The Swindler turns the Error pathway from the lifting of objects to the lifting of trust. A Swindler's Eloquence spins words that beguile, persuade, and disarm those who listen; their Charm projects a charisma that lowers a mark's guard and wins their confidence; and Thought Misdirection steers a target's attention and assumptions where the Swindler wishes them to go. Their theft now extends to small advantages and openings, not only objects. The potion's main ingredients are a Human-Faced Pitcher Plant and a larva from a Charm-Swarm, supplemented by pure water, twenty millilitres of others' tears, a lapis lazuli, and white chestnut balm. The advancement ritual requires carrying off a grand confidence scheme by guile alone — constructing an elaborate deception against a wary mark, seeing it through to a profitable end with words and misdirection, and withdrawing before the swindle is ever unmasked. The acting method has the Swindler con and beguile, let their tongue do the stealing, build and burn false trust as the scheme demands, and vanish before the deception is discovered.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [8],
    tags: ["error-pathway", "swindler", "deception", "theft", "acting-method"],
    tokenCount: 250,
  },
  {
    slug: "error-seq7-cryptologist",
    title: "Error Pathway — Sequence 7: Cryptologist",
    category: "pathway",
    content: `The Cryptologist carries the Error pathway into the mid sequences and into the stealing of secrets. A Cryptologist's Decryption unravels ciphers, codes, and hidden meanings with supernatural insight, and they can perform Thought Theft, stealing fragments of thought and intention from an unguarded mind. Their Superior Observation reads the smallest tells and the patterns others overlook, and their cipher-trained mind can hold and manipulate vast webs of code and secret knowledge. The potion's main ingredients are the brain of a Sphinx and an adult from a Charm-Swarm, supplemented by Sphinx blood, Charm-Swarm mucus, a moonstone, a wild rose, and a set of codes the Beyonder has devised themselves. The advancement ritual requires cracking an unbreakable cipher and stealing the secret it guards, lifting the protected knowledge without the owner's awareness and leaving the cipher seemingly untouched. The acting method has the Cryptologist break codes and steal secrets so that no cipher stands against them, trick understanding from the guarded and unwilling, and keep their own methods encrypted and unknowable.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [7],
    tags: [
      "error-pathway",
      "cryptologist",
      "decryption",
      "mid-sequence",
      "acting-method",
    ],
    tokenCount: 250,
  },
  {
    slug: "error-seq6-prometheus",
    title: "Error Pathway — Sequence 6: Prometheus",
    category: "pathway",
    content: `The Prometheus — whose name, drawn from the original "Fire Stealer," points straight at the myth of the one who stole fire from the gods — gives the Error pathway its signature theft of Beyonder power itself. A Prometheus can steal the Beyonder ability of another, taking their power as their own, and can bestow or kindle that stolen power and knowledge in others, like passing on stolen fire. They carry a strong Mental Resistance against intrusion and the lingering imprints of stolen powers, and a Superior Observation that perceives the abilities and weaknesses worth stealing in a foe. The potion's main ingredients are a Crystal Threadworm and an attachment-object left by a Robed Phantom, supplemented by a hundred millilitres of freshly stolen fine wine, Robed Phantom residual powder, a citrine, larch essential oil, and a kindling source of fire. The advancement ritual requires stealing a Beyonder's signature power in the heat of conflict and binding it into oneself, withstanding the imprint of its former owner. The acting method has the Prometheus steal power itself as a thief takes fire, deceive and outwit those stronger than them, and share or hoard their stolen fire as cunning dictates.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [6],
    tags: [
      "error-pathway",
      "prometheus",
      "ability-theft",
      "mid-sequence",
      "acting-method",
    ],
    tokenCount: 260,
  },
  {
    slug: "error-seq5-dream-stealer",
    title: "Error Pathway — Sequence 5: Dream Stealer",
    category: "pathway",
    content: `The Dream Stealer — also rendered Dreams Thief — is the apex of mid-sequence power in the Error pathway, where theft turns from the material toward the abstract. A Dream Stealer can Disguise themselves at the level of heavenly mysteries, stealing an identity so completely they become another in the eyes of fate; they can usurp the thoughts and intentions of a target, slip into the dreams of others to steal what they hold dear, and steal increasingly abstract things — ideas, roles, and concealed truths. The potion's main ingredients are the heart of a Dream-Eating Rat and the spirit of a Fallen Aura, supplemented by Dream-Eating Rat blood, despiritualised Fallen Aura, a celestite, lavender hydrosol, and fifty millilitres of another's tears shed over a shattered ideal. The advancement ritual requires becoming a recurring figure — an important supporting role or the chief villain — in the unconscious dreams of at least thirty people, ensuring those dreams are unfolding at the moment the potion is consumed, and stealing from within them without waking the dreamers. The acting method has the Dream Stealer steal identities, dreams, and ideas, deceive even fate, and wear stolen selves without losing the thread of their own.`,
    pathway: "error",
    epoch: 5,
    npcs: [],
    sequences: [5],
    tags: [
      "error-pathway",
      "dream-stealer",
      "theft",
      "mid-sequence-apex",
      "acting-method",
    ],
    tokenCount: 270,
  },
];
