import type { LoreEntry } from "./types";

export const TINGEN_LORE: LoreEntry[] = [
  {
    slug: "tingen-city-overview",
    title: "Tingen City — Overview",
    category: "location",
    content: `Tingen City is a mid-sized industrial city in the Awwa County of the Loen Kingdom, situated along the Tussock River in the kingdom's midlands. It serves as the primary setting for the opening arc of Lord of the Mysteries. The city is a microcosm of Fifth Epoch society: gas-lit streets, steam-powered factories, horse-drawn carriages, and a populace navigating the tensions between industrial progress and entrenched class hierarchies. Tingen has a population of roughly 300,000 and functions as a regional center for trade, education, and light manufacturing. The city's atmosphere is defined by perpetual overcast skies, the smell of coal smoke, and a pervasive sense that something ancient lurks beneath its veneer of modernity. Supernatural incidents are quietly handled by the three official Beyonder organizations stationed here: the Nighthawks (Church of the Evernight Goddess), the Mandated Punishers (Church of the Lord of Storms), and the Machinery Hivemind (Church of the God of Steam and Machinery).`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "loen-kingdom", "fifth-epoch"],
    tokenCount: 210,
  },
  {
    slug: "tingen-iron-cross-district",
    title: "Tingen — Iron Cross District",
    category: "location",
    content: `Iron Cross Street and its surrounding district form one of Tingen's lower-middle-class neighborhoods. Klein Moretti's apartment is located here, a modest flat in a multi-story tenement building. The district is characterized by narrow cobblestone streets, rows of brick tenements with iron railings, small shops at street level, and the constant background noise of factory whistles. The residents are predominantly factory workers, clerks, and minor civil servants. Gas lamps line the main thoroughfares but many side alleys remain dark after sunset. A small church and several pubs serve as community gathering points. The area is not impoverished but carries a sense of constrained respectability — residents maintain appearances despite modest means. Klein's daily life here involves walking to Blackthorn Security Company (the Nighthawks' cover operation) and frequenting the local newsstand and food vendors.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Klein Moretti"],
    sequences: [],
    tags: ["district", "residential", "setting"],
    tokenCount: 180,
  },
  {
    slug: "tingen-khoy-university",
    title: "Tingen — Khoy University",
    category: "location",
    content: `Khoy University is Tingen's premier institution of higher learning, located in the northern part of the city. It offers programs in history, law, medicine, and the natural sciences. Klein Moretti attended Khoy University as a history student before his death and subsequent transmigration. The university campus features stone buildings in a classical architectural style, a modest library, lecture halls, and tree-lined courtyards. The faculty includes both conventional academics and, unbeknownst to most, individuals with connections to the Beyonder world — some serve as informants for the orthodox churches. The university plays a role in the early narrative as Klein draws on his academic knowledge of history to navigate the Beyonder world's complex lore and rituals. Students at Khoy University represent Tingen's aspiring middle class, and the institution serves as a social hub where different classes intermingle.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Klein Moretti"],
    sequences: [],
    tags: ["education", "institution", "setting"],
    tokenCount: 185,
  },
  {
    slug: "tingen-blackthorn-security",
    title: "Tingen — Blackthorn Security Company",
    category: "location",
    content: `Blackthorn Security Company is the front operation for the Tingen Nighthawks team, located on Zouteland Street. To the public, it appears to be a small private security firm. Behind its mundane facade, the building contains a concealed underground operations center where the Nighthawks conduct their true work: investigating supernatural incidents, sealing dangerous artifacts, and eliminating threats from uncontrolled Beyonders and aberrations. The building has a modest office on the ground floor with a reception area staffed by Mrs. Klarman, and the real work happens in sealed basement rooms equipped with ritual materials, containment wards, and an evidence vault for mystical artifacts. Captain Dunn Smith maintains his office here, perpetually dozing between cases. The Nighthawks operate under strict secrecy — their existence as a Beyonder organization is classified, and all members maintain cover identities as security consultants.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Dunn Smith", "Klein Moretti", "Leonard Mitchell"],
    sequences: [],
    tags: ["nighthawks", "headquarters", "cover-operation", "setting"],
    tokenCount: 195,
  },
  {
    slug: "tingen-divination-club",
    title: "Tingen — Divination Club",
    category: "location",
    content: `The Divination Club is a semi-private social gathering in Tingen where enthusiasts of the occult meet to practice divination, share mystical knowledge, and discuss esoteric topics. Located in a rented hall, the club is one of Tingen's few venues where interest in the supernatural is openly expressed — though most members are ordinary people dabbling in superstition rather than true Beyonders. Klein Moretti frequents the club after becoming a Sequence 9 Seer, using it both to practice his divination abilities and to digest his potion by "acting" the role of a mysterious seer. The club provides Klein with a social cover and a venue for his acting method. Members are a mix of curious intellectuals, minor nobles seeking entertainment, and the occasional genuine practitioner. The club's atmosphere blends Victorian parlor society with occult aesthetics — crystal balls, tarot decks, astrology charts, and dim candlelight define the setting.`,
    epoch: 5,
    city: "tingen",
    npcs: ["Klein Moretti"],
    sequences: [9],
    tags: ["social", "divination", "acting-method", "setting"],
    tokenCount: 195,
  },
  {
    slug: "tingen-cathedral-of-serenity",
    title: "Tingen — Cathedral of Serenity",
    category: "location",
    content: `The Cathedral of Serenity is Tingen's primary house of worship for the Church of the Evernight Goddess. It is the largest religious building in the city, featuring tall stained-glass windows depicting the Goddess in her aspect as guardian of the night, dark stone architecture, and a perpetually dim interior lit by candlelight. The cathedral serves as the spiritual center for Tingen's Evernight faithful and the administrative hub from which the Nighthawks receive their orders. Bishop Utravsky presides over public services, while the Nighthawks' chain of command runs through the church hierarchy. The cathedral's basement contains restricted archives and sealed chambers for handling dangerous artifacts. Sunday services draw large congregations from all social classes. The atmosphere is solemn and comforting — the Evernight Goddess's doctrine emphasizes rest, darkness as shelter, and the peace of eternal sleep. For Klein, the cathedral represents both his cover organization's spiritual authority and a genuine source of protection.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["church", "evernight-goddess", "religion", "nighthawks", "setting"],
    tokenCount: 200,
  },
  {
    slug: "tingen-tussock-river",
    title: "Tingen — Tussock River and Docks",
    category: "location",
    content: `The Tussock River runs through Tingen City, serving as both a commercial waterway and a natural boundary between the city's districts. The docks along the river handle cargo from inland barges and smaller seagoing vessels, making Tingen a secondary trade hub. The dock district is rougher than the city center — warehouses, taverns catering to sailors and dockworkers, and flophouses line the waterfront. The Mandated Punishers (the Beyonder arm of the Church of the Lord of Storms) maintain a stronger presence in this area, as maritime supernatural incidents fall under their jurisdiction. At night, the river district becomes particularly atmospheric: fog rolls off the water, gas lamps create pools of yellowish light, and the sound of the river provides a constant backdrop. Several early supernatural encounters in the narrative occur near or on the Tussock River, including investigations into smuggled Beyonder materials and encounters with water-dwelling aberrations.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["waterway", "commerce", "docks", "mandated-punishers", "setting"],
    tokenCount: 195,
  },
  {
    slug: "tingen-north-district",
    title: "Tingen — Backlund and Hillston Upper Districts",
    category: "location",
    content: `Tingen's northern and elevated areas house the city's wealthier residents. Named areas like Hillston Borough feature detached homes with small gardens, wider streets with better gas lighting, and proximity to Khoy University. The local aristocracy and successful merchants reside here, maintaining social clubs, hosting evening gatherings, and employing domestic staff. These districts contrast sharply with the working-class neighborhoods near the river and factories. The police presence is more visible, the streets are cleaner, and horse-drawn carriages are common. For the Beyonder world, these upper districts are significant because several secretive collectors of mystical artifacts reside here, and the Psychology Alchemists recruit from the educated upper class. The social stratification visible in Tingen's geography mirrors the Loen Kingdom's broader class structure, where birth, education, and wealth determine access to both mundane and supernatural opportunities.`,
    epoch: 5,
    city: "tingen",
    npcs: [],
    sequences: [],
    tags: ["district", "upper-class", "setting", "social-stratification"],
    tokenCount: 185,
  },
];
