import type { LoreEntry } from "./types";

export const TRIER_LORE: LoreEntry[] = [
  {
    slug: "trier-city-overview",
    title: "Trier — Overview",
    category: "location",
    content: `Trier is the capital of the Intis Republic, set in the region where the Ryan and Srenzo rivers meet on the western side of the Northern Continent. It is a world-class metropolis and a sacred land for artists, musicians, and novelists — a place of bustling arts and humanities so devoted to display that it is nicknamed the "City of Fashion," where even a figure in a black robe and hood draws no second glance and idlers walk turtles on leads to advertise their leisurely elegance. In the Fourth Epoch it was the capital of the Tudor Empire; in the Fifth it was rebuilt into its modern grandeur after the era of Emperor Roselle. Though Trier has its own pollution, its factories are sensibly confined to the south, so the city largely keeps its sunlight — unlike smog-shrouded Backlund. The Intis Republic is governed not by a king but by a parliament, and Trier seethes with the revolutionary ferment of that order: audacious students shout slogans in the streets, and the city is a crossroads of political fervour, art, and faith.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "intis-republic", "capital", "fifth-epoch"],
    tokenCount: 230,
  },
  {
    slug: "trier-city-walls-quartiers",
    title: "Trier — The City Walls & Quartiers",
    category: "location",
    content: `Trier is girdled by a wall three metres high pierced by fifty-four gates, each manned by tax collectors and police who also watch for wanted criminals passing in or out. Within the walls the city is divided into twenty quartiers, and these districts structure both its government and its policing: Trier holds nearly forty seats in the Intis National Convention, distributed among the twenty quartiers, and the district representatives double as councillors on the Trier City Council. Every quartier keeps its own police headquarters under a commissioner, with a four-rank hierarchy of officers. Seats and prosperity are not evenly shared — the wealthier Greater Trier region carries disproportionate weight in the Convention, a fact that feeds the city's political resentments. The gated, walled structure gives Trier a layered character: each quartier is a small world with its own character, police, and grievances, knit together by the toll-gates and the river traffic of the Ryan and Srenzo.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["district", "walls", "administration", "setting"],
    tokenCount: 210,
  },
  {
    slug: "trier-island-district",
    title: "Trier — The Island District",
    category: "location",
    content: `The Island District is the spiritual centre of Trier and the seat of the city's dominant faith. Here rises Saint Viève Cathedral, the headquarters and chief cathedral of the Church of the Eternal Blazing Sun, whose golden dome catches and throws back the daylight the city is so proud of keeping. Like all cathedrals of the Blazing Sun, it is built on a resplendent golden base adorned with gilded accents — an onion-shaped dome painted shimmering gold as a representation of the radiant sun, set above white walls edged in gilt, a monumental Sun Sacred Emblem, vivid stained glass, and a vast mural sprinkled with golden powder. Sunlight pouring through the glass behind the altar lends the interior an atmosphere of profound sanctity. The Island District is therefore the beating heart of sun-worship in the Republic, the place from which the Church's white-and-gold-robed clergy radiate their influence; their prayer gesture — head raised, arms spread as if to embrace sunlight — is performed here daily before the dawn.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["district", "cathedral", "eternal-blazing-sun", "religion", "setting"],
    tokenCount: 215,
  },
  {
    slug: "trier-underground",
    title: "Trier — The Underground & Catacombs",
    category: "location",
    content: `Beneath Trier lies a labyrinth as extensive as the surface, or more so. The city was once smaller and ringed by quarries that supplied its building stone; as the population swelled, Trier expanded to swallow the quarries, leaving the ground riddled with holes and mine tunnels. Part of the city sank underground in the Fourth Epoch, and the later installation of sewers, subways, and gas pipes made the subterranean network denser still. Over nearly a decade the City Hall reinforced pillars, joined isolated quarries, ruins, catacombs, and sewers into a single mapped warren, and — so workers would not lose themselves — named the underground streets to match the streets above. The Catacombs of Trier, entered near the Place du Purgatoire, were created when overcrowded surface cemeteries forced the dead underground; visitors are told to extinguish their lanterns and carry white candles instead, a quasi-ritual said to invoke a hidden protection. The deep levels are reputed to touch the corrupt remnants of Fourth Epoch Trier — making the underground a refuge for smugglers, rioters, cultists, and worse.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["district", "underground", "catacombs", "setting"],
    tokenCount: 230,
    narratorOnly: true,
  },
  {
    slug: "trier-stations-transport",
    title: "Trier — Stations & City Transport",
    category: "location",
    content: `Trier moves on rails, river, and rented carriages. Two great steam-locomotive stations anchor its rail traffic: Suhit Station, linking the southern and central regions, and the Northern Train Station, serving the northern provinces — from here a traveller can take a third-, second-, or first-class seat to distant ports, or a private business-class room sold only in packages to keep companions' affairs discreet. Within the city, hiring a carriage by day costs a verl d'or and a quarter for the first hour and more for each hour after; fares rise after midnight, and double-decker carriages carry the thriftier for a few coppet a head. The whole apparatus of tolls, fares, and timetables runs through the gated quartiers, so a journey across Trier is a passage through checkpoints as much as distance. It is a city built for showing oneself off in transit — its avenues, stations, and promenades are stages, and the leisurely pace of its citizens is itself a kind of performance.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["transport", "railway", "setting"],
    tokenCount: 205,
  },
  {
    slug: "intis-republic-overview",
    title: "The Intis Republic — Overview",
    category: "location",
    content: `The Intis Republic is one of the four great nations of the Northern Continent and, after the Loen Kingdom, the second strongest — followed by the Feynapotter Kingdom and the Feysac Empire. It occupies the heart of the continent's west: the Fog Sea at its back, the Feysac Empire to the north, the Loen Kingdom to the east across the Hornacis range and the Midseashire lakes, and Feynapotter, Lenburg, and Masin to the south. It was founded by the Sauron Family after the Trunsoest Empire fell, ruling first as the Intis Kingdom — until the transmigrator-emperor Roselle Gustav overthrew the Sauron crown and, after much upheaval, left behind the parliamentary Republic that governs today under the slogan "Freedom, Equality, Fraternity." Its capital is sunlit Trier, where the Srenzo and Ryan rivers meet; its coin is the verl d'or and the coppet. Two Churches share its faith — the Church of the Eternal Blazing Sun and the Church of the God of Steam and Machinery — and a nation that prides itself on liberty is also a nation of feverish politics, where parliamentary ambition, revolutionary ferment, and the radiant order of the sun-faith all pull against one another.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "intis-republic", "nation", "fifth-epoch"],
    tokenCount: 230,
    narratorOnly: false,
  },
  {
    slug: "trier-arts-and-revolution",
    title: "Trier — The City of Fashion & Its Politics",
    category: "location",
    content: `Trier wears two faces. By day it is the City of Fashion, a world-class sanctuary for artists, musicians, and novelists, where idlers walk turtles on leads to advertise their leisure, salons argue aesthetics over coffee, and a figure in a black hood draws no second glance among so much studied eccentricity. Beneath the elegance runs a hotter current: Intis is a republic, not a monarchy, and Trier is the crucible of its politics. Nearly forty seats of the National Convention are split among the city's twenty quartiers, but seats and prosperity are not shared evenly — wealthier Greater Trier carries a weight the poorer quartiers resent — and that grievance feeds an endless ferment of student radicals, pamphleteers, political clubs, and street-corner orators shouting liberty into the gaslight. Art and revolution feed each other here: a song or a satire can move a quartier faster than a speech, and the same cafés that host the avant-garde host the conspirators. It is a beautiful, restless city, forever performing its own freedom even as the police of each quartier watch the crowds for the ones who mean it.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["setting", "trier", "intis-republic", "politics", "arts", "fifth-epoch"],
    tokenCount: 235,
    narratorOnly: false,
  },
  {
    slug: "intis-wider-republic",
    title: "The Intis Republic — Beyond Trier",
    category: "location",
    content: `The Republic is more than its sunlit capital. To the south lie the provincial reaches toward Lenburg and Masin, farm country and lesser towns that send their grain and their grievances up to Trier. To the north stretches the Fog Sea Province, the cold borderland that screens Intis from the Feysac Empire, and beyond the western coast the Fog Sea itself, out of which rise the Republic's island holdings in the Fog Sea Archipelago. Farthest of all is West Balam, the Intisian colony on the distant Southern Continent, won in the great age of colonisation and held in uneasy rivalry with Loen's own colonies there. The Church of the Eternal Blazing Sun and the Church of the God of Steam and Machinery both reach into these provinces, but their grip loosens with distance from Trier, and the farther corners of the Republic — fog-bound coast, frontier province, and overseas colony alike — are exactly the kind of half-watched country where the Beyonder world does its quietest work.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["geography", "setting", "intis-republic", "provinces", "fifth-epoch"],
    tokenCount: 210,
    narratorOnly: false,
  },
  {
    slug: "trier-church-eternal-blazing-sun",
    title: "Trier — The Church of the Eternal Blazing Sun",
    category: "organization",
    content: `The Church of the Eternal Blazing Sun is the dominant orthodox faith of the Intis Republic and one of the great Churches of the Northern Continent, controlling the Sun Pathway. Its god, the Eternal Blazing Sun, is worshipped as the "Father of All Life," and the Republic — which it shares with the Church of the God of Steam and Machinery — is said to stand at the forefront of the world in the art of gold. Its headquarters and main cathedral, Saint Viève, stand in the Island District of Trier. The Church keeps poor relations with the Church of the Lord of Storms and the Church of the God of Knowledge and Wisdom, the three regarding one another as enemies. Its clergy wear resplendent white robes interwoven with golden thread and greet the sun with raised heads and outspread arms. In Trier the Church is not a distant authority but the visible spiritual power of the city — its golden domes, its night-and-day services, and its sun-priests are woven into the texture of a capital that prides itself on living in the light, even as revolutionary politics and a faith of radiant order strain against one another in the streets.`,
    epoch: 5,
    city: "trier",
    npcs: [],
    sequences: [],
    tags: ["organization", "eternal-blazing-sun", "sun-pathway", "religion", "setting"],
    tokenCount: 240,
    narratorOnly: true,
  },
];
