-- Canon correction (issue #136 follow-up): the Loen–Feysac border is the
-- Amantha Mountain Range (Winter County), NOT the Hornacis range — the Hornacis
-- is the Loen–Intis (western) border (corpus: Loen "separated [from Feysac] by
-- Winter County's Amantha Mountain Range ... and ... from the Intis Republic by
-- the Hornacis Mountain Range"). The Pritz Harbor / Feysac-frontier lore wrongly
-- named the Hornacis as the northern frontier; this resyncs the three SEEDED
-- rows to the corrected TS (the matching code-only files — gazetteer/narration/
-- glossary/start-scenarios — need no migration). resync_pathway_lore_seq0 pattern.

update public.lore_entries set content = 'Pritz Harbor is the Loen Kingdom''s chief naval port, set on the cold northern coast below the Amantha mountain range that walls Loen off from the Feysac Empire. It is a working navy town before it is anything else: dry-docks and shipyards, powder magazines and victualling yards, ironclads and gunboats riding at anchor in a grey, fog-bound roadstead, and streets full of sailors, marines, and the families that supply them. The Amantha passes at its back are a smuggler''s country and a monster''s country both, so the garrison is heavy and the night watch real. For the Beyonder world the harbour matters as a chokepoint: contraband curios, sealed artifacts, and people who would rather not be noticed all move through a port this busy, and the Church of the Lord of Storms keeps a watchful presence over a town that lives and dies by the sea''s temper.', token_count = 180 where slug = 'pritz-harbor-overview';
update public.lore_entries set content = 'Beneath Pritz Harbor''s fog the real business of the town is the navy. The royal dockyards run the length of the grey roadstead — building-slips and dry-docks, powder magazines and victualling stores, ironclads under repair and gunboats fitting out — and a whole town of riggers, shipwrights, chandlers, and the families that serve them lives by the rhythm of the fleet. The garrison is heavy, the night watch real, and the Amantha passes at the harbour''s back are worked hard by smugglers running goods over the mountains to and from the Feysac frontier. Pritz is above all a city of the Church of the Lord of Storms: the storm-faith of sailors and soldiers is the dominant creed here, its seafront chapels blessing every long voyage, and so it is the Lord of Storms'' own Beyonder enforcers — the Mandated Punishers — who hold the strongest hand over the uncanny in this port, more even than the Nighthawks. Sealed cargo, drowned things, and Beyonders who would rather not be logged all pass through a navy town this busy, and the storm-priests watch the water for them.', token_count = 230 where slug = 'pritz-harbor-naval-yard';
update public.lore_entries set content = 'If the Mandated Punishers keep only a small office in inland Tingen, in the naval port of Pritz Harbor they are at their strongest. The Mandated Punishers are the Beyonder arm of the Church of the Lord of Storms, and Pritz is a storm-faith town to its bones — a city of sailors, marines, and dockworkers whose creed is the sea''s own. Here the Punishers, not the Nighthawks, are the first hand on any uncanny trouble: smuggled Beyonder materials coming over the water or down through the Amantha passes, sea-creature manifestations off the cold roadstead, drowned things that will not stay drowned, and rogue Beyonders among the fleet''s crews. Their style suits the town — direct, aggressive, more inclined to force than to the Nighthawks'' patient investigation — and their members run heavily to the Sailor (Tyrant) pathway, with its dominion over storm, water, and the body. The harbour''s heavy garrison and real night-watch give them cover and muscle both, and a quiet understanding keeps their jurisdiction and the Nighthawks'' from colliding more than the sea already does.', token_count = 220 where slug = 'mandated-punishers-pritz';
