-- Seed the Rorsted Archipelago / Bayam lore (world build-out 8, issue #137): the
-- archipelago's isles and the Sonia Sea's lanes & powers, a deepened Cathedral
-- of Waves, the native sea-god faith + the Mandated Punishers' maritime presence
-- (organizations.ts), and the Rorsted NPCs Kalat, Ralph, and Danitz Dubois
-- (npcs.ts). 8 new entries, all epoch 5. Generated from the canonical TS source;
-- same lore_entries INSERT format as the earlier seed migrations. narratorOnly
-- is a TS-only prompt flag (no column), intentionally not persisted. Parity
-- verified via the Supabase MCP.
--
-- Two UPDATEs accompany the inserts:
--   * `bayam-sea-god-kalvetua` is recategorised metaphysics -> location. A
--     `metaphysics` + epoch entry is injected as global Fifth-Epoch *setting*
--     (getLoreByEpochSetting) into EVERY Fifth character's curated lore, which
--     leaked this Bayam-specific belief to the whole mainland; as a city-keyed
--     `location` it stays confined to a Bayam character (the issue #132 rule).
--   * `bayam-cathedral-of-waves` is deepened (content + the member Jahn Kottman
--     + token count) per the issue's "deepen the stub".

insert into public.lore_entries (slug, title, category, content, pathway, epoch, city, npcs, sequences, tags, token_count)
values
  ('bayam-rorsted-isles', 'The Rorsted Archipelago — Its Isles', 'location', 'The Rorsted Archipelago — the "Spice Archipelago" — is a scatter of islands in the central Sonia Sea, and Bayam, on Blue Mountain Island, is its capital and the greater half of it. Blue Mountain Island is the rich one: gold, silver, copper, coal, and iron in its forested hills and fruit enough that the first colonists named the place for plenty. Beyond it the archipelago runs out into lesser isles. Symeem Island lies at the far end, a place of old elven ruins and the small port of Symeem Harbor, known for its Gurney Sap and watched over by an outlying chapel of the storm-faith. Longtail Island marks the southern edge of the Rorsted waters. Loen has held the whole archipelago for less than fifty years, and its grip shows everywhere — the governor-general''s office, a Parliament and courts staffed at the top entirely by Loenese, the harbour patrols and the garrison — yet the islands keep their own weather, their own tongues, and their own old loyalties beneath the colonial paint. The natives fill the lower ranks; the descendants of the islands'' former kings and chieftains hold the middle; and the resentment of the ruled is never far below the surface.', null, 5, 'bayam', '{}', '{}', ARRAY['geography', 'setting', 'rorsted-archipelago', 'isles', 'colony', 'fifth-epoch'], 245),
  ('bayam-sonia-sea-lanes', 'The Sonia Sea & Its Lanes', 'location', 'The Sonia Sea is the great eastern ocean off the Northern Continent, and Bayam lives by it. Two powers hold its islands. The Loen Kingdom rules the Rorsted Archipelago in the central waters; the Feysac Empire holds the north and east — Sonia Island, the largest island in the whole sea and an old elf refuge Feysac took from Loen generations ago, and the Gargas Archipelago at the eastern front, a whale-fishing, white-walled colony (its capital Nas, the "City of White") so loosely policed it is half a pirates'' playground. Loen''s own outposts string the sea-lanes between: the busy free port of Oravi Island a few days'' sail out, the storm-faith''s holy seat on Pasu Island, and the once-famous Bansy Harbor on the long run back toward Pritz Harbor, now fallen to ruin. Far to the east, past Gargas, the charts give out at the Sea of Ruins — a dead and dangerous water no nation claims, where old battles of the gods are said to litter the deep. And away on the continent''s far western side lies the Fog Sea with its Intis spice-islands, a world every Bayam sailor has heard of in the harbour bars and almost none will ever see.', null, 5, 'bayam', '{}', '{}', ARRAY['geography', 'setting', 'sonia-sea', 'gargas-archipelago', 'sea-lanes', 'fifth-epoch'], 255),
  ('sea-god-faith-overview', 'The Sea-God Faith of the Rorsted Archipelago', 'organization', 'Long before Loen''s fleets came, the islanders of the Rorsted Archipelago prayed to a sea-god of their own — a vast blue serpent said to hold back the earthquakes and the tsunamis — and on Blue Mountain Island and across the Sonia Sea many of them pray to him still. The colony has outlawed the worship: the Church of the Lord of Storms brooks no rival faith on its own waters, and its priests haul heretics in by the handful every month or two, while the natives bury their dead apart and keep their shrines up the jungle slopes and out of sight. Pilgrims still trade in the god''s charms — tokens blessed to turn a blade or let a man swim like a fish, though the virtue is said to bleed out of them within a few months — and the faith has become a banner for everything the islanders resent about foreign rule. Where the storm-faith is the religion of the harbour and the garrison, the old sea-god is the religion of the back-streets, the fishing villages, and the quiet talk of independence. To the colonial authorities it is heresy; to the islanders it is the last of themselves they have not surrendered.', null, 5, 'bayam', '{}', '{}', ARRAY['sea-god', 'kalvetua', 'native-belief', 'bayam', 'religion'], 240),
  ('sea-god-resistance', 'The Resistance & the Drowned God''s Devotees', 'organization', 'Beneath the scattered back-street worship runs something organised: the Resistance, the independence movement of the Rorsted Archipelago, with the sea-god''s faith for its banner and the back-country and the open sea for its hiding-places. Its leader is Kalat — "Baldy Kalat," a wheelchair-bound Beyonder once schooled in the Feysac Empire — and among its quiet backers is the half-native trader Ralph, whose trading company funds it from behind a respectable ledger. The Resistance cooperates with the archipelago''s pirates and adventurers and is courted from the shadows by Loen''s rivals, who would gladly see the colony bleed. Deeper and far more dangerous are the sea-god''s true devotees: the guard who keep his hidden lair, and the old priests who once fed him living sacrifices — for the islanders'' god is no superstition but a genuine Sea King of the Tyrant Pathway, a sea-serpent the Church of the Lord of Storms has hunted for over a century. To the colonial authorities the whole tangle is heresy and sedition; to the islanders it is a war for their own souls that the storm-priests must never be allowed to win.', null, 5, null, ARRAY['Kalat', 'Ralph'], ARRAY[4], ARRAY['sea-god', 'resistance', 'kalvetua', 'tyrant-pathway', 'secret-society'], 245),
  ('mandated-punishers-bayam', 'Mandated Punishers — Rorsted Archipelago Presence', 'organization', 'In the Rorsted Archipelago the Mandated Punishers — the Beyonder arm of the Church of the Lord of Storms — are not the junior partner they are in an inland Loen city; here, on the storm-faith''s own sea, they are the first and final word on anything uncanny. Of all the nations only Loen''s Church wields authority over the sea, and the Sonia Sea is its domain: from the Cathedral of Waves in Bayam the Punishers police the smuggled curios moving through the busiest port of the eastern ocean, sea-creature manifestations off the islands, rogue Beyonders among the pirate crews and the adventurers'' bars, and above all the outlawed sea-god cult they hunt without end. Their members run heavily to the Tyrant Pathway — the sea''s own power of storm, water, and the body — leavened with the occasional White Tower analyst, and their style is the pathway''s own: headlong, aggressive, more inclined to force than to patient inquiry. Over them all stands the Sea King, Cardinal Jahn Kottman, who has made the archipelago''s hidden world answer to Bayam for years.', null, 5, 'bayam', ARRAY['Jahn Kottman'], '{}', ARRAY['mandated-punishers', 'lord-of-storms', 'maritime', 'bayam', 'tyrant-pathway', 'beyonder-organization'], 235),
  ('npc-kalat', 'Baldy Kalat — Leader of the Resistance', 'npc', 'Kalat, called "Baldy Kalat," is the leader of the Resistance — the independence movement of the Rorsted Archipelago that fights the Loen colony beneath the banner of the outlawed Sea God Kalvetua. A wheelchair-bound mid-Sequence Beyonder once schooled in the Feysac Empire, he is shrewd, patient, and devout, holding the back-country camps and sea-hideouts of the movement together and trading in the sea-god''s relics — among them a sword he will swear is the holy blade of Kalvetua himself. He keeps faith with the fanatic Edmonton and the merchant Ralph, courts the archipelago''s pirates and adventurers, and takes quiet coin from Loen''s rivals, all toward the one end of seeing the islands rule themselves again. To the Church of the Lord of Storms he is a heretic and a rebel to be hunted; to the natives of Bayam he is the keeper of the last thing the colony could not take from them.', null, 5, 'bayam', ARRAY['Kalat', 'Ralph'], ARRAY[6], ARRAY['resistance', 'sea-god', 'kalvetua', 'bayam', 'native-belief'], 195),
  ('npc-ralph', 'Ralph — The Half-Native Trader of Bayam', 'npc', 'Ralph is the owner of the Ralph Trading Company, a respectable Bayam merchant house built on the spice trade and the long sea-routes of the Sonia Sea — and a former pirate and seaman besides. Half-native, his mother a woman of the Rorsted islands, he keeps two faces: the prosperous colonial trader who deals openly with Loen factors and foreign captains alike, and the secret and reverent worshipper of the Sea God Kalvetua who funds the Resistance from behind his clean ledgers. He will, given the measure of a likely stranger, try to introduce them to "our god," for he believes the islanders'' cause and the islanders'' faith are one and the same. His wealth, his ships, and his standing make him far more useful to the movement than any zealot — a quiet pillar of the independence struggle whom the colonial authorities have never thought to suspect.', null, 5, 'bayam', ARRAY['Ralph', 'Kalat'], '{}', ARRAY['resistance', 'sea-god', 'kalvetua', 'bayam', 'trade', 'colony'], 185),
  ('npc-danitz-dubois', 'Danitz Dubois — Boatswain of the Golden Dream', 'npc', 'Danitz Dubois is a boatswain of the Golden Dream, the treasure-seeking pirate fleet of the Pirate Admiral "Vice Admiral Iceberg," Edwina Edwards — a fleet that, unlike most, neither murders nor plunders but hunts the relics and ruins of the seas. A restless, talkative young seaman who has drifted between the great pirate crews and the Bayam underworld, he keeps one foot in the Rorsted Archipelago''s tangled affairs and a quiet sympathy for its native cause. He is the kind of crewman who knows every bar on the harbour and every captain worth the name, and who can get a willing hand a berth on a ship bound anywhere in the Sonia Sea. In the great events to come he will find a stranger role still as a go-between for the islands'' hidden powers — but for now he is simply an able sailor of a famous fleet, at home in Bayam''s salt and rumour.', null, 5, 'bayam', ARRAY['Danitz Dubois', 'Edwina Edwards'], '{}', ARRAY['golden-dream', 'pirate', 'privateer', 'bayam', 'sonia-sea'], 195);

update public.lore_entries set category = 'location' where slug = 'bayam-sea-god-kalvetua';

update public.lore_entries set content = 'The Cathedral of Waves is the Church of the Lord of Storms'' great seat in the Rorsted Archipelago — for now the largest cathedral in all Bayam, its bells timed to the tides and its seafront steps worn by sailors leaving offerings before a voyage. But its true weight is not in its stone. Of all the nations only Loen''s storm-faith holds authority over the sea, and in the Sonia Sea that authority runs through this cathedral: it is the diocese from which the Church administers the Beyonder world of the whole archipelago, answering to the Pontiff Gaard II at the Chasm of Storms Cathedral on distant Pasu Island. Its archbishop, the Cardinal Jahn Kottman — a Sea King of fearsome repute who boasts that even a War Bishop must bow his head in his waters — has long been the real ruler of the islands'' hidden world, and through him the Mandated Punishers keep their watch. From here the Church wages its quiet, endless war on the outlawed worship of the native sea-god, hauling heretics in every month or two; and from here it would answer, should the drowned thing the old cardinals are said to have driven into hiding a century ago ever stir again.', npcs = ARRAY['Jahn Kottman'], token_count = 250 where slug = 'bayam-cathedral-of-waves';
